### ISSUE TITLE
[PWA] What's the actual use-case for the pwa-plugin?

### ISSUE THREAD

**Issue by alexandernst** [vuejs/vue-cli#3006] opened 2018-11-25 02:32 UTC
### Version
3.1.1

### Node and OS info
Node 10.x / yarn 1.7.0 / Alpine 3.8

### Steps to reproduce
I spent some time tweaking the `pwa` section in my `vue.config.js`. Then I ran `vue build`, expecting the PWA plugin to generate a `manifest.json`, but I was surprised to see my old (and empty) `manifest.json` from the `public` folder just copied to the `dist` folder.

Then I spent some more time looking at documentation and issues in both vue-cli and @vue/pwa repos, and I couldn't find a real reason about what's the exact purpose of the `pwa` section in the `vue.config.js` file.

If the `manifest.json` is not generated from the content of the `pwa` section in my `vue.config.js`, then what's the point in having that section at all?

### What is expected?
`vue build` should create a `manifest.json` file based on the config in `vue.config.js`

### What is actually happening?
Nothing.

**Comment by lululeon** [comment] 2018-11-25 20:18
I'm in the exact same bind. manifest.json and service worker files not being generated.

- Node 8.9.1
- @vue/cli-service@3.1.4
- vue ^2.5.17

Not sure what files in /dist are based on: see no resemblance to files in static/*, static/index.html or vue.config.js.

**Comment by alexandernst** [comment] 2018-11-25 22:29
Check my other open issue (#3007). If that get's implemented it would totally make sense to generate the `manifest.json` as it would be way less prone to have all the images in one place and then let Vue generate the index, the manifest and so on with the correct paths to each image. 

Also have a look at how https://github.com/arthurbergmz/webpack-pwa-manifest handles the images stuff, it's a very clean design.

**Comment by lululeon** [comment] 2018-11-26 23:37
@alexandernst thanks for asking and @LinusBorg thanks for clarifying. The fact that the PWA plugin has all these settings that map so nicely to a PWA manifest file, AND that it (or something else) auto-injects a link for manifest.json into the index.html template, led me to believe that:
- public/manifest.json can be deleted and the build will magically regenerate it
- public/manifest.json will be injected with settings from the PWA plugin setup in vue.config.js
- the build process will complain and alert you if manifest.json is missing for whatever reason or cannot be populated with your settings in the PWA plugin.

I've _**finally**_ realised that none of these things are true, lol.

**Comment by LinusBorg** [comment] 2018-11-30 14:22
Docs could probably be improved, but that's generally on the roadmap. I'll close this issue since it's not a bug.

If you want to open a feature request to handle manifest.json in a different way, open a new issue for it and describe what it should do, exactly.

PRs would also be welcome.

**Comment by sodatea** [comment] 2019-05-26 07:43
Implemented in https://github.com/vuejs/vue-cli/pull/2981

**Closed by sodatea** 2019-05-26 07:43 UTC
Labels: feat: pwa, feature request
