### ISSUE TITLE
jest.config.js > testMatch pattern is not working on windows 10 machine

### ISSUE THREAD

**Issue by rav84** [vuejs/vue-cli#1777] opened 2018-07-06 09:30 UTC
### Version
3.0.0-rc.3

### Steps to reproduce
Create new project with jest using cli on windows 10 machine. Run "yarn run test:unit".

vue-cli creates jest.config.js file with following testMatch
`'<rootDir>/(tests/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx))'`

### What is expected?
Tests within 
`/tests/unit/**` and
`**/__tests__/**`
should be found and run.

### What is actually happening?
Jest complains: no tests found.
I think on windows jest is not able to match the whole path.

---
by removing rootDir from the testMatch it works.

**Comment by LinusBorg** [comment] 2018-07-06 09:39
duplicate of #1584

**Closed by LinusBorg** 2018-07-06 09:39 UTC

**Comment by karthikatl** [comment] 2019-12-18 17:16
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _Object$defineProperty from "../../core-js/object/define-property";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      17 |             <template #selection="data">
      18 |               <v-chip :key="data.item.entity_id" :input-value="data.selected">
    > 19 |                 <p>{{ data.item.display_name }}-{{ data.item.profile.emp_id }}-{{ data.item.profile.guard_id}}</p>
         |                                               ^
      20 |               </v-chip>
      21 |             </template>
      22 |           </v-autocomplete>

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at src/ui/sections/Patrol/PatrolSupervisorValidationStatus.vue:19:47
      at Object.<anonymous> (src/ui/sections/Patrol/PatrolSupervisorValidationStatus.vue:166:3)

i have this error. any solution
