### ISSUE TITLE
vue build sample in documentation does not work because of absolute paths

### ISSUE THREAD

**Issue by rowild** [vuejs/vue-cli#1948] opened 2018-07-25 20:51 UTC
### Version
3.0.0-rc.5

### Reproduction link
[https://codepen.io/rowild/pen/VBzvzr?editors=1010](https://codepen.io/rowild/pen/VBzvzr?editors=1010)

### Steps to reproduce
1. Create a folder on desktop
2. Create App.vue with minimal code as in documentation
3. "vue build"

### What is expected?
The index.html dist folder can be clicked and the text of App.vue will be shown.

### What is actually happening?
White screen. The linked Javascript starts with "/", which is an absolute path on a operation system. If the paths are prepended with a dot (./js/...) everything works fine.

---
No example possible, because this report needs "vue build" on desktop. But the link to the "example" again describes the problem. Please be fair and have a look into it instead of immediately deleting the issue, because the behaviour cannot be rebuild on any of those coding platforms. Thank you!

And, IMO, if this is NOT considered an error, the docu should at least mention the "behaviour".
Thank you!

**Comment by Akryum** [comment] 2018-07-25 20:56
Duplicate of #1572

**Closed by Akryum** 2018-07-25 20:56 UTC
