### ISSUE TITLE
Replace svg rule to svg-sprite-loader doesn't work in chainWebpack

### ISSUE THREAD

**Issue by clixiang** [vuejs/vue-cli#2052] opened 2018-08-03 06:44 UTC
### Version
3.0.0-rc.10

### Node and OS info
Node 8.11.3

### Steps to reproduce
1. Install svg-sprite-loader:  `npm install --save-dev svg-sprite-loader`
2. Modify `vue.config.js`

```
module.exports = {
  chainWebpack: config => {
    const svgRule = config.module.rule('svg')
    svgRule.uses.clear()

    svgRule
      .include
      .add('./src/icons')
      .end()
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
      .options({
        symbolId: 'icon-[name]'
      })
  }
}
```

3. Run `npm run serve`

### What is expected?
compile success.

### What is actually happening?
``` 
warning  in ./src/icons/svg/nested.svg

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1529559567446" class="icon" style="" viewBox="0 0 1167 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1767" xmlns:xlink="http://www.w3.org/1999/xlink" width="227.9296875" height="200"><defs><style type="text/css"></style></defs><path d="M0.015952 74.459413A2.286 2.286 1440 1 0 145.85218 74.459413 2.286 2.286 1440 1 0 0.015952 74.459413zM291.720312 1.525347 1166.801488 1.525347 1166.801488 147.361574 291.720312 147.361574zM291.720312 366.163773A2.286 2.286 1440 1 0 437.55654 366.163773 2.286 2.286 1440 1 0 291.720312 366.163773zM583.424672 293.229707 1166.801488 293.229707 1166.801488 439.065934 583.424672 439.065934zM291.720312 949.540588A2.286 2.286 1440 1 0 437.55654 949.540588 2.286 2.286 1440 1 0 291.720312 949.540588zM583.424672 876.638427 1166.801488 876.638427 1166.801488 1022.474654 583.424672 1022.474654zM583.424672 657.836228A2.286 2.286 1440 1 0 729.2609 657.836228 2.286 2.286 1440 1 0 583.424672 657.836228zM875.129032 584.934067 1166.801488 584.934067 1166.801488 730.770294 875.129032 730.770294z" p-id="1768"></path></svg>

 @ ./src/icons/svg sync nonrecursive \.svg$
 @ ./src/icons/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.2.4.20:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 
  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://10.2.4.20:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.
```

**Comment by LinusBorg** [comment] 2018-08-03 07:45
Please provide a runnable reproduction as explained in the "new issue" website that you used. 

Thanks.

**Comment by yyx990803** [comment] 2018-08-07 01:32
Closing (no reproduction)

**Closed by yyx990803** 2018-08-07 01:32 UTC
Labels: needs reproduction

**Comment by Estelle00** [comment] 2018-08-18 14:53
请问你的问题怎么解决的呢

**Comment by AaronChen2012** [comment] 2018-09-03 01:04
这个问题怎么解决？

**Comment by gu0zh1q1ang** [comment] 2023-05-08 03:32
There must be another rule also matches /\.svg$/, which makes a recursion, just delete one of them. It works for me.
```js
{
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        include: [resolve('src/assets/icons')],
        options: {
          symbolId: 'icon-[name]'
        }
},
{
        test: /\.(png|jpe?g|gif|svg|ico)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
}
```
