### ISSUE TITLE
Build fails @vue/test-utils and chai should be in dependencies not in devdependencies 

### ISSUE THREAD

**Issue by MSDDR** [vuejs/vue-cli#2918] opened 2018-11-08 04:27 UTC
### Version
3.1.1

### Reproduction link
N/A

### Node and OS info
Node 11.1.0 / Windows

### Steps to reproduce
1. run vue ui
2. turn on all features
3. turn on babel and class component style
4. use sass css preprocessor
5. use eslint airbnb
6. turn on both lint options
7. use mocha   chai
8. use nightwatch

### What is expected?
build runs without errors

### What is actually happening?
Build fails @vue/test-utils and chai should be in dependencies not in devdependencies , then gets stuck running completion hooks forever

**Comment by LinusBorg** [comment] 2018-11-08 21:42
> @vue/test-utils and chai should be in dependencies not in devdependencies

Why? they are devDependencies.

> Build fails

 mocha doesn't run when running `build`, so how should this have any effect on your build? What's the erorr?

So: I can't follow your "reproduction".

**Comment by sodatea** [comment] 2018-11-09 04:12
Duplicate of https://github.com/vuejs/vue-cli/issues/2554

😂But I forgot why I marked that issue as `upstream`…

**Closed by sodatea** 2018-11-09 04:12 UTC
Labels: needs reproduction
