### ISSUE TITLE
Cypress --headless no longer works on windows

### ISSUE THREAD

**Issue by badders** [vuejs/vue-cli#4807] opened 2019-11-07 10:44 UTC
### Version
4.0.5

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  4.0.5
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  4.0.5
    @vue/cli-plugin-babel: ^4.0.5 => 4.0.5
    @vue/cli-plugin-e2e-cypress: ^4.0.5 => 4.0.5
    @vue/cli-plugin-eslint: ^4.0.5 => 4.0.5
    @vue/cli-plugin-router: ^4.0.5 => 4.0.5
    @vue/cli-plugin-typescript: ^4.0.5 => 4.0.5
    @vue/cli-plugin-unit-jest: ^4.0.5 => 4.0.5
    @vue/cli-plugin-vuex:  4.0.5
    @vue/cli-service: ^4.0.5 => 4.0.5
    @vue/cli-shared-utils:  4.0.5
    @vue/component-compiler-utils:  3.0.0
    @vue/eslint-config-prettier: ^5.0.0 => 5.0.0
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.2.3 => 5.2.3
    jest-serializer-vue:  2.0.2
    typescript: ^3.7.2 => 3.6.4 (3.5.3)
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.1.0 => 7.1.0
    vue-cli-plugin-electron-builder: ^1.4.0 => 1.4.0
    vue-cli-plugin-vuetify: ^2.0.2 => 1.1.1
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-jest:  3.0.5
    vue-loader:  15.7.1
    vue-property-decorator: ^8.3.0 => 8.3.0
    vue-resize: ^0.4.5 => 0.4.5
    vue-router: ^3.1.3 => 3.1.3
    vue-socket.io-extended: ^4.0.1 => 4.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vue-unique-id: ^2.0.0 => 2.0.0
    vuejs-logger: ^1.5.3 => 1.5.3
    vuetify: ^2.1.9 => 2.1.9
    vuetify-loader: ^1.3.0 => 1.3.0
    vuex: ^3.1.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
create a new vue cli project with cypress e2e testing & typescript

run vue-cli-service test:e2e --headless

### What is expected?
Tests run and output results, which works fine on linux and outputs correctly

### What is actually happening?
 WARNING  Compiled with 2 warnings                                                                                                                                                         10:40:22
 warning 

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  js/chunk-vendors.efe30bc0.js (299 KiB)

 warning 

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (307 KiB)
      js/chunk-vendors.efe30bc0.js
      css/app.ae7c37ea.css
      js/app.c8779371.js

No type errors found
Version: typescript 3.5.3
Time: 2108ms

  App running at:
  - Local:   http://localhost:8080/
  - Network: ***********************

  App is served in production mode.
  Note this is for preview or E2E testing only.

 ERROR  Error: Command failed: ***********************\cyp\node_modules\cypress\bin\cypress run --config baseUrl=http://localhost:8080/
Error: Command failed: **********************\cyp\node_modules\cypress\bin\cypress run --config baseUrl=http://localhost:8080/
    at makeError (***********************\node_modules\execa\index.js:174:9)
    at ***********************\cyp\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

---
Same project works fine on linux, only fails to run on windows 10

**Comment by badders** [comment] 2019-11-07 11:17
Corrected environment info, pasted from wrong project:

Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  4.0.5
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  4.0.5
    @vue/cli-plugin-babel: ^4.0.0 => 4.0.5
    @vue/cli-plugin-e2e-cypress: ^4.0.0 => 4.0.5
    @vue/cli-plugin-eslint: ^4.0.0 => 4.0.5
    @vue/cli-plugin-router: ^4.0.0 => 4.0.5
    @vue/cli-plugin-typescript: ^4.0.0 => 4.0.5
    @vue/cli-plugin-unit-jest: ^4.0.0 => 4.0.5
    @vue/cli-plugin-vuex: ^4.0.0 => 4.0.5
    @vue/cli-service: ^4.0.0 => 4.0.5
    @vue/cli-shared-utils:  4.0.5
    @vue/component-compiler-utils:  3.0.1
    @vue/eslint-config-prettier: ^5.0.0 => 5.0.0
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    jest-serializer-vue:  2.0.2
    typescript: ~3.5.3 => 3.5.3
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.0.2 => 7.1.0
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-jest:  3.0.5
    vue-loader:  15.7.2
    vue-property-decorator: ^8.3.0 => 8.3.0
    vue-router: ^3.1.3 => 3.1.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by badders** [comment] 2019-11-07 11:40
additionally i configured the project with jest and eslint

**Comment by sodatea** [comment] 2019-11-07 14:14
Duplicate of #4799
See https://github.com/cypress-io/cypress/issues/5466

**Closed by sodatea** 2019-11-07 14:14 UTC
