### ISSUE TITLE
请尽快修复coffee-script安装失败的问题

### ISSUE THREAD

**Issue by ChangedenCZD** [vuejs/vue-cli#657] opened 2017-11-30 09:18 UTC
目前无法完成 npm i -g vue-cli 的操作。
错误问题：Error: coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
分析原因：coffee-script模块已被移除，改为 coffeescript

**Comment by inickel** [comment] 2017-11-30 09:26
mark

**Comment by westeross** [comment] 2017-11-30 09:27
CoffeeScript has moved, wait until update

**Comment by Tobee4Lin** [comment] 2017-11-30 09:30
still doesn't work ：)

**Comment by sansroman** [comment] 2017-11-30 09:43
you can modify package.json and run `npm update`

**Comment by ChangedenCZD** [comment] 2017-11-30 09:45
@sansroman modify which module's package.json

**Comment by sansroman** [comment] 2017-11-30 09:52
@ChangedenCZD  I modify global,you can try `npm install coffee-script -g & npm update & npm install vue-cli -g`,This solves my problem, and I don't know if it's the same for you.

**Comment by royeaher** [comment] 2017-11-30 09:55
@sansroman sorry,it also don`t work

**Comment by ChangedenCZD** [comment] 2017-11-30 09:56
@sansroman `npm install coffee-script -g` no work
>

**Comment by sansroman** [comment] 2017-11-30 09:56
@ChangedenCZD  https://stackoverflow.com/questions/13011290/cannot-find-module-coffee-script

**Comment by ChangedenCZD** [comment] 2017-11-30 09:58
@sansroman [https://www.npmjs.com/package/coffee-script](https://www.npmjs.com/package/coffee-script)  CoffeeScript has moved!

**Comment by sansroman** [comment] 2017-11-30 10:00
@ChangedenCZD So replace with coffee-script

**Comment by ChangedenCZD** [comment] 2017-11-30 10:03
@sansroman how can i do this?wait for official update?

**Comment by sansroman** [comment] 2017-11-30 10:06
@ChangedenCZD What is the wrong message? when you run `npm install coffee-script -g`

**Comment by ChangedenCZD** [comment] 2017-11-30 10:07
@sansroman Error: coffee-script@1.12.8 postinstall: node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

**Comment by inickel** [comment] 2017-11-30 10:09
https://github.com/jonschlinkert/gray-matter/pull/56

**Comment by sansroman** [comment] 2017-11-30 10:13
@ChangedenCZD  no tube,please continue

**Comment by royeaher** [comment] 2017-11-30 10:16
@sansroman this answer [https://stackoverflow.com/questions/13011290/cannot-find-module-coffee-script] comes from five years ago

**Comment by sansroman** [comment] 2017-11-30 10:20
@royeaher  sorry, but the same issue fixed for me

**Comment by posva** [comment] 2017-11-30 11:09
Duplicate of #655

**Closed by posva** 2017-11-30 11:09 UTC
