### ISSUE TITLE
VSCode shows eslint error with '@vue/airbnb' when using webpack aliases in import paths

### ISSUE THREAD

**Issue by KokoTa** [vuejs/vue-cli#2546] opened 2018-09-18 09:07 UTC
### Version
3.0.3

![image](https://user-images.githubusercontent.com/14892053/45676821-447e0280-bb65-11e8-9b7c-769a05753306.png)

### Node and OS info
Node 10.7.0

### Steps to reproduce
Vscode will throw error, but app running successful.

### What is expected?
no error info

### What is actually happening?
throw error info

---

**Comment by LinusBorg** [comment] 2018-09-18 17:19
Please share the repository

**Comment by KokoTa** [comment] 2018-09-19 01:03
![image](https://user-images.githubusercontent.com/14892053/45724846-8e5cfc00-bbea-11e8-9da7-0003438b273c.png)
Build with default configuration @LinusBorg

**Comment by LinusBorg** [comment] 2018-09-19 07:03
Do `npm run serve` and `npm run build` work?

**Comment by KokoTa** [comment] 2018-09-19 07:04
yes, running successful.

**Comment by LinusBorg** [comment] 2018-09-19 07:06
Then this is a problem with the eslint integration of your editor

**Comment by KokoTa** [comment] 2018-09-19 07:09
The same situation，app can work，but error still exist.

**Comment by LinusBorg** [comment] 2018-09-19 07:10
So the error is only in your editor? Then I think your editor's eslint integration doesn't play nice with eslint-airbnb ?

**Comment by LinusBorg** [comment] 2018-09-19 07:12
Possibly related: https://github.com/Microsoft/vscode-eslint/issues/405

**Comment by KokoTa** [comment] 2018-09-19 07:12
I use Vscode, I don't know. OK, I try to see it.

**Comment by blitheinsz** [comment] 2018-11-06 12:09
1 upgrade  vscode editor
2 upgrade vscode-plugin   ESLint to  1.7
3  ok

**Comment by 2xAA** [comment] 2019-01-14 15:36
SublimeLinter-eslint seems to also have the same issue.

eslint version v5.12.0 (local and global)
Latest Sublime Linter and SublimeLinter-eslint

Built with vue cli 3.3.0. Vuex, Router and Airbnb linting.

`npm run build` also works fine.
![screen shot 2019-01-14 at 15 32 09](https://user-images.githubusercontent.com/554219/51122576-15755600-1812-11e9-9a9e-36ec305cff62.png)

**Comment by LinusBorg** [comment] 2019-01-14 15:39
Then you should probably open an issue in their repository. We can't influence how your editor plugins work

**Comment by sodatea** [comment] 2019-01-20 08:39
No longer reproducible with the latest versions of vscode, vscode-eslint, @vue/cli…
So I'm closing this issue.

**Closed by sodatea** 2019-01-20 08:39 UTC
Labels: feat: eslint

**Comment by STLighter** [comment] 2019-01-31 06:01
> Actually, red herring. The project folder is a subdirectory of a larger project. (SublimeLinter-)eslint was getting confused.
> 
> SublimeLinter-eslint seems to also have the same issue.
> 
> eslint version v5.12.0 (local and global)
> Latest Sublime Linter and SublimeLinter-eslint
> 
> Built with vue cli 3.3.0. Vuex, Router and Airbnb linting.
> node version 11.5.0.
> 
> `npm run build` also works fine.
> ![screen shot 2019-01-14 at 15 32 09](https://user-images.githubusercontent.com/554219/51122576-15755600-1812-11e9-9a9e-36ec305cff62.png)

Same problem with you! When I open the subdirectory only, everything works well. But if I open the large project, vscode shows no-unresolved error.

vscode: v1.30.2
eslint extension: v1.8.0

**Comment by TaylorDale** [comment] 2019-04-15 01:25
> Same problem with you! When I open the subdirectory only, everything works well. But if I open the large project, vscode shows no-unresolved error
Thanks for that - spent a good hour on this one trying to figure out why it wasn't resolving.

**Comment by dpgalloway** [comment] 2020-02-26 18:47
In case anyone else is still struggling with this, I realized the same thing as others that the issue was caused by my front-end code being in a sub-directory of the main project. To fix, add this to your settings.json (change "client" to the name of your front-end sub-directory):

```
    "eslint.workingDirectories": [
      { "directory": "./client", "changeProcessCWD": true },
    ],
```
