### ISSUE TITLE
Please update babel dependencies.

### ISSUE THREAD

**Issue by 634750802** [vuejs/vue-cli#2376] opened 2018-08-28 09:31 UTC
### What problem does this feature solve?
The official [babel 7.0.0](https://github.com/babel/babel/releases/tag/v7.0.0) has been released,  but the version used by `@vue/babel-preset-app` is 'beta.47'.

Thanks for your efforts to create such a great framework.

### What does the proposed API look like?
Update babel dependencies' version from '7.0.0-beta.47' to '7.0.0'.

**Comment by Kocal** [comment] 2018-08-28 13:44
@LinusBorg there is a PR #2377

**Comment by corbinu** [comment] 2018-08-28 23:29
@634750802 Shouldn't "babel-core" deps also be changed to "@babel/core"?

**Comment by 634750802** [comment] 2018-08-29 02:05
@corbinu  Which package.json file? In packages/@vue/babel-preset-app/package.json there is no "babel-core".

**Comment by 634750802** [comment] 2018-08-29 02:40
The main "babel-core" dep is under version [7.0.0-bridge](https://www.npmjs.com/package/babel-core/v/7.0.0-bridge.0). I think this may be a feature.

**Comment by corbinu** [comment] 2018-08-29 03:53
Yes as in it was the "bridge" until 7.0.0 was released ... @babel/core replaces it.

<img width="1353" alt="screen shot 2018-08-28 at 8 52 54 pm" src="https://user-images.githubusercontent.com/533625/44764404-5dfed200-ab04-11e8-8abc-9c1706107dad.png">

**Comment by 634750802** [comment] 2018-08-29 05:46
I'm not sure about what the bridge used for. Does it affect the babel compiler? I found another '@babel/core' dep in '@vue/cli-plugin-babel' which I think is the dep that babel used in fact.

**Comment by 634750802** [comment] 2018-08-29 05:50
```
# yarn.lock
jest-config@^23.5.0:
  version "23.5.0"
  resolved "https://registry.yarnpkg.com/jest-config/-/jest-config-23.5.0.tgz#3770fba03f7507ee15f3b8867c742e48f31a9773"
  dependencies:
    babel-core "^6.0.0"
    babel-jest "^23.4.2"
    chalk "^2.0.1"
    glob "^7.1.1"
    jest-environment-jsdom "^23.4.0"
    jest-environment-node "^23.4.0"
    jest-get-type "^22.1.0"
    jest-jasmine2 "^23.5.0"
    jest-regex-util "^23.3.0"
    jest-resolve "^23.5.0"
    jest-util "^23.4.0"
    jest-validate "^23.5.0"
    micromatch "^2.3.11"
    pretty-format "^23.5.0"
```
Maybe it is used for jest, which depends on babel 6. Should I upgrade jest dep in this issue or create a new one?

**Comment by 634750802** [comment] 2018-08-29 05:53
https://github.com/facebook/jest/tree/master/packages/babel-jest

**Comment by 634750802** [comment] 2018-08-29 08:43
Needs help, It's beyond my ability.

**Comment by vikr01** [comment] 2018-09-08 03:40
`jest` needs `babel-core@7.0.0-bridge.0` to work with `@babel/core@^7.0.0`. I believe the reason is that `jest` still imports babel core as `babel-core`, so the "bridge" is meant to force `@babel/core` to be imported.

**Comment by LinusBorg** [comment] 2018-09-17 11:52
Jest itself is ok, but we need this PR to be merged:

https://github.com/airbnb/babel-plugin-dynamic-import-node/pull/64

As this plugin is still using babel 6

**Comment by ShaneXie** [comment] 2018-10-11 18:53
@LinusBorg seems the v2.2.0 release support both babel 6 and 7 already,  according to this comment https://github.com/airbnb/babel-plugin-dynamic-import-node/pull/64#issuecomment-428011905

**Closed** 2018-10-20 13:29 UTC
Labels: enhancement, feat: babel, intend to implement

**Comment by rgalaxy** [comment] 2018-10-23 03:39
is this fixed? can somebody told me what to do?
currently i have 
`dependencies: { "@babel/core": "^7.1.2", }`
and
`
devDependencies: {
"babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.0.1",
}
`
and a lot more @babel plugin. but now each time i do npm isntall it says `@babel/{plugins} requires a peer of @babel/core@7.0.0-beta.47 but none is installed`.

i am confused, should i downgrade it to `@babel/core 7.0.0-beta.47` ? or can i do something?

**Comment by vikr01** [comment] 2018-10-23 04:13
@rgalaxy You need to upgrade those `babel` plugins.

**Comment by rgalaxy** [comment] 2018-10-23 04:21
@vikr01 hi vikr thanks for the reply, i already try to update babel plugins, but it still show the same, for instance
i upgrade `@babel/preset-env` but it still show the message `@babel/preset-env@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.`

i dont understand, is it because there is a hidden plugin somewhere? and what's weird lot of the dependencies is not even ont package.json devdependencies. is it bcs vue cli 3 isntall it somewhere? even without showing on package.json?

**Comment by sodatea** [comment] 2018-10-23 04:30
@vikr01 It's a dependency of `@vue/cli-plugin-babel`. This is gonna be fixed in the next release.
Maybe the errors are due to the `"@babel/core": "^7.1.2"` in the `package.json` suppressed dependency hoisting so for now you can remove this field to see if it works.

**Comment by rgalaxy** [comment] 2018-10-23 05:01
@sodatea hi sodat, thanks for the reply, when you say  'This is gonna be fixed in the next release', it means i need to update my vue cli version and then reinstall? or will it update all the project inside and able to fix also the problems?

and i tried to remove all the `@babel/` from my package.json, remove package-lock.json and run npm install, and.... guess what is still gaves me the errors..
and i can see this line ` babel-core@7.0.0-bridge.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.`
i am so ultra mega ultimately confused, i tried to create another vue-cli project and it works normally (without all the `@babel/` thing)

**Comment by vikr01** [comment] 2018-10-23 05:02
@rgalaxy Are you able to create a repo that reproduces the issue? Just with all `babel` dependencies you had installed.

**Comment by rgalaxy** [comment] 2018-10-23 07:07
i am not sure, can you suggest me where i can do this?

**Comment by adamdyson** [comment] 2018-10-23 14:10
I'm experiencing the same problem. @vikr01, if you are wanting an example you could use this `package.json`.

```json
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test:e2e": "vue-cli-service test:e2e",
    "test:unit": "vue-cli-service test:unit"
  },
  "dependencies": {
    "register-service-worker": "^1.0.0",
    "vue": "^2.5.17",
    "vue-class-component": "^6.0.0",
    "vue-property-decorator": "^7.0.0",
    "vue-router": "^3.0.1",
    "vuetify": "^1.3.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@cypress/webpack-preprocessor": "^3.0.0",
    "@types/jest": "^23.1.4",
    "@vue/cli-plugin-babel": "^3.0.5",
    "@vue/cli-plugin-e2e-cypress": "^3.0.5",
    "@vue/cli-plugin-eslint": "^3.0.5",
    "@vue/cli-plugin-pwa": "^3.0.5",
    "@vue/cli-plugin-typescript": "^3.0.5",
    "@vue/cli-plugin-unit-jest": "^3.0.5",
    "@vue/cli-service": "^3.0.5",
    "@vue/eslint-config-prettier": "^3.0.5",
    "@vue/eslint-config-typescript": "^3.0.5",
    "@vue/test-utils": "^1.0.0-beta.20",
    "babel-core": "7.0.0-bridge.0",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "ts-jest": "^23.0.0",
    "typescript": "^3.0.0",
    "vue-cli-plugin-vuetify": "^0.4.4",
    "vue-template-compiler": "^2.5.17",
    "vuetify-loader": "^1.0.5"
  }
}
```

**Comment by Number77asa** [comment] 2019-09-23 00:29
Well, in most cases you shouldn't ignore this; the issue arises from babel having so many package versions (babel 6, babel 7; etc.)
Here is a reference: https://nuget.qite.be/feeds/NPM/babel-core/7.0.0-bridge.0
solution for me was: sudo npm install --save-dev babel-core@7.0.0-bridge.0
