### ISSUE TITLE
Could not open vue-demo in the editor

### ISSUE THREAD

**Issue by paritosh149** [vuejs/vue-cli#2070] opened 2018-08-04 15:17 UTC
### Version
3.0.0-rc.10

### Node and OS info
Node 10.8.0

### Steps to reproduce
Go to Vue Project Manager,
Click on Open in Editor icon,
Nothing happens on screen.

### What is expected?
The VSCode editor should launch with ' e:\vue-demo' folder

### What is actually happening?
On Ternimal, two messages are shown
1. Could not Open vue-demo in the editor
2. Unable to open 'e:\vue-demo' null

**Comment by yyx990803** [comment] 2018-08-06 02:04
Duplicate of #2049

**Closed by yyx990803** 2018-08-06 02:04 UTC
