### ISSUE TITLE
SFC based on TS and  vue-property-decorator does not generate d.ts file

### ISSUE THREAD

**Issue by MikeMitterer** [vuejs/vue-cli#4874] opened 2019-11-21 19:33 UTC
### Version
3.5.5

### Reproduction link
[https://github.com/MikeMitterer/vue-cmp-liveforce](https://github.com/MikeMitterer/vue-cmp-liveforce)

### Environment info
```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.16.0
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
    Safari: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.0.5
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.0.5
    @vue/cli-plugin-babel: ^4.0.5 => 4.0.5
    @vue/cli-plugin-router:  4.0.5
    @vue/cli-plugin-typescript: ^4.0.5 => 4.0.5
    @vue/cli-plugin-unit-jest: ^4.0.5 => 4.0.5
    @vue/cli-plugin-vuex:  4.0.5
    @vue/cli-service: ^4.0.5 => 4.0.5
    @vue/cli-shared-utils:  4.0.5
    @vue/component-compiler-utils:  3.0.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: ^1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    jest-serializer-vue:  2.0.2
    typescript: ^3.7.2 => 3.7.2
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.1.0 => 7.1.0
    vue-hot-reload-api:  2.3.4
    vue-jest: ^3.0.5 => 3.0.5
    vue-loader:  15.7.2
    vue-property-decorator: ^8.3.0 => 8.3.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 3.0.0
```

### Steps to reproduce
yarn run build

### What is expected?
Should produce a d.ts file to import the component

### What is actually happening?
Generates a MLiveForce.common.js but nothing TS specific.
The problem is that without a .d.ts file the component can't be imported. WebStorm says "Cannot find module xxx"

**Comment by sodatea** [comment] 2019-11-22 16:22
Duplicate of https://github.com/vuejs/vue-cli/issues/1081

**Closed by sodatea** 2019-11-22 16:22 UTC
