### ISSUE TITLE
vue-cli creating typescript project have error logs

### ISSUE THREAD

**Issue by weixiao-huang** [vuejs/vue-cli#1977] opened 2018-07-29 02:54 UTC
### Version
3.0.0-rc.8

### Node and OS info
node 10.7.0, yarn 1.9.2, MacOS 10.13.6

### Steps to reproduce
I use `vue create test2` to create the test project. Except pwa, I use all options. And detailed options are below:

```
Vue CLI v3.0.0-rc.8
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS, Router, Vuex, CSS Pre-processors, Linter, Unit, E2E
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript for auto-detected polyfills? Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Stylus
? Pick a linter / formatter config: Airbnb
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Jest
? Pick a E2E testing solution: Nightwatch
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? Yes
```

After several minutes, I successfully create the project but get the error logs below

```
error: 'Component' is defined but never used (no-unused-vars) at test2/src/components/HelloWorld.vue:37:10:
  35 |
  36 | <script lang="ts">
> 37 | import { Component, Prop, Vue } from 'vue-property-decorator';
     |          ^
  38 |
  39 | @Component
  40 | export default class HelloWorld extends Vue {


error: 'msg' is not defined (no-undef) at test2/src/components/HelloWorld.vue:41:19:
  39 | @Component
  40 | export default class HelloWorld extends Vue {
> 41 |   @Prop() private msg!: string;
     |                   ^
  42 | }
  43 | </script>
  44 |


error: 'JSX' is not defined (no-undef) at test2/src/shims-tsx.d.ts:4:13:
  2 |
  3 | declare global {
> 4 |   namespace JSX {
    |             ^
  5 |     // tslint:disable no-empty-interface
  6 |     interface Element extends VNode {}
  7 |     // tslint:disable no-empty-interface


error: 'ElementClass' is not defined (no-undef) at test2/src/shims-tsx.d.ts:8:15:
   6 |     interface Element extends VNode {}
   7 |     // tslint:disable no-empty-interface
>  8 |     interface ElementClass extends Vue {}
     |               ^
   9 |     interface IntrinsicElements {
  10 |       [elem: string]: any
  11 |     }


error: 'IntrinsicElements' is not defined (no-undef) at test2/src/shims-tsx.d.ts:9:15:
   7 |     // tslint:disable no-empty-interface
   8 |     interface ElementClass extends Vue {}
>  9 |     interface IntrinsicElements {
     |               ^
  10 |       [elem: string]: any
  11 |     }
  12 |   }


error: 'elem' is not defined (no-undef) at test2/src/shims-tsx.d.ts:10:8:
   8 |     interface ElementClass extends Vue {}
   9 |     interface IntrinsicElements {
> 10 |       [elem: string]: any
     |        ^
  11 |     }
  12 |   }
  13 | }


error: 'Component' is defined but never used (no-unused-vars) at test2/src/views/Home.vue:9:10:
   7 |
   8 | <script lang="ts">
>  9 | import { Component, Vue } from 'vue-property-decorator';
     |          ^
  10 | import HelloWorld from '@/components/HelloWorld.vue'; // @ is an alias to /src
  11 |
  12 | @Component({


error: 'HelloWorld' is defined but never used (no-unused-vars) at test2/src/views/Home.vue:10:8:
   8 | <script lang="ts">
   9 | import { Component, Vue } from 'vue-property-decorator';
> 10 | import HelloWorld from '@/components/HelloWorld.vue'; // @ is an alias to /src
     |        ^
  11 |
  12 | @Component({
  13 |   components: {


error: Use the function form of 'use strict' (strict) at test2/tests/e2e/custom-assertions/elementCount.js:10:21:
   8 | // http://nightwatchjs.org/guide#writing-custom-assertions
   9 |
> 10 | exports.assertion = function elementCount(selector, count) {
     |                     ^
  11 |   this.message = `Testing if element <${selector}> has count: ${count}`;
  12 |   this.expected = count;
  13 |   this.pass = val => val === count;


error: Use the function form of 'use strict' (strict) at test2/tests/e2e/specs/test.js:5:24:
  3 |
  4 | module.exports = {
> 5 |   'default e2e tests': (browser) => {
    |                        ^
  6 |     browser
  7 |       .url(process.env.VUE_DEV_SERVER_URL)
  8 |       .waitForElementVisible('#app', 5000)


10 errors found.
```

### What is expected?
I want to have no error logs

### What is actually happening?
10 errors found. Some errors are described as no-unused-vars. But I did use the definition.

---
The no-unused-vars error makes me confused since I do use them in my typescript vue project.

**Comment by yyx990803** [comment] 2018-07-29 03:13
Duplicate of #1972

**Closed by yyx990803** 2018-07-29 03:13 UTC
