### ISSUE TITLE
Can`t install vue

### ISSUE THREAD

**Issue by ivanromakh** [vuejs/vue-cli#659] opened 2017-11-30 11:00 UTC
coffee-script did n`t installed
PS C:\work\rrs_pilot_new> npm install -g vue-cli
C:\Users\andri\AppData\Roaming\npm\vue-init -> C:\Users\andri\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-init
C:\Users\andri\AppData\Roaming\npm\vue -> C:\Users\andri\AppData\Roaming\npm\node_modules\vue-cli\bin\vue
C:\Users\andri\AppData\Roaming\npm\vue-list -> C:\Users\andri\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-list

> coffee-script@1.12.8 postinstall C:\Users\andri\AppData\Roaming\npm\node_modules\vue-cli\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

[eval]:1
'if
^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)
    at startup (bootstrap_node.js:163:9)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coffee-script@1.12.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andri\AppData\Roaming\npm-cache\_logs\2017-11-30T11_01_12_409Z-debug.log
PS C:\work\rrs_pilot_new> npm install -g coffee-script@1.27.1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for coffee-script@1.27.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andri\AppData\Roaming\npm-cache\_logs\2017-11-30T11_02_03_893Z-debug.log
PS C:\work\rrs_pilot_new> npm install -g coffee-script@1.12.7
C:\Users\andri\AppData\Roaming\npm\coffee -> C:\Users\andri\AppData\Roaming\npm\node_modules\coffee-script\bin\coffee
C:\Users\andri\AppData\Roaming\npm\cake -> C:\Users\andri\AppData\Roaming\npm\node_modules\coffee-script\bin\cake
+ coffee-script@1.12.7
added 1 package in 0.705s
PS C:\work\rrs_pilot_new> npm install -g vue-cli
C:\Users\andri\AppData\Roaming\npm\vue -> C:\Users\andri\AppData\Roaming\npm\node_modules\vue-cli\bin\vue
C:\Users\andri\AppData\Roaming\npm\vue-init -> C:\Users\andri\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-init
C:\Users\andri\AppData\Roaming\npm\vue-list -> C:\Users\andri\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-list

> coffee-script@1.12.8 postinstall C:\Users\andri\AppData\Roaming\npm\node_modules\vue-cli\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

[eval]:1
'if
^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)
    at startup (bootstrap_node.js:163:9)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coffee-script@1.12.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andri\AppData\Roaming\npm-cache\_logs\2017-11-30T11_02_38_919Z-debug.log
PS C:\work\rrs_pilot_new> ^C

**Comment by ivanromakh** [comment] 2017-11-30 11:04
I installed coffee script 1.27.7 but it vue-cli needs 1.28.8 which I can`t install

**Comment by ivanromakh** [comment] 2017-11-30 11:05
PS C:\work\rrs_pilot_new> npm install -g coffee-script@1.12.1
C:\Users\andri\AppData\Roaming\npm\coffee -> C:\Users\andri\AppData\Roaming\npm\node_modules\coffee-script\bin\coffee
C:\Users\andri\AppData\Roaming\npm\cake -> C:\Users\andri\AppData\Roaming\npm\node_modules\coffee-script\bin\cake
+ coffee-script@1.12.1
updated 1 package in 0.538s
PS C:\work\rrs_pilot_new>

**Comment by ivanromakh** [comment] 2017-11-30 11:19
Can I change it here?

**Comment by posva** [comment] 2017-11-30 11:20
Duplicate of #655

**Closed by posva** 2017-11-30 11:20 UTC

**Comment by lihua123569** [comment] 2017-11-30 11:25
Coffeescript has been installed, but there are other problems, as follows
![image](https://user-images.githubusercontent.com/8295524/33428497-0a5b2656-d604-11e7-8845-2c11129fa4d2.png)
