### ISSUE TITLE
vue: command not found in Mac OS

### ISSUE THREAD

**Issue by developerzinan** [vuejs/vue-cli#732] opened 2018-01-22 21:08 UTC
`-bash: vue: command not found` when i wanted to run vue in terminal it always showing that. My npm version is 5.6.0 

How could i solve this issue?

```
/Users/nadeem/.npm-global/bin/vue-init -> /Users/nadeem/.npm-global/lib/node_modules/vue-cli/bin/vue-init
/Users/nadeem/.npm-global/bin/vue -> /Users/nadeem/.npm-global/lib/node_modules/vue-cli/bin/vue
/Users/nadeem/.npm-global/bin/vue-list -> /Users/nadeem/.npm-global/lib/node_modules/vue-cli/bin/vue-list
```

**Comment by posva** [comment] 2018-01-22 21:16
Make sure your global installed packages are included in your PATH. Closing since this is very unlikely to be related with vue-cli

**Closed by posva** 2018-01-22 21:16 UTC

**Comment by nottinhill** [comment] 2018-04-30 11:28
No, it is related to vue. I can reproduce.

`npm i vue -g`
Then:
```
$ vue 
command not found: vue
```

It works for all other npm packages that I install globally, only not for vue. What is the solution to this bug?

**Comment by Akryum** [comment] 2018-04-30 11:29
@nottinhill You are not installing vue-cli so it won't work.

For the old version: `npm i vue-cli -g`
For the new version: `npm i @vue/cli -g`

**Comment by nottinhill** [comment] 2018-04-30 11:32
The older one work as is. Just note, with the latest one I had to

`yarn global add @vue/cli-init` in order to get `vue init` to run.

**Comment by TummenUppGeInteUpp** [comment] 2018-06-13 14:29
Its a nightmare to get vue-cli to run. worth the invested time to get it to work ??? ive installed, uninstalled and installed agin but its not working! MacOs terminal. vue list -bash: vue: command not found

**Comment by Akryum** [comment] 2018-06-13 14:35
@TummenUppGeInteUpp Please open a new issue with more info like did you use yarn or npm? Do you have the path to yarn/npm bin correctly setyp?
