### ISSUE TITLE
@use at-rule of  module system in vue/cli3 error

### ISSUE THREAD

**Issue by GouJieShinee** [vuejs/vue-cli#4686] opened 2019-10-16 03:58 UTC
### Version
3.12.0

### Environment info
```
System:
    OS: macOS High Sierra 10.13.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.6.0 - ~/.config/yarn/global/node_modules/.bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: Not Found
    Safari: 11.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.12.0
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.12.0
    @vue/cli-plugin-babel: ^3.12.0 => 3.12.0
    @vue/cli-plugin-eslint: ^3.12.0 => 3.12.0
    @vue/cli-service: ^3.12.0 => 3.12.0
    @vue/cli-shared-utils:  3.12.0
    @vue/component-compiler-utils:  3.0.0
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.1
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
```

### Steps to reproduce
1. vue create my-project
2. select default config
2. yarn add sass
3. add vue.config.js and code is: `const sass = require('sass'); module.exports = { css: { loaderOptions: { sass: { implementation: sass, }, }, }, };`
4. use @use at-rule in scss file

### What is expected?
@use at-rule can be use success

### What is actually happening?
@use error: Unknown at rule @usescss(unknownAtRules)

---
my vue.config.js code is:
`const sass = require('sass'); module.exports = { css: { loaderOptions: { sass: { implementation: sass, }, }, }, };`

my package.json is:
`"sass": "^1.23.0", "sass-loader": "^8.0.0"`

my var.scss file code is: 
$--color-primary: #2166e7;

my page.scss file code is: 
@use "var"

**Comment by sodatea** [comment] 2019-10-16 04:08
Please provide a runnable reproduction. If I'm not mistaken, the `unknownAtRules` error does not come from any of the dependencies but from vscode, you may need to report to them instead.

**Comment by GouJieShinee** [comment] 2019-10-16 04:27
project in github url: https://github.com/GouJieShinee/sassModuleSystem

**Comment by sodatea** [comment] 2019-10-16 04:37
I'm sorry but I don't see any usage of `@use` in this project.

**Comment by GouJieShinee** [comment] 2019-10-16 04:40
sorry, now you again see it. url: src/components/a.scss   .Thank you!

**Comment by sodatea** [comment] 2019-10-16 04:46
And what I get is 
![image](https://user-images.githubusercontent.com/3277634/66888889-d8ddc180-f012-11e9-9650-a5c049bd992d.png)

Still no `unknownAtRules`

**Comment by sodatea** [comment] 2019-10-16 04:46
![image](https://user-images.githubusercontent.com/3277634/66888903-ed21be80-f012-11e9-91ff-16bfab5e715d.png)

**Comment by sodatea** [comment] 2019-10-16 05:00
Closing this issue because I don't think there's a bug here. At least no bug related to Vue CLI.

**Closed by sodatea** 2019-10-16 05:00 UTC
Labels: needs reproduction

**Comment by andybaacke** [comment] 2020-02-03 19:21
@GouJieShinee, or for anyone else in the furture, see the [sass documentation on private members](https://sass-lang.com/documentation/at-rules/use#private-members). This error looks entirely because `$--color-primary` is prefixed with `-`.

**Comment by pisandelli** [comment] 2020-03-16 20:37
Hi guys, I have the same issue and my variable is called `$font-size`. The same error. I guess it's not related to sass' private members as pointed by @andybaacke.  
When using `@import` in my `vue.config.js` everything goes fine.  
sass: 1.25.0
sass-loader: 8.0.2
![Screenshot from 2020-03-16 17-26-06](https://user-images.githubusercontent.com/1986634/76796972-5026a580-67ab-11ea-8ca6-c0021f8805ad.png)
```javascript
//This code does not work
loaderOptions: {
      sass: {
        prependData: `@use "~abstracts/variables"`
      }
    }
```
```javascript
//This code works
loaderOptions: {
      sass: {
        prependData: `@import "~abstracts/variables"`
      }
    }
```
Any ideas?

Thanks
