### ISSUE TITLE
cmd automatically closed after running `vue init`

### ISSUE THREAD

**Issue by c-cho** [vuejs/vue-cli#274] opened 2016-12-21 08:13 UTC
I installed vue-cli by using yarn(`yarn global add vue-cli`) today. 
It seems that everything went successfully. 
But when I tried to initialize a vue project with command like `vue init webpack test`,
cmd closed itself automatically.
After some research, I found that it occurred because vue.cmd which located in `C:\Users\<MyUserName>\AppData\Local\Yarn\config\global\node_modules\.bin` couldn't be found in this script
`"$basedir/../../Users/<MyUserName>/AppData/Local/Yarn/config/global/node_modules/.bin/vue.cmd"`

Looking to #245 , I think yarn support is already taken into account, but I'm wondering whether it is OK to install vue-cli with yarn in Windows.

OS: Windows 7
yarn: 0.18.1
nodejs: 6.2.0 (x64)
npm: 3.8.9

Thanks in advance.

**Comment by zigomir** [comment] 2016-12-21 18:58
It might not be related at all, but I had many problems with yarn@0.18.1 yesterday. After I re-installed everything with npm things started to work again. Please try it out, it might help, otherwise let us know.

**Comment by c-cho** [comment] 2016-12-22 00:21
@zigomir Yep, I tried npm yesterday and it did work. I'm just very curious to know if it is fine to use yarn to install vue-cli.

**Comment by posva** [comment] 2016-12-22 08:54
@c-cho yes, it's absolutely fine 🙂 
Closing since there's no issue anymore

**Closed by posva** 2016-12-22 08:54 UTC

**Comment by c-cho** [comment] 2016-12-22 09:12
@posva But as shown above, vue-cli installed with yarn (not npm) didn't work for me..

**Comment by posva** [comment] 2016-12-22 09:28
Seems to be an issue with yarn: https://github.com/yarnpkg/yarn/issues/1601

**Comment by c-cho** [comment] 2016-12-22 12:54
@posva Okay, I will keep an eye on it.

**Comment by ibujs** [comment] 2017-01-20 11:27
Just saw this, I can confirm this is fixed with v0.19.1 (possibly v0.19 too).
