### ISSUE TITLE
Cypress counldn't run in a new project

### ISSUE THREAD

**Issue by inventer13** [vuejs/vue-cli#2736] opened 2018-10-15 08:03 UTC
### Version
3.0.5

### Reproduction link
[https://github.com/inventer13/vue-cypress-test](https://github.com/inventer13/vue-cypress-test)

### Node and OS info
node.js 10.5.0 / npm 6.1.0 / Windows 10

### Steps to reproduce
run `npm run test:e2e`
when cypress opened, click `test.js` to run spec

### What is expected?
some test results display in the chrome

### What is actually happening?
there has an error in my powershell, `Entry module not found: Error: Can't resolve 'D:\www\vue\cyp-test\tests\e2e\specs\integration\test.js' in 'D:\www\vue\cyp-test'`

---
I create this project by `vue-ui`, how can I solve this problem?

**Comment by LinusBorg** [comment] 2018-10-15 08:17
This seems to be a duplicate of #2709

**Closed by LinusBorg** 2018-10-15 08:17 UTC
