### ISSUE TITLE
Using the CLI with existing backend projects

### ISSUE THREAD

**Issue by cecilphillip** [vuejs/vue-cli#1359] opened 2018-05-24 00:00 UTC
### What problem does this feature solve?
I work with other backend platforms (python, .NET) that typically have their own folder structure for where things go. Today, creating a new Vue project with the CLI generates src/, public/ and dist/ folders in the project root. I would love to be able to override these folders when generating a new project. 

IMO it would made adopting the vue-cli even easier. I know I could spent the time to override the webpack build settings. It would be much faster for me, and a better on-boarding experience, if I could have the vue project generated using the directories that fit my backend when I call `vue create`

### What does the proposed API look like?
Something like the following command would allow the source and destination folders to be defined.
```
vue create . --destDir wwwroot/js/ --sourcedir frontend/js/
```
When using an existing backend, I probably don't need the public folder and index.html. Maybe there could be an option to exclude that

Something like the following command would allow the source and destination folders to be defined.
```
vue create . --destDir wwwroot/js/ --sourcedir frontend/js/ --no-public
```

**Comment by yyx990803** [comment] 2018-05-24 16:16
I don't think this needs additional options. What you need to do is creating the project inside `frontned/js/` and set `outputDir` in `vue.config.js`. There's no need to mess with webpack at all.

As for optional public dir, that's a duplicate of #1265.

**Closed by yyx990803** 2018-05-24 16:16 UTC
Labels: feat: cli, feature request

**Comment by yyx990803** [comment] 2018-05-24 16:17
However, we do want to include integration guide for popular backend frameworks in the docs. If there are some common, repeated steps among those integrations, we will consider offering convenience options for those.
