### ISSUE TITLE
@vue/cli 3.11.0 => 3.12.0 update Install Issues

### ISSUE THREAD

**Issue by michealjroberts** [vuejs/vue-cli#4674] opened 2019-10-10 13:37 UTC
### Version
3.11.0

### Reproduction link
[https://github.com/vuejs/vue-cli/](https://github.com/vuejs/vue-cli/)

### Environment info
```
 System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.75
    Firefox: 69.0
    Safari: 13.0.2
  npmGlobalPackages:
    @vue/cli: 3.12.0
```

### Steps to reproduce
When @vue/cli 3.11.0 version is installed, simply use $ sudo npm install -g @vue/cli 

### What is expected?
Clean install without errors.

### What is actually happening?
Install seems to bork around fsevents? (See additional comments). Install "seems" ok.

---
/usr/local/bin/vue -> /usr/local/lib/node_modules/@vue/cli/bin/vue.js

> fsevents@1.2.9 install /usr/local/lib/node_modules/@vue/cli/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.9 and node@10.16.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/lib' 
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/Users/michaelroberts/Library/Caches/node-gyp/10.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/@vue/cli/node_modules/fsevents
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/@vue/cli/node_modules/fsevents
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> nodemon@1.19.3 postinstall /usr/local/lib/node_modules/@vue/cli/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@vue/cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

  @vue/cli@3.12.0
added 3 packages from 37 contributors, removed 4 packages and updated 56 packages in 25.808s

**Comment by sodatea** [comment] 2019-10-10 13:50
```
sudo npm install -g @vue/cli --unsafe-perm
```

https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root

This is a design flaw in npm and will be fixed in npm v7.

**Closed by sodatea** 2019-10-10 13:50 UTC

**Comment by Dinuz** [comment] 2019-11-16 04:12
@sodatea I do think the issue is still there, and is not really related with npm, but with fsevents for which they changed a bit the code.

check the related issue that I opened over there and the response that the author gave to me: [](https://github.com/fsevents/fsevents/issues/291)

**Comment by sodatea** [comment] 2019-11-16 04:32
@Dinuz It's not the same error as the one described in the original issue.

This issue is for `EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/lib`, which, is apparently a permission issue.

Yours is a `build error`, caused by the incompatibility between `fsevents` v1 and Node.js v13.
Here fsevents is a transitive dependency: `@vue/cli > @vue/cli-ui > vue-cli-plugin-apollo > nodemon > chokidar > fsevents@1.2.9`.
But I don't know why it could stop you from installing `@vue/cli` because it is an **optional dependency** in `chokidar` so it's allowed to fail.

**Comment by Dinuz** [comment] 2019-11-16 16:10
@sodatea apologize for the confusion. I can install the cli, but the error keeps popping up during runtime...I get my terminal console flooded with errors and warning. If you had the opportunity to check the message from fsevents author, he suggested to update chokidar to version 3.

**Comment by keikoro** [comment] 2019-11-21 00:46
> check the related issue that I opened over there and the response that the author gave to me:
> [https://github.com/fsevents/fsevents/issues/291](url)

@Dinuz, the link you included goes nowhere/redirects back to here. I think you are missing the `url` part.

Fixed:
[https://github.com/fsevents/fsevents/issues/291](https://github.com/fsevents/fsevents/issues/291)

**Comment by Dinuz** [comment] 2019-11-22 00:34
@keikoro you are right...Thank you!

**Comment by Dinuz** [comment] 2019-12-02 20:37
@sodatea who requires fsevents@1.2.9 ?? In order to don't get the error (yes transient) which dependency needs to be update? after looking a bit around I do think vue-cli-plugin-apollo is the culpable (they require a dependency on a nodemon version that doesn't use chokidar 3).

I mean it's pretty ugly keeping getting the error message
