### ISSUE TITLE
Do not update node-icp version

### ISSUE THREAD

**Issue by Actticus** [vuejs/vue-cli#7059] opened 2022-03-17 11:15 UTC
### What problem does this feature solve?
New version of node-icp contains Malware for Russian programmers (checking by ip):

Proofs: https://github.com/RIAEvangelist/peacenotwar/issues

### What does the proposed API look like?
-

**Comment by Akryum** [comment] 2022-03-17 11:20
Duplicate of #7051

**Closed as completed by Akryum** 2022-03-17 11:20 UTC
