### ISSUE TITLE
vue init or any command (on 2.9.4, not 2.9.3) , shows an error message

### ISSUE THREAD

**Issue by akarelas-pt** [vuejs/vue-cli#1417] opened 2018-05-31 07:22 UTC
### Version
2.9.3

### Reproduction link
[https://gist.github.com/akarelas-pt/1d0a4c86952302d585fc7ddeb5db7827](https://gist.github.com/akarelas-pt/1d0a4c86952302d585fc7ddeb5db7827)

### Steps to reproduce
1) npm uninstall -g vue-cli
2) npm i -g vue-cli
3) vue init webpack my-test

### What is expected?
The init command should work without error messages

### What is actually happening?
The init commands doesn't work, and I get the following 2 error messages:

$ vue init webpack my-test

Unknown command init.

vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)

---
The bug-submission form doesn't let my choose v2.9.4 (there's no such option), so I chose 2.9.3 in the selection box.

**Comment by 95y** [comment] 2018-05-31 07:36
I also encountered the same problem, and finally chose the 2.9.3 version :)

**Comment by joannesalfa** [comment] 2018-05-31 07:48
I got the same issue, this is very unforgivable, not cool.

**Comment by Akryum** [comment] 2018-05-31 07:52
Duplicate of #1413

**Closed by Akryum** 2018-05-31 07:52 UTC
