### ISSUE TITLE
can you give me  a way to use the indent of four Spaces when I init my program? 能不能给我们一个初始化项目时用4个空格的方案

### ISSUE THREAD

**Issue by vsionly** [vuejs/vue-cli#3265] opened 2019-01-08 08:10 UTC
### What problem does this feature solve?
I see so many people want to use the indent of four spaces,but you can not to  solve that?
很多人都想在初始化项目时用4 个空格 ，但一直没收到方案，你们不能给解决一下吗I see so many people want to use the indent of four spaces,but you can not to  solve that?
很多人都想在初始化项目时用4 个空格 ，但一直没收到方案，你们不能给解决一下吗

### What does the proposed API look like?
I see so many people want to use the indent of four spaces,but you can not to  solve that?
很多人都想在初始化项目时用4 个空格 ，但一直没收到方案，你们不能给解决一下吗

**Comment by sodatea** [comment] 2019-01-08 09:12
Duplicate of https://github.com/vuejs/vue-cli/issues/2691
Also you can do it with your own custom preset. We just don't prompt this option on creation by default.

**Closed by sodatea** 2019-01-08 09:12 UTC
