### ISSUE TITLE
Cannot Create Project using the UI

### ISSUE THREAD

**Issue by akrome11** [vuejs/vue-cli#1843] opened 2018-07-13 15:33 UTC
### Version
3.0.0-rc.3

### Reproduction link
I am unable to create the project
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
I installed vue cli 3 and ran vue cli. Then i went to create new project and followed the steps. I chose manually select features and included vue-router, vuex, sass, babel, es-lint, unit-jest, e2e-cypress and use config files. I chose eslint   airbnb as my linter/formatter, scss as my preprocessor and hit create project.

### What is expected?
It will then create the project

### What is actually happening?
It fails on create project with code 1. It is unable to resolve path to module @/components/HelloWorld.vue

**Comment by akrome11** [comment] 2018-07-13 15:33
![vuecli3_ _vue___users_akrome_dev_vuecli3_ _node__usr_local_bin_vue_ui_ _117x53_and_genesis-frontend](https://user-images.githubusercontent.com/6146808/42700040-88efa87e-8690-11e8-98d5-d36ab72e0649.png)

**Comment by akrome11** [comment] 2018-07-13 15:33
this is a screenshot of the error im getting

**Comment by Akryum** [comment] 2018-07-13 15:35
Duplicate of #1734

**Closed by Akryum** 2018-07-13 15:35 UTC
