### ISSUE TITLE
Enable Production Source Maps has bug?

### ISSUE THREAD

**Issue by Snile826** [vuejs/vue-cli#4578] opened 2019-09-14 14:30 UTC
### Version
3.8.2

### Reproduction link
[https://github.com/Snile826/stock-stat.git](https://github.com/Snile826/stock-stat.git)

### Environment info
```
 System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.15.0 - D:\Nodejs\node.EXE
    Yarn: Not Found
    npm: 6.10.3 - D:\Nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.329.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.11.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.11.0
    @vue/cli-plugin-babel: ^3.11.0 => 3.11.0
    @vue/cli-plugin-eslint: ^3.11.0 => 3.11.0
    @vue/cli-service: ^3.11.0 => 3.11.0
    @vue/cli-shared-utils:  3.11.0
    @vue/component-compiler-utils:  3.0.0
    @vue/eslint-config-prettier: ^5.0.0 => 5.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)
    vue: ^2.6.10 => 2.6.10
    vue-axios: ^2.1.4 => 2.1.4
    vue-echarts: ^4.0.3 => 4.0.3
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1.  Enable Production Source Maps
2.  npm run build
3. TypeError: Cannot read property 'name' of undefined(compilation.getAsset(css/chunk-vendors.6dc57fe0.css.map) => undefined)

### What is expected?
No errors occur after compilation

### What is actually happening?
TypeError: Cannot read property 'name' of undefined(compilation.getAsset(css/chunk-vendors.6dc57fe0.css.map) => undefined)

**Comment by sodatea** [comment] 2019-09-14 15:41
Duplicate of https://github.com/vuejs/vue-cli/issues/4572
It's the webpack version in your repository (4.40) that has this bug. Please run `npm update` to update it to the latest.

**Closed by sodatea** 2019-09-14 15:41 UTC
