### ISSUE TITLE
Cannot find namespace 'process'.

### ISSUE THREAD

**Issue by andre-dw** [vuejs/vue-cli#1500] opened 2018-06-07 12:48 UTC
### Version
3.0.0-beta.15

### Reproduction link
[https://vuejs.org/](https://vuejs.org/)

### Steps to reproduce
Create a new project based on vue-cli@3.0.0-beta.15 and choose to use TypeScript. Add .env to root of project and set `VUE_APP_BASE_URI=/api`.
Use `process.env.VUE_APP_BASE_URI` in an .ts file.

### What is expected?
No error in linting

### What is actually happening?
Error: Cannot find namespace 'process'.

**Comment by LinusBorg** [comment] 2018-06-07 14:17
From your descrption we understand that you seem to have a linting problem yet you did't mention which linter option you chose.

There may be other things you have missed.

Please follow protocoll and provide a reproduction repository so we don't end up in a back-and-forth about what you *actually* did.

Thanks! :)

**Comment by yyx990803** [comment] 2018-06-07 14:21
Cannot reproduce with either TSLint nor ESLint. Closing until a valid repro is provided.

**Closed by yyx990803** 2018-06-07 14:21 UTC
Labels: need repro
