### ISSUE TITLE
Websocket connection failed, Invalid frame header

### ISSUE THREAD

**Issue by dean5277** [vuejs/vue-cli#1850] opened 2018-07-14 10:56 UTC
### Version
3.0.0-rc.3

### Reproduction link
[http://localhost:8080](http://localhost:8080)

### Steps to reproduce
npm run serve

### What is expected?
no error

### What is actually happening?
when i run dev serve, brower console print socket error.
![image](http://7xjfvt.com1.z0.glb.clouddn.com/q2.png)
![image](http://7xjfvt.com1.z0.glb.clouddn.com/q1.png)

**Comment by LinusBorg** [comment] 2018-07-14 11:04
You seem to be messing with the proxy with this proxyfile? be you don't share it. 

We can't investigate you report without a proper, run able reproduction (as a guy repository) 

Please provide one or we have to close this issue.

**Comment by dean5277** [comment] 2018-07-14 11:14
![image](http://7xjfvt.com1.z0.glb.clouddn.com/q3.png)

proxyFile content.

**Comment by LinusBorg** [comment] 2018-07-14 11:16
That's not a run able reproduction. I won't type the code from your screenshot to run it.

**Closed** 2018-07-14 11:44 UTC
Labels: need repro

**Comment by rayax86** [comment] 2018-07-27 07:07
I am running into this issue too. Basically, when the `/` path exist, HMR websocket requests are not ignored and will be somehow proxied. This can be disabled by adding `ws: false` to the options, however, this will disable all websocket requests.

**Comment by ChrisShen93** [comment] 2018-09-05 01:55
+1

**Comment by dean5277** [comment] 2018-09-05 11:59
proxytable key  'ws' set false.

**Comment by ChrisShen93** [comment] 2018-09-27 06:43
In my case, I use the following configuration to proxy websocket for my site:

```javascript
proxys: {
  '/websocket': {
    target: my_ws_server,
    ws: true,
    changeOrigin: true
  }
}
```

It will cause the same problem like the issue said.

All what I do to resolve is to add a '^' :

```javascript
proxys: {
  '^/websocket': {
    target: my_ws_server,
    ws: true,
    changeOrigin: true
  }
}
```

**Comment by rayax86** [comment] 2018-09-27 06:51
@ChrisShen93 Cool, in which package does the `^` actually took effect?

**Comment by ChrisShen93** [comment] 2018-10-03 13:34
@rayax86 
Sorry for late reply.
That's for the `http-proxy-middleware`.

**Comment by cduyzh** [comment] 2019-03-20 03:54
ws改为false

**Comment by tangdaohai** [comment] 2019-11-29 08:18
Why set it to `ws: false`, it works?

**Comment by gowhari** [comment] 2022-09-22 13:54
running vue-cli itself will run a websocket service on `/ws` route, e.g. `ws://127.0.0.1:8080/ws` to do live reload and other vue-cli internal services.

if you use same route for your app and try to proxy it, there will be a conflict. you can simply try to use another route to avoid this conflict. I couldn't fix it with `^/ws` or `ws: true/false`, but rename the route to something else simply solved the issue.

    '/websock': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
        ws: true,
    },

**Comment by Lucas-lgm** [comment] 2023-01-19 13:21
The reason is that the `path` of `webSocketServer` conflicts with the `path` of proxy in the project. It can be solved by modifying the `path` of `webSocketServer`.

```js
  devServer: {
    webSocketServer: {
      options: {
        path: "/yourCustomPath"
      }
    }
  }
```

**Comment by LiMeii** [comment] 2023-01-20 16:06
In my case , I am using ```http-proxy-middleware```,  I updated the proxy configuration from:
```js
    app.use(
        '/hubs',
        createProxyMiddleware({
            target: 'your target url',
            changeOrigin: true,
            ws: true
        })
    );
```
to
```js
   app.use(
        createProxyMiddleware('/hubs', {
            target: 'your target url',
            changeOrigin: true,
            ws: true
        })
    );
```
Then the issue is fixed.

**Comment by gowhari** [comment] 2023-05-02 18:17
based on @liangguangming solution but for the people that are still using webpack 4.x :-)

```js
devServer: {
    sockPath: '/webpack-dev',
}
```
https://v4.webpack.js.org/configuration/dev-server/#devserversockpath
