### ISSUE TITLE
typescript building error when import .vue file with separate .ts file

### ISSUE THREAD

**Issue by troy351** [vuejs/vue-cli#1104] opened 2018-04-10 06:48 UTC
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/troy351/vue-cli-demo](https://github.com/troy351/vue-cli-demo)

### Steps to reproduce
clone the repo, run
```
npm install
npm run serve
```

### What is expected?
run success

### What is actually happening?
error `File '/src/components/HelloWorld.vue' is not a module.`
in `App.vue`

---
use inline script (not put script into a separate file) works fine

**Comment by posva** [comment] 2018-04-10 10:04
https://github.com/vuejs/vue/issues/5298#issuecomment-289641843

> This is because you don't have declarations of `.vue` files, then the typescript compiler cannot load them. You need to declare [general declaration of `.vue` file](https://github.com/vuejs/vue-class-component/blob/master/example/sfc.d.ts) in your project or generating each `.vue` file declaration by using [vuetype](https://github.com/ktsn/vuetype)

**Comment by posva** [comment] 2018-04-10 11:00
Maybe @ktsn knows how to make `<script src="Component.ts"/>` work

**Comment by ktsn** [comment] 2018-04-10 13:57
This looks like `fork-ts-checker-webpack-plugin` issue.
I already opened an issue: https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/111

**Comment by UnnoTed** [comment] 2018-05-15 13:35
I had the same issue some time ago, but i got it to work by removing the `.vue` extension.

**Comment by UnnoTed** [comment] 2018-05-15 19:36
@shenron 100% sure https://www.youtube.com/watch?v=k7UkuPzh22o

**Comment by shenron** [comment] 2018-05-16 08:27
Thank you for your answer, so I guess I have a bad config.

I've a fresh new project generated by vue-cli@3, I just split a module in three files (ts, html, vue). I still have a problem during the serve/build. I tried to remove `.vue`, same trouble.

So I don't know if it's link to a vue-cli config or not, I'm sorry if it's not the good place to ask help.

I've created a repo to reproduce:

https://github.com/shenron/vue-cli-ts-seed

` DONE  Compiled successfully in 4327ms                                                                                                                                                                                                                04:14:26

ERROR in /home/node/app/src/views/Home.vue
10:24 File '/home/node/app/src/components/HelloWorld/HelloWorld.vue' is not a module.
     8 | <script lang="ts">
     9 | import { Component, Vue } from 'vue-property-decorator';
  > 10 | import HelloWorld from '@/components/HelloWorld/HelloWorld.vue'; // @ is an alias to /src
       |                        ^
    11 | 
    12 | @Component({
    13 |   components: {
ERROR in /home/node/app/tests/unit/HelloWorld.spec.ts
2:24 File '/home/node/app/src/components/HelloWorld/HelloWorld.vue' is not a module.
    1 | import { shallowMount } from '@vue/test-utils';
  > 2 | import HelloWorld from '@/components/HelloWorld/HelloWorld.vue';
      |                        ^
    3 | 
    4 | describe('HelloWorld.vue', () => {
    5 |   it('renders props.msg when passed', () => {
Version: typescript 2.8.3
Time: 4092ms
`

**Comment by troy351** [comment] 2018-05-16 08:36
@shenron add `// @ts-ignore` before each `import '*.vue'` could be a temporary solution.
```typescript
// @ts-ignore
import HelloWorld from '@/components/HelloWorld/HelloWorld.vue'; 
```

**Comment by shenron** [comment] 2018-05-16 08:43
@troy351 

Yes ! it works thank you very much.

**Comment by bc3** [comment] 2018-06-19 18:14
indeed had a sort-a-like issue, now it works :-D thanks

**Comment by LinusBorg** [comment] 2018-07-05 11:31
A Workaround is described here:

https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/111#issuecomment-401519194

**Comment by banxi1988** [comment] 2018-07-14 14:19
@LinusBorg I'd agree with your idea, vue-cli should disable the plugin currently.
I've waste some time in my new project to handle this error. actually, I had waste some time in another project some days ago. well, I just forgot I had to config it with vue.config.js because A strong idea is always in my mind.I dont' need to configure it too much with vue cli 3.0. now,I think I'm wrong.

**Comment by troy351** [comment] 2018-07-17 09:37
seems that hot module replacement becomes abnormal after using the workaround provided by @LinusBorg

**Comment by LinusBorg** [comment] 2018-07-17 09:49
What does "abnormal" mean, exactly? 

Can you provide a repository with a minimum reproduction?

**Comment by troy351** [comment] 2018-07-17 10:18
I mean component will lost its status after patch
demo [here](https://github.com/troy351/vue-cli-demo)

click button will increase count, but if adding some static text then count will be reset to 0 and this should not happend.

**Comment by LinusBorg** [comment] 2018-07-17 10:31
Thanks, we will have a look. 

@ktsn we should check this bout before we decide to deactivate the ts-checker plugin

**Comment by ktsn** [comment] 2018-07-25 05:37
I ended up to make a PR to fork-ts-checker-webpack-plugin https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/130

**Comment by yyx990803** [comment] 2018-07-26 22:03
@ktsn's PR has been merged, pending release in https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/132

**Comment by johnnyreilly** [comment] 2018-07-31 05:49
We're currently waiting on @piotr-oles to generate a new token so we can release. (A result of the eslint token problem the other week.)

In the meantime I could publish this to our unofficial fork-ts-checker-webpack-plugin@next channel:

https://github.com/TypeStrong/fork-ts-checker-webpack-plugin

Let me know if that would help and I'll make it happen.

**Closed** 2018-08-06 03:29 UTC
Labels: feat: typescript, upstream

**Comment by beetaa** [comment] 2019-01-11 02:07
@yyx990803 @troy351  In my case , when I try to import some `vue` files into the `jest` files written in `ts` format, **vs code** hint that I got an error in forms `[ts]  cannot find module... 2307`. I think that it must be a problem for vs code to resolve the module path, so I include all the paths that typescript should treat that files,  in `tsconfig.json`, just like this:

```js
{
  "include": [
    "src/**/*.ts",
    "src/**/*.vue",
    "test/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "files": [
    "ts-custom.d.ts"
  ],
  "types": [
    "jest"
  ],
  "compilerOptions": {
    "outDir": "./dist/",
    "target": "es5",
    "module": "esnext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "strict": true,
    "noImplicitReturns": true,
    "allowJs": false,
    "sourceMap": true,
    "pretty": true,
    "removeComments": true
  }
}
```

and finally, vs code feel so happy. :laugh:

**Comment by FlamesoFF** [comment] 2019-05-03 12:19
@troy351 
```ts
declare module '*.vue' {
  import Vue from 'vue'
  export default Vue
}
```
It's not working.

![image](https://user-images.githubusercontent.com/5371279/57136887-74091480-6dae-11e9-949c-8b5117d5aae3.png)

**Comment by troy351** [comment] 2019-05-03 13:00
This should not happened since the bug was already fixed in the latest version.




------------------ Original ------------------

**Comment by FlamesoFF** [comment] 2019-05-03 16:36
@troy351 Um... all versions are latest.

**Comment by troy351** [comment] 2019-05-05 01:11
@FlamesoFF Could you create a new **empty** project with the lateset vue-cli and check if that works?

**Comment by FlamesoFF** [comment] 2019-05-05 10:07
@troy351 I don't use vue-cli, because I want to have full control over my project (webpack configurations and other stuff).

**Comment by troy351** [comment] 2019-05-05 10:35
That make things complicated. I suggest you to use vue-cli to create an empty project with all you needed plugins then use `vue inspect` to output its webpack config and compare yours.

More about the command https://cli.vuejs.org/guide/webpack.html#inspecting-the-project-s-webpack-config
