### ISSUE TITLE
Lint Error

### ISSUE THREAD

**Issue by M6stafa** [vuejs/vue-cli#1976] opened 2018-07-28 19:04 UTC
### Version
3.0.0-rc.8

### Node and OS info
node 8.11.3 / npm 6.2.0 / typescript 2.9.2 / Windows 10

### Steps to reproduce
repo created with @vue/cli@3.0.0-rc.8 and untoched: [repo](https://github.com/M6stafa/test-new-vue-cli)
`npm i`
`npm run lint`

### What is expected?
Linting pass with no error!

### What is actually happening?
Several errors:
![image](https://user-images.githubusercontent.com/7975309/43359807-7f2cfdca-92be-11e8-8625-1225822fb282.png)
![image](https://user-images.githubusercontent.com/7975309/43359810-909646e8-92be-11e8-90f4-5b895ecc3a99.png)
![image](https://user-images.githubusercontent.com/7975309/43359813-a064213a-92be-11e8-912e-fbe33d38ddce.png)

**Comment by sodatea** [comment] 2018-07-28 19:11
Duplicate of #1972

**Closed by sodatea** 2018-07-28 19:11 UTC
