### ISSUE TITLE
cli-plugin-typescript: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by justinkames** [vuejs/vue-cli#2019] opened 2018-08-01 07:51 UTC
### Version
@vue/cli-plugin-typescript@3.0.0-rc.10
@vue/cli-service@3.0.0-rc.10

### Node and OS info
node v9.30, npm 6.2.0, macosx high sierra

### Steps to reproduce
I initially had a vue-cli project 3.0 with default settings ( babel ). I added typescript support with this command : vue add @vue/typescript. It converted all my .js files to .ts files. This worked as expected. However when running or vue-cli-service build i get an error: RangeError: Maximum call stack size exceeded. I'm not able to build the project, it is stuck. vue-cli-service serve does work properly. How can I debug this?

### What is expected?
For vue-cli-service build to work properly.

### What is actually happening?
``` 
> vue-cli-service build


⠙  Building for production...Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
⠧  Building for production.../Users/user/Documents/app/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:22
        throw error;
        ^

RangeError: Maximum call stack size exceeded
    at compareComparableValues (/Users/user/Documents/app/node_modules/typescript/lib/typescript.js:1482:37)
    at compareValues (/Users/user/Documents/app/node_modules/typescript/lib/typescript.js:1494:16)
    at Object.binarySearch (/Users/user/Documents/app/node_modules/typescript/lib/typescript.js:1030:21)
    at addTypeToUnion (/Users/user/Documents/app/node_modules/typescript/lib/typescript.js:37021:82)
    at addTypesToUnion (/Users/user/Documents/app/node_modules/typescript/lib/typescript.js:37037:28)
    at getUnionType (/Users/user/Documents/app/node_modules/typescript/lib/typescript.js:37117:28)
    at getArrayLiteralType (/Users/user/Documents/app/node_modules/typescript/lib/typescript.js:44356:17)
    at checkArrayLiteral (/Users/user/Documents/app/node_modules/typescript/lib/typescript.js:44351:20)
    at checkExpressionWorker (/Users/user/Documents/app/node_modules/typescript/lib/typescript.js:49158:28)
    at checkExpression (/Users/user/Documents/app/node_modules/typescript/lib/typescript.js:49108:42)
⠼  Building for production...

```

---

**Comment by justinkames** [comment] 2018-08-01 12:16
Running `node --max_old_space_size=4096 node_modules/.bin/vue-cli-service build`

Does not change the issue.

**Comment by LinusBorg** [comment] 2018-08-01 14:41
We can't say anything about this without a reproduction of the problem.

If you can't reduce the problem to a small reproduction, it's likely specific to the typescript code that you created, and the fork-ts-checker plugin which does the typeschecking

**Comment by yyx990803** [comment] 2018-08-03 19:21
Closing due to lack of reproduction.

**Closed by yyx990803** 2018-08-03 19:21 UTC
Labels: needs reproduction

**Comment by proshuai** [comment] 2018-12-11 01:57
now i also meet this question. 
example : [https://github.com/proshuai/test-vue-cli3]
`Using 1 worker with 2048MB memory limit
 36% building 224/228 modules 4 active ...s/core-js/modules/_to-absolute-index.js/Users/work/zyb-cws/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:22
        throw error;
        ^

RangeError: Maximum call stack size exceeded`

**Comment by TeamDman** [comment] 2019-12-23 20:32
I believe it was fixed [here](https://github.com/Microsoft/TypeScript/issues/28785)
Updating typescript fixed it for me.
