### ISSUE TITLE
vue.config.js 不生效

### ISSUE THREAD

**Issue by ChesterBu** [vuejs/vue-cli#5481] opened 2020-05-14 14:02 UTC
### Version
4.3.1

### Reproduction link
[https://github.com/ChesterBu/vue-cli-bug](https://github.com/ChesterBu/vue-cli-bug)

### Environment info
```
node v12.9
```

### Steps to reproduce
npm i
npm run serve

### What is expected?
vue.config.js中随意引用了一个错误的文件，应该报错

### What is actually happening?
没有执行vue.config.js的配置而执行了默认配置，也没报错

---
看了下源码是因为错误类型是MODULE_NOT_FOUND，没有抛出

**Comment by sodatea** [comment] 2020-05-14 14:16
Duplicate of https://github.com/vuejs/vue-cli/issues/5442

**Closed by sodatea** 2020-05-14 14:16 UTC
