### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by 80073955** [vuejs/vue-cli#6168] opened 2020-12-24 06:35 UTC
### Version
5.0.0-alpha.0

### Environment info
```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\node_global\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.102
    Edge: Spartan (44.18362.449.0)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1.cmd :   vue  ui;
2.创建项目：Failed to load resource: the server responded with a status of 404 ()  https://unpkg.com/vue-cli-locales@4.5.9/locales/zh_CN.json

### What is expected?
no  error  in  chrome dug view

### What is actually happening?
error

**Comment by sodatea** [comment] 2020-12-24 06:50
Duplicate of https://github.com/vuejs/vue-cli/issues/6028

**Closed by sodatea** 2020-12-24 06:50 UTC
