### ISSUE TITLE
library built with UI doesn't recognize enviroment variables

### ISSUE THREAD

**Issue by katerlouis** [vuejs/vue-cli#3796] opened 2019-04-12 10:55 UTC
### Version
3.5.5

### Reproduction link
[https://github.com/katerlouis/vue-cli-ui-enviroment-bug](https://github.com/katerlouis/vue-cli-ui-enviroment-bug)

### Environment info
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    Yarn: Not Found
    npm: 6.9.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.1
    Safari: 11.1.2
  npmGlobalPackages:
    @vue/cli: 3.5.5
```

### Steps to reproduce
* `>npm i`
* `>vue ui`
* go to tasks
* click `build:lib` button in the UI
* open the resulting `demo.html`
* see the wrong message

### What is expected?
Expected message from <HelloWorld /> component is
"Nice! Environment variable worked!" 
_(see `App.vue` line 19)_

### What is actually happening?
The `.env.prodlib` file is ignored when building with the UI – 

---
When you build the library with terminal:
`npm run build:lib` the `.env.prodlib` file is being recognized and the correct message is displayed

**Comment by Akryum** [comment] 2019-04-12 12:05
Is `Mode` set to `(unset)` in the task parameters?

**Comment by katerlouis** [comment] 2019-04-12 13:09
Unfortunately I still can't disable automatic translation, so I don't know what exactly you mean by `Mode` – but the screenshots show my settings:

![image](https://user-images.githubusercontent.com/1983382/56039589-e1d49a00-5d34-11e9-84af-26c61bd1f291.png)

Changing the "Modern mode" setting doesn't solve the issue, though.

**Comment by katerlouis** [comment] 2019-04-12 13:14
No, it wasn't. I had `production` selected.
When I built with `(unset)` selected, the environment variable works.

I find that quite unintuitive. Would it be possible to grey out / hide this dropdown altogether, when the command in `package.json` already sets a mode via `--mode prodlib`?

Would you agree that this is worth mentioning in the docs?

**Comment by Akryum** [comment] 2019-04-13 18:57
Duplicate of #3236

**Closed by Akryum** 2019-04-13 18:57 UTC
Labels: feat: ui
