### ISSUE TITLE
jest don't work

### ISSUE THREAD

**Issue by KAROTT7** [vuejs/vue-cli#2834] opened 2018-10-29 09:06 UTC
### Version
3.0.1

### Node and OS info
Node-v10.11.0/OS-window 7

### Steps to reproduce
```
vue create jest-demo
npm install --save-dev jest @vue/test-utils
npm install --save-dev vue-jest
npm install --save-dev babel-jest
```

jest.config.js
```
module.exports = {
  moduleFileExtensions: ['js', 'json', 'vue'],
  transform: {
    '. \\.(vue)$': '<rootDir>/node_modules/vue-jest',
    '^. \\.js$': '<rootDir>/node_modules/babel-jest'
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1'
  },
  transformIgnorePatterns: ['<rootDir>/node_modules/']
}
```
my.test.js
```
import { mount } from '@vue/test-utils'
import Component from '@/components/HelloWorld'

describe('Component', () => {
  test('是一个 Vue 实例', () => {
    const wrapper = mount(Component)
    expect(wrapper.isVueInstance()).toBeTruthy()
  })
})
```

### What is expected?
It should print ''是一个 Vue 实例“

### What is actually happening?
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { mount } from '@vue/test-utils';

   ^

    SyntaxError: Unexpected token {

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)

---
plz tell me how to do  
thank you

**Comment by LinusBorg** [comment] 2018-10-29 09:34
Please provide an actual reproduction 

You don't show what options you chose for `vue create`. 

You also install dependencies that you don't have to install because the come with the jest option - if you chose them. 

You also don't show how you run your tests. 

So please, provide an actual repository with a reproduction.

**Comment by KAROTT7** [comment] 2018-10-30 01:34
So sorry for late.
I chose default option for ```vue create```
I am a noob to jest.
this is reproduction https://github.com/KAROTT7/vue-jest-demo

**Comment by KAROTT7** [comment] 2018-10-30 02:39
after look https://github.com/vuejs/vue-cli/issues/1879#issuecomment-409872897
it works.

**Comment by LinusBorg** [comment] 2018-10-31 18:49
closing in favour of #1879

**Closed by LinusBorg** 2018-10-31 18:49 UTC
Labels: feat: unit-jest, needs reproduction
