### ISSUE TITLE
npm error：“ Cannot find module 'core-js/modules/es7.object.entries'”

### ISSUE THREAD

**Issue by SilverLeaves** [vuejs/vue-cli#2221] opened 2018-08-15 02:44 UTC
### Version
3.0.0

### Node and OS info
Node 10.80, npm 6.2, windows10

### Steps to reproduce
``` bash
npm  i -g @vue/cli
vue ui

internal/modules/cjs/loader.js:583
Error: Cannot find module 'core-js/modules/es7.object.entries'
```
### temp solutoin:
``` bash
npm i core-js -g
```
and then, it works!

``` bash
vue ui

🚀  Starting GUI...

🌠  Ready on http://localhost:8000
```

### What is expected?
🚀  Starting GUI...

🌠  Ready on http://localhost:8000

### What is actually happening?
internal/modules/cjs/loader.js:583

    throw err;
    ^

Error: Cannot find module 'core-js/modules/es7.object.entries'

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)

    at Function.Module._load (internal/modules/cjs/loader.js:507:25)

    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

    at Object.<anonymous> (C:\Users\leaff\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\_apollo-upload-server@5.0.0@apollo-upload-server\lib\middleware.js:14:1)

    at Module._compile (internal/modules/cjs/loader.js:689:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

    at Module.load (internal/modules/cjs/loader.js:599:32)

    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

---
#### temp solutoin:
``` bash
npm i core-js -g
```
and then, it works!

**Comment by themaxaboy** [comment] 2018-08-15 05:39
go to global directory npm or yarn

ex : ~/AppData/Local/Yarn/Data/global

yarn add core-js
npm i core-js --save

**Comment by minhchu** [comment] 2018-08-15 05:44
same problem here:
Ubuntu 16.04
Node 8.11.2

**Comment by SilverLeaves** [comment] 2018-08-15 06:10
@sigpoggy my pleasure， 新人的微笑๑乛◡乛๑

**Comment by yinxin630** [comment] 2018-08-15 08:14
+1

**Comment by Chas2016** [comment] 2018-08-15 08:37
### Version
3.0.0
`yarn global add @vue/cli`
`vue ui
Error: Cannot find module 'core-js/modules/es7.object.entries'`
### temp solutoin:
`yarn global remove @vue/cli
npm i -g @vue/cli`

**Comment by Kocal** [comment] 2018-08-15 08:39
I think this is a duplicate of #2215

**Comment by sodatea** [comment] 2018-08-15 09:07
Closed in favor of #2215

**Closed by sodatea** 2018-08-15 09:07 UTC

**Comment by specter322** [comment] 2018-12-29 13:48
This work for me npm install webpack-cli

**Comment by arunap2509** [comment] 2019-02-02 07:39
I was having the same error too, got it after updating all outdated dependencies
fixed using              npm i core-js --save

**Comment by timerainbow** [comment] 2019-03-27 07:58
thanks!
