### ISSUE TITLE
ERROR  Error: Failed to resolve plugin: @vue/cli-service

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [vuejs/vue-cli#1604] opened 2018-06-17 23:58 UTC
### Version
3.0.0-rc.2

### Reproduction link
[https://uhh.should.i.put.an.ascinemma.here](https://uhh.should.i.put.an.ascinemma.here)

### Steps to reproduce
1. Run ``vue create project-name``
2. Choose default settings
3. Error!

### What is expected?
For project to successfully create

### What is actually happening?
ERROR  Error: Failed to resolve plugin: @vue/cli-service

**Comment by ThatNerdyPikachu** [comment] 2018-06-18 12:52
Latest, 10.4.1 I think?

**Comment by sqal** [comment] 2018-06-18 13:02
vue-cli 3.0.0-rc.2
node 10.4.1
Windows 10

Installation went flawless :)

**Comment by yyx990803** [comment] 2018-06-18 13:44
This error should only happen on an older version of Vue CLI on a specific version range of Node, so we will need accurate info on your exact Node and Vue CLI verisons.

**Comment by ThatNerdyPikachu** [comment] 2018-06-18 15:05
@yyx990803 Latest Vue CLI, and latest Node
Windows 10 too if that means something

**Comment by yyx990803** [comment] 2018-06-19 13:41
There's nothing we can do at the moment because we can't reproduce the issue based on the information you provided.

**Comment by openks** [comment] 2018-06-22 08:04
![image](https://user-images.githubusercontent.com/4387721/41765146-cd4bd418-7635-11e8-9983-d6467f3208df.png)

**Comment by vikas-rathee** [comment] 2018-07-05 07:10
Same Issue:
Node : v8.11.3
Vue/CLI : 3.0.0-rc.3
Windows 10 : 10.0.17134

**Comment by cdelguercio** [comment] 2018-07-12 00:41
same here:
Vue CLI: 3.0.0-rc.3
Node: v10.6.0
OS: Ubuntu 18.04

**Comment by yyx990803** [comment] 2018-07-18 03:01
@openks I noticed although you said you upgraded npm, the installation is actually performed using Yarn. Have you tried:

1. Upgrade Yarn to the latest
2. OR: set package manager to `npm` in `~/.vuerc`

Question to everyone in this thread: do you have `yarn` installed on your system, and what is the version?

**Comment by JnusK** [comment] 2018-07-19 14:58
Same here:
@vue/cli: 3.0.0-rc.5
 Node: v8.11.3
npm: 6.2.0
OS: Windows 10
No Yarn installed

**Comment by sodatea** [comment] 2018-09-12 05:45
I'm closing this issue since it's been months since the last active comment and we cannot reproduce this issue on our local environments.

Please open a new issue with a reference to this one if you can follow up with more information.

**Closed by sodatea** 2018-09-12 05:45 UTC
Labels: cannot reproduce

**Comment by openks** [comment] 2018-09-13 07:10
> @openks I noticed although you said you upgraded npm, the installation is actually performed using Yarn. Have you tried:
> 
> 1. Upgrade Yarn to the latest
> 2. OR: set package manager to `npm` in `~/.vuerc`
> 
> Question to everyone in this thread: do you have `yarn` installed on your system, and what is the version?

I am sorry to see it after such a long time.

In my case, there is something wrong with yarn ,2 yarn installed 
1.  install by  `brew install yarn`
2.  install by `npm install yarn`    this yarn works

 **after delete the yarn folder in  whole situation node_modules , it works**
I found this by update yarn  using`brew upgrade yarn` the version doesn't match
