### ISSUE TITLE
Cannot control configurations on vue-ui ( windows 10 )

### ISSUE THREAD

**Issue by sk0x0y** [vuejs/vue-cli#2553] opened 2018-09-19 06:34 UTC
### Version
3.0.3

### Node and OS info
Node 8.12.0 / npm 6.4.1 / Windows 10 1803 x64

### Steps to reproduce
1. My issue occur after update 3.0.1 to 3.0.3
2. after update 3.0.0-rc4 to 3.0.3
* . or.. after update windows 10 new rs? ( just my idea )

2 cases

### What is expected?
well.. really i dont know..

### What is actually happening?
same as title.
suddenly(maybe), cannot modify configurations on vue-ui

---
umm.. i checked about my issues use to devtools,
occur events when click.
but, not working VueSwitch ( no change payload, still false )
i dont know why it cannot modify configurations on vue-ui
summary : 1. not working on vue-ui, 2. working well on webstorm ex) eslintrc

thank you

**Comment by sodatea** [comment] 2018-09-19 07:14
Duplicate of #2522 
Will release a new patch soon.

**Closed by sodatea** 2018-09-19 07:14 UTC
