### ISSUE TITLE
Stuck building when add more then 5 pages in a multi-page webapp

### ISSUE THREAD

**Issue by murilobd** [vuejs/vue-cli#2306] opened 2018-08-21 14:42 UTC
### Version
3.0.0

### Node and OS info
Node v8.11.3, NPM 6.1.0, Fedora Workstation 28

### Steps to reproduce
Create a vue-cli project and add 6 pages (using the https://cli.vuejs.org/config/#pages configuration). It will stuck on 11% when building. Serving works fine.

### What is expected?
To build the project

### What is actually happening?
Stuck on 11%

**Comment by Akryum** [comment] 2018-08-21 14:48
Duplicate of #1996

**Closed by Akryum** 2018-08-21 14:48 UTC
