### ISSUE TITLE
Upgrade cypress to support TypeScript

### ISSUE THREAD

**Issue by upcccz** [vuejs/vue-cli#5595] opened 2020-06-19 02:29 UTC
### What problem does this feature solve?
Cypress 4.4.0 already supports ts, but the version 3.8.3 referenced by @vue-cli-plugin-e2e-cypress does not.

### What does the proposed API look like?
 No API changes, only  @Vue-cli-plugin-e2e-cypress upgrade cypress to support TS

**Comment by sodatea** [comment] 2020-06-19 02:42
Duplicate of https://github.com/vuejs/vue-cli/issues/5177 https://github.com/vuejs/vue-cli/issues/5352

**Closed by sodatea** 2020-06-19 02:42 UTC
