### ISSUE TITLE
[Typescript] Curious warnings about missing interface exports

### ISSUE THREAD

**Issue by DorianGrey** [vuejs/vue-cli#2125] opened 2018-08-09 08:57 UTC
### Version
3.0.0-rc.12

### Node and OS info
Node 8.11.3 / yarn 1.9.2 / Ubuntu 18.04 & 16.04 (CI)

### Steps to reproduce
- Checkout https://github.com/DorianGrey/vue-ts-playground.git
- yarn
- yarn build (uses the `--modern` flag by default)

Note that the issue seems to occur somewhat randomly, but very often during the legacy build when using the `--modern` flag.

### What is expected?
The build should only yield two warnings about bundle and resource sizes.

### What is actually happening?
In some cases, additional warnings are emitted about missing exported interfaces, even though they are present. Additionally, every warning occurs twice.
The `typescript` would yield an error for this, so it does not seem to be caused by it or `ts-loader`.

---
I've recognized this on a recent CI build: 
- https://travis-ci.org/DorianGrey/vue-ts-playground/builds/413952547#L598
```
 warning  in ./src/views/todoList/todoEntry.ts?vue&type=script&lang=ts&
"export 'TodoModel' was not found in './state/interfaces'
```
- https://travis-ci.org/DorianGrey/vue-ts-playground/builds/413952547#L602
```
 warning  in ./src/views/todoList/todoEntry.ts?vue&type=script&lang=ts&
"export 'TodoModel' was not found in './state/interfaces'
```

The issue did not occur (at least yet) in development mode. It doesn't break anything, though, yet it is quite confusing.

**Comment by yyx990803** [comment] 2018-08-09 15:55
Duplicate of https://github.com/vuejs/vue-cli/issues/1708

**Closed by yyx990803** 2018-08-09 15:55 UTC

**Comment by DorianGrey** [comment] 2018-08-10 06:33
Oh... thanks for the hint, didn't find the other issue before.
