### ISSUE TITLE
vue.config.js设置问题

### ISSUE THREAD

**Issue by clark-cui** [vuejs/vue-cli#5248] opened 2020-03-06 13:59 UTC
### Version
4.2.3

### Reproduction link
[https://github.com/clark-cui/vue3-template.git](https://github.com/clark-cui/vue3-template.git)

### Environment info
```
  System:
    OS: Windows 10 10.0.18362
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 11.10.0 - C:\softwares\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.7.0 - C:\softwares\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.2.3
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.2.3
    @vue/cli-plugin-babel: ~4.2.0 => 4.2.3
    @vue/cli-plugin-router: ~4.2.0 => 4.2.3
    @vue/cli-plugin-typescript: ~4.2.0 => 4.2.3
    @vue/cli-plugin-vuex: ~4.2.0 => 4.2.3
    @vue/cli-service: ~4.2.0 => 4.2.3
    @vue/cli-shared-utils:  4.2.3
    @vue/component-compiler-utils:  3.1.1
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    typescript: ~3.7.5 => 3.7.5
    vue: ^2.6.11 => 2.6.11
    vue-class-component: ^7.2.2 => 7.2.3
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.0
    vue-property-decorator: ^8.3.0 => 8.4.0
    vue-router: ^3.1.5 => 3.1.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.2 => 3.1.2
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
Docs write:
> > vue.config.js is an optional config file that will be automatically loaded by @vue/cli-service if it's present in your project root (next to package.json). 

But vuecli can't load vue.config.ts,the option in this typescript file is useless.change the file from typescript to javascript can solve this problem.

### What is expected?
vuecli can load vue.config.ts.(typescript file)

### What is actually happening?
vuecli just can load vue.config.js(javacript file)

---
none

**Comment by sodatea** [comment] 2020-03-08 05:08
Duplicate of https://github.com/vuejs/vue-cli/issues/2138

**Closed by sodatea** 2020-03-08 05:08 UTC
