### ISSUE TITLE
yarn serve ：Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by xiaomizhou66** [vuejs/vue-cli#3200] opened 2018-12-27 07:51 UTC
### Version
3.2.1

### Environment info
```
win7
```

### Steps to reproduce
yarn serve

### What is expected?
yarn serve

### What is actually happening?
error

```BASH
### Version
3.2.1







### Environment info
```
win7
```


### Steps to reproduce
yarn serve

### What is expected?
yarn serve

### What is actually happening?
error

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by xiaomizhou66** [comment] 2018-12-27 07:51
```BASH
### Version
3.2.1







### Environment info
```
win7
```


### Steps to reproduce
yarn serve

### What is expected?
yarn serve

### What is actually happening?
error

<!-- generated by vue-issues. DO NOT REMOVE -->
```

**Comment by sodatea** [comment] 2018-12-27 07:55
I guess it's a duplicate of https://github.com/vuejs/vue-cli/issues/2938#issuecomment-437896185

Next time **please provide a reproduction repo**. Without actual runnable code we can't help you much.

**Closed by sodatea** 2018-12-27 07:55 UTC
