### ISSUE TITLE
Unit tests cannot be run using Mocha

### ISSUE THREAD

**Issue by iwfan** [vuejs/vue-cli#2300] opened 2018-08-21 06:58 UTC
### Version
3.0.1

### Node and OS info
Node 8.11.3 / yarn 1.6.0 / Windows 10

### Steps to reproduce
Here go my steps:

Generated new project with vue-cli 3.
```shell
Vue CLI v3.0.1
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS, Router, Vuex, CSS Pre-processors, Linter, Unit
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript for auto-detected polyfills? Yes
? Use history mode for router? (Requires proper server setup for index fallback in production) Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Stylus
? Pick a linter / formatter config: Prettier
? Pick additional lint features: Lint on save, Lint and fix on commit
? Pick a unit testing solution: Mocha
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
```
The following picture is the configuration I chose.
![my config](https://i.loli.net/2018/08/21/5b7bb55766e01.jpg)

After the installation is over, run `yarn test:unit` directly.

### What is expected?
Running unit tests correctly.

### What is actually happening?
I got this error:

```shell
$ vue-cli-service test:unit
 WEBPACK  Compiling...

Starting type checking service...
Using 1 worker with 2048MB memory limit
  [======================== ] 95% (emitting)

 ERROR  Failed to compile with 1 errors

 error  in ./tests/unit/HelloWorld.spec.ts

Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Super expression must either be null or a function
    at _inherits (E:\GitRepositories\test-unit-1\node_modules\prettier\index.js:1945:11)
    at E:\GitRepositories\test-unit-1\node_modules\prettier\index.js:32893:5
    at E:\GitRepositories\test-unit-1\node_modules\prettier\index.js:32913:4
    at createCommonjsModule (E:\GitRepositories\test-unit-1\node_modules\prettier\index.js:181:35)
    at Object.<anonymous> (E:\GitRepositories\test-unit-1\node_modules\prettier\index.js:32885:18)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object._module2.default._extensions.(anonymous function) [as .js]
(E:\GitRepositories\test-unit-1\node_modules\mocha-webpack\lib\util\registerRequireHook.js:141:62)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Program (E:\GitRepositories\test-unit-1\node_modules\eslint-plugin-prettier\eslint-plugin-prettier.js:393:26)
    at listeners.(anonymous function).forEach.listener (E:\GitRepositories\test-unit-1\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)

 @ ./node_modules/mocha-webpack/lib/entry.js 7:0-57

  [=========================] 100% (completed)
 WEBPACK  Failed to compile with 1 error(s)

Error in ./tests/unit/HelloWorld.spec.ts

  Module build failed (from ./node_modules/eslint-loader/index.js):
  TypeError: Super expression must either be null or a function
      at E:\GitRepositories\test-unit-1\node_modules\prettier\index.js:32893:5      at E:\GitRepositories\test-unit-1\node_modules\prettier\index.js:32913:4
 ERROR  mocha-webpack exited with code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

---
This issue did not occur after switching to `Jest`

**Comment by sodatea** [comment] 2018-08-21 11:15
Duplicate of https://github.com/vuejs/vue-cli/issues/2128

**Closed by sodatea** 2018-08-21 11:15 UTC

**Comment by sodatea** [comment] 2018-08-21 11:16
You might need to clear your yarn cache by running `yarn cache clean`.

**Comment by themathmagician** [comment] 2018-09-28 22:35
I am getting this error as well - using webpack and trying to run a hello world vue test. Any advice? (have cleared cache, etc)
