### ISSUE TITLE
webpack produces new hash on every build

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/vue-cli#3475] opened 2019-02-19 19:49 UTC
### Version
2.6.6

### Reproduction link
[https://github.com/jacekkarczmarczyk/vue-webpack-hash-issue](https://github.com/jacekkarczmarczyk/vue-webpack-hash-issue)

main.ts:
```ts
const foo = () => ({
  component: () => import(/* webpackChunkName: "chunk" */'@/chunk.vue'),
});
foo();
```

chunk.vue:
```vue
<template>
  <div />
</template>
```

### Steps to reproduce
clone the repo and run

`yarn && yarn build && git add . && yarn build && git status`

### What is expected?
chunks' hahses should be the same (git diff should not show any files not staged for commit)

### What is actually happening?
```
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   dist/index.html
        new file:   dist/js/app-legacy.155770f0.js
        deleted:    dist/js/app-legacy.a12773d6.js
        renamed:    dist/js/app.ffad86f5.js -> dist/js/app.fd34753d.js
        new file:   dist/js/chunk-legacy.5dbcfb01.js
        deleted:    dist/js/chunk-legacy.a5727f74.js
        new file:   dist/js/chunk.13f19048.js
        deleted:    dist/js/chunk.dc249bd6.js

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   dist/index.html
        deleted:    dist/js/app-legacy.155770f0.js
        deleted:    dist/js/app.fd34753d.js
        deleted:    dist/js/chunk-legacy.5dbcfb01.js
        deleted:    dist/js/chunk.13f19048.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        dist/js/app-legacy.0c621562.js
        dist/js/app.e38b44d2.js
        dist/js/chunk-legacy.acbc2f32.js
        dist/js/chunk.1c5aa6af.js
```

### Additional info
I've created an issue in vuejs repo because it might be related to the template compiler or vue-loader. Changing the chunk.vue from
```vue
<template>
  <div />
</template>
```

to 

```vue
<script>
export default {
  render: h => h('div')
};
</script>
```
solves the problem

**Comment by yyx990803** [comment] 2019-02-19 20:25
This looks pretty weird since the chunk actually contains the exact same content across builds, but webpack somehow is generating different contenthash for it (which causes the entry chunk to change too because it contains the hash for the lazy chunk).

This looks like a regression from webpack since I'm pretty sure this didn't happen in the past...

**Comment by yyx990803** [comment] 2019-02-19 20:28
Related:

https://github.com/webpack/webpack/issues/7984
https://github.com/webpack/webpack/issues/8419

**Comment by jacekkarczmarczyk** [comment] 2019-02-20 08:35
@yyx990803 3.4.1 release fixed this bug in my project, i didn't check this test repo

**Comment by sodatea** [comment] 2019-02-20 08:53
@jacekkarczmarczyk I suppose it's fixed by https://github.com/vuejs/vue-cli/commit/a2bc927ac837ac6b343f597be4271f0ce9d688f1 Maybe there's an environment variable got changed between builds, thus triggering that bug.

**Closed by sodatea** 2019-02-20 08:53 UTC
Labels: bug, upstream
