### ISSUE TITLE
Picking Prettier along with Eslint preset

### ISSUE THREAD

**Issue by jjangga0214** [vuejs/vue-cli#5321] opened 2020-03-26 00:59 UTC
### What problem does this feature solve?
Currently, there's no option to pick specific Eslint preset along with Prettier.
For example, users can't scaffold Airbnb Eslint preset with  Prettier configuration. 

![Screenshot from 2020-03-26 09-51-31](https://user-images.githubusercontent.com/28584151/77599587-8cdf6300-6f48-11ea-94f6-c0ad3ee01dd3.png)

### What does the proposed API look like?
I think we can provide these new options.

- ESLint  + Airbnb config +  Prettier
- ESLint  + Standard config + Prettier

**Comment by sodatea** [comment] 2020-03-27 07:20
Duplicate of https://github.com/vuejs/vue-cli/issues/2462

**Closed by sodatea** 2020-03-27 07:20 UTC
