### ISSUE TITLE
vue create node under v8.10.0: Error: Failed to resolve plugin: @vue/cli-service

### ISSUE THREAD

**Issue by zigomir** [vuejs/vue-cli#1396] opened 2018-05-29 17:51 UTC
### Version
3.0.0-beta.14

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
`npm i -g @vue/cli` or `yarn add global @vue/cli`.
Then run `vue create <project-name>` and select default settings.

### What is expected?
Command to scaffold  project and install dependencies.

### What is actually happening?
Command creates `package.json`,  `package-lock.json` files and installs some (or all?) dependencies into `node_modules` dir, but doesn't scaffold any other files.

It fails with error:

```
🚀  Invoking generators...
 ERROR  Error: Failed to resolve plugin: @vue/cli-service
Error: Failed to resolve plugin: @vue/cli-service
    at Creator.resolvePlugins (/Users/ziga/.nvm/versions/node/v8.9.4/lib/node_modules/@vue/cli/lib/Creator.js:303:15)
    at Creator.create (/Users/ziga/.nvm/versions/node/v8.9.4/lib/node_modules/@vue/cli/lib/Creator.js:146:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by LinusBorg** [comment] 2018-05-29 21:03
Are you on windows 10? I think I heard a couple of people report problems with 10

**Comment by marco-carvalho** [comment] 2018-05-29 21:18
@LinusBorg i'm on win10 with 3.0.0-beta.14 and this is happening

**Comment by yyx990803** [comment] 2018-05-29 21:49
@Akryum can you look into this? I believe it's related to the changes to `resolveModules` [here](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/util/module.js#L1-L9) merged from the UI branch.

**Comment by doot0** [comment] 2018-05-29 22:43
Happening on macOS High Sierra 10.13.4 with 3.0.0-beta.14.

**Comment by andrewb273** [comment] 2018-05-29 23:11
Happening for me on Win 7 with 3.0.0-beta.14

**Comment by C-Higgins** [comment] 2018-05-30 00:43
I'm on RHEL7

**Comment by zhangbobell** [comment] 2018-05-30 02:45
Me too, happening on macOS High Sierra 10.13.4 with 3.0.0-beta.14.

**Comment by iquejay** [comment] 2018-05-30 03:58
happening with 3.0.0-beta.14.

**Comment by zhangbobell** [comment] 2018-05-30 04:27
😆 a temporary solution maybe: 
1. install beta.11
2. create new project
3. upgrade to beta.14

**Comment by mashirozx** [comment] 2018-05-30 07:10
@zhangbobell  beta.14Still not work on windows...

**Comment by Akryum** [comment] 2018-05-30 07:21
If you can, please try upgrading to node 8.9.x or newer and report back if it works for you.

**Comment by zhangbobell** [comment] 2018-05-30 07:26
@mashirozx I means you could totally remove vue-cli beta.14 and install beta.11, then create project, finally you could upgrade from beta.11 to beta.14 😄

**Comment by Akryum** [comment] 2018-05-30 07:28
@mashirozx Could you try node 8.11.2 please?

**Comment by zigomir** [comment] 2018-05-30 07:38
@Akryum I just updated node from 8.9.4 to 8.11.2 and it works in this version of node. I first tried with npm 5.6.0 (which comes with 8.9.4 – it works) and even with 6.1.0 it works.

**Comment by Akryum** [comment] 2018-05-30 07:39
@zigomir So it worked with node 8.9.4 for you?

**Comment by zigomir** [comment] 2018-05-30 07:41
@Akryum no, it doesn't work in 8.9.4.

**Comment by Akryum** [comment] 2018-05-30 07:42
Ok. Also npm shouldn't be the cause of the issue.

**Comment by zigomir** [comment] 2018-05-30 07:48
It works in 8.10.0 too. Looking at https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/util/module.js#L4 and https://nodejs.org/en/blog/release/v8.10.0/ (search for `require.resolve`) I'm almost sure it is related.

**Comment by Akryum** [comment] 2018-05-30 07:50
Yes it's related. So the working version of `require.resolve(request, options)` is 8.10.0, thanks!

I implemented a fallback resolver for older versions of node:

![capture d ecran 2018-05-30 a 09 48 24](https://user-images.githubusercontent.com/2798204/40706710-e9b6b1e4-63ee-11e8-805d-00a78e76659e.png)

**Comment by mashirozx** [comment] 2018-05-30 07:57
@Akryum Yes, Node v8.11.2 works 👍

**Closed** 2018-05-30 13:44 UTC
Labels: bug, priority: now

**Comment by macwac** [comment] 2018-06-06 11:12
i have same problem on node 9.2.1 and vue-cli v3.0.0-beta.15

**Comment by LinusBorg** [comment] 2018-06-06 11:34
then open a new issue. this one is outdated and closed.
