### ISSUE TITLE
Error: Cannot find module 'typescript/package.json' updating to rc.7 version

### ISSUE THREAD

**Issue by algil** [vuejs/vue-cli#1964] opened 2018-07-27 16:53 UTC
### Version
3.0.0-rc.7

### Node and OS info
Node 10.7.0 / yarn 1.7.0 / MacOS X 10.13.6

### Steps to reproduce
Update all @vue/ packages from rc.4 to rc.7 version
Run `yarn serve`

### What is expected?
Compilation was successfully 

### What is actually happening?
An error is shown
```
$ yarn serve
yarn run v1.7.0
$ vue-cli-service serve
 INFO  Starting development server...
 ERROR  Error: Cannot find module 'typescript/package.json'
Error: Cannot find module 'typescript/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at api.chainWebpack.config (/Users/algil/dev/my-project/node_modules/@vue/cli-plugin-typescript/index.js:27:23)
    at webpackChainFns.forEach.fn (/Users/algil/dev/my-project/node_modules/@vue/cli-service/lib/Service.js:209:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/algil/dev/my-project/node_modules/@vue/cli-service/lib/Service.js:209:26)
    at Service.resolveWebpackConfig (/Users/algil/dev/my-project/node_modules/@vue/cli-service/lib/Service.js:213:48)
    at PluginAPI.resolveWebpackConfig (/Users/algil/dev/my-project/node_modules/@vue/cli-service/lib/PluginAPI.js:110:25)
    at serve (/Users/algil/dev/my-project/node_modules/@vue/cli-service/lib/commands/serve.js:48:31)
    at Service.run (/Users/algil/dev/my-project/node_modules/@vue/cli-service/lib/Service.js:203:12)
    at Object.<anonymous> (/Users/algil/dev/my-project/node_modules/@vue/cli-service/bin/vue-cli-service.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

---
package.json:

```json
{
  "name": "my-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "dev": "yarn serve:electron",
    "test:unit": "vue-cli-service test:unit",
    "test:e2e": "vue-cli-service test:e2e",
    "build:electron": "vue-cli-service build:electron",
    "serve:electron": "vue-cli-service serve:electron"
  },
  "dependencies": {
    "lodash": "^4.17.10",
    "portal-vue": "^1.3.0",
    "vee-validate": "^2.1.0-beta.6",
    "vue": "^2.5.16",
    "vue-class-component": "^6.2.0",
    "vue-i18n": "^8.0.0",
    "vue-property-decorator": "^7.0.0",
    "vue-resize": "^0.4.4",
    "vue-responsive-components": "^0.2.3",
    "vue-router": "^3.0.1",
    "vuescroll": "^4.6.5",
    "vuex": "^3.0.1",
    "vuex-class": "^0.3.1"
  },
  "devDependencies": {
    "@types/jest": "^23.3.1",
    "@types/webpack": "^4.4.8",
    "@types/webpack-env": "^1.13.6",
    "@vue/cli-plugin-babel": "^3.0.0-rc.7",
    "@vue/cli-plugin-e2e-cypress": "^3.0.0-rc.7",
    "@vue/cli-plugin-typescript": "^3.0.0-rc.7",
    "@vue/cli-plugin-unit-jest": "^3.0.0-rc.7",
    "@vue/cli-service": "^3.0.0-rc.7",
    "@vue/test-utils": "^1.0.0-beta.21",
    "babel-core": "7.0.0-bridge.0",
    "electron": "^2.0.5",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.0.3",
    "ts-jest": "^23.0.1",
    "vue-cli-plugin-electron-builder": "^1.0.0-beta.6",
    "vue-template-compiler": "^2.5.16"
  },
  "main": "dist_electron/bundled/background.js"
}

```

**Comment by Akryum** [comment] 2018-07-27 16:58
Duplicate of #1962

**Closed by Akryum** 2018-07-27 16:58 UTC
