### ISSUE TITLE
@vue/cli fails to install using both npm and yarn

### ISSUE THREAD

**Issue by teleclimber** [vuejs/vue-cli#2213] opened 2018-08-14 18:54 UTC
### Version
3.0.0

### Node and OS info
node 10.8, npm 6.2, yarn 1.9.4

### Steps to reproduce
npm install -g @vue/cli

..or..

yarn global add @vue/cli

### What is expected?
vue cli installs.

### What is actually happening?
I get an error. In yarn: 

"error Package "apollo-server-core" refers to a non-existing file '"/Users/ollie/.config/yarn/apollo-server-core"'."

In npm :

code ENOLOCAL
npm ERR! Could not install from "../../usr/local/lib/node_modules/@vue/cli/node_modules/apollo-server-core" as it does not contain a package.json file.

---
I'm on Mac, 10.12.6

**Comment by ph1p** [comment] 2018-08-14 19:14
The problem is `apollo-server-express`. I manually downgraded the `apollo-server-core` core to 2.0.0 and it works.

---
```bash
cd YOUR_PATH/@vue/cli/node_modules/apollo-server-express
```
change `"apollo-server-core": "..."` to `"apollo-server-core": "2.0.0"`

```bash
npm update --save
```
---

This is only a small work around and `apollo-server-express` or `apollo-server-core` should update their packages.

**Comment by Akryum** [comment] 2018-08-14 19:30
Fixed with `apollo-server-express` `2.0.2`. Try remove and add `@vue/cli` again.

**Closed by Akryum** 2018-08-14 19:30 UTC
Labels: upstream

**Comment by moslemir** [comment] 2018-08-14 19:52
not work
![vue-cli](https://user-images.githubusercontent.com/1429030/44114707-3f2f414a-a021-11e8-8f52-1d2e5721b67f.jpg)

**Comment by darthchudi** [comment] 2018-11-28 10:46
I have this same problem. Not sure where it's coming from. Fails to install with both npm and yarn.

**Comment by chakri622** [comment] 2019-01-12 23:43
Install the failed packages manually, then rerun the installation of @vue/cli, it will install successfully.
