### ISSUE TITLE
Document plugin naming convention

### ISSUE THREAD

**Issue by ascendancyy** [vuejs/vue-cli#1056] opened 2018-03-29 23:38 UTC
### What problem does this feature solve?
There is a naming convention for third party plugin developers that doesn't seem to be documented anywhere (granted it's still in beta).  

~~Also the fact that you can use invoke/add using shorthand. I could see users getting confused on whether or not `@myscope/vue-cli-plugin-awesomeplugin` and `@myscope/awesomeplugin` are the same thing. Not to mention that you can do `vue invoke plugin` if its an official vue-cli plugin.~~

~~I feel like requiring the explicit package name would be a lot better. It would be less confusing, there would be no need to document a naming convention and get issues about why something isn't working, and we would also be able to name our plugins wild esoteric things. Is there a strong reason for doing this? Or am I just misunderstanding something?~~

### What does the proposed API look like?
~~No shorthand for `vue invoke|add`.~~

**Comment by Akryum** [comment] 2018-03-30 00:14
> there would be no need to document a naming convention

You still need to name your plugin with the `vue-cli-plugin-` form or else things will break. Also your plugin won't appear in search. If the naming convention isn't well documented yet, maybe it's time to do it properly. 🐈 

> we would also be able to name our plugins wild esoteric things

Sorry, this is not currently technically possible.

**Comment by elevatebart** [comment] 2018-03-30 03:28
Hey @ascendancyy ,

Here is another pointer :

At compile time, the vue cli runs through the dependencies to find the plugins.
It then adds configurations of each plugin to the webpack configuration. 
This allows plugin developpers to customize implicitly the webpack configuration without invading user files.

=> No prefixing plugins, no webpack configuration 

The choice of abstracting the configuration is by design. It can be counter-intuitive at first but allows for better upgradability.

Hope this helps

**Comment by ascendancyy** [comment] 2018-03-30 03:45
Ah okay that makes sense. The package naming should definitely find its way onto a doc page though.

**Comment by yyx990803** [comment] 2018-06-08 03:56
Closing as this is addressed in the refactored docs.

**Closed by yyx990803** 2018-06-08 03:56 UTC
Labels: docs
