### ISSUE TITLE
npm ERR! notarget No matching version found for @apollographql/apollo-tools@^0.4.6

### ISSUE THREAD

**Issue by jagj77** [vuejs/vue-cli#5403] opened 2020-04-17 22:24 UTC
### Version
4.3.1

### Environment info
```
I can't install vue.
```

### Steps to reproduce
npm install -g @vue/cli

### What is expected?
vue-cli installed

### What is actually happening?

npm ERR! code ETARGET

npm ERR! notarget No matching version found for @apollographql/apollo-tools@^0.4.6

npm ERR! notarget In most cases you or one of your dependencies are requesting

npm ERR! notarget a package version that doesn't exist.

npm ERR! notarget 

npm ERR! notarget It was specified as a dependency of 'apollo'
.

**Comment by Phoscur** [comment] 2020-04-17 22:27
Duplicate of #5402

**Comment by rx2347** [comment] 2020-04-17 22:52
For whats it worth, I just looked at the npmjs registry and there is only a 0.4.6-alpha.0 for apollo-tools registered.

https://www.npmjs.com/package/@apollographql/apollo-tools

**Comment by willlymendoza** [comment] 2020-04-17 23:02
> For whats it worth, I just looked at the npmjs registry and there is only a 0.4.6-alpha.0 for apollo-tools registered.
> 
> https://www.npmjs.com/package/@apollographql/apollo-tools

I did the same, :(

**Comment by amc1999** [comment] 2020-04-18 01:12
It is solved by apollo team, everything OK with @vue/cli now

**Comment by rx2347** [comment] 2020-04-18 01:14
I can confirm this. Issue can be closed.

**Comment by willlymendoza** [comment] 2020-04-18 01:34
Confirmed, it is working now!

**Closed** 2020-04-18 20:02 UTC
