### ISSUE TITLE
node 18 support

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/vue-cli#7116] opened 2022-04-25 20:13 UTC
### What problem does this feature solve?
It solve the issue that vue cli can't be installed on node 18 because `@achrinza/node-ipc@9` doesn't support it

```
$ yarn
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.0.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### What does the proposed API look like?
Allow `@achrinza/node-ipc@10`

**Comment by janlauber** [comment] 2022-04-26 14:13
got the same issue when trying to install:
```bash
yarn global add @vue/cli@next
```

**Comment by 9mm** [comment] 2022-04-28 16:23
Im getting an issue with `node-ipc` and so I tried to upgrade vue/cli with `yarn global upgrade-interactive` and i get

> @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.0.0"

**Comment by FlorianLoch** [comment] 2022-04-29 08:24
I think requiring `9.2.4` (released two days ago, so after this issue has been created) instead of `9.2.3` will do the trick - no need to bump the major version.

https://github.com/achrinza/node-ipc/releases/tag/v9.2.4

**Comment by wxh06** [comment] 2022-04-30 04:14
The temporary solution is:

```sh
yarn --ignore-engines
```

Reference:

```sh
$ yarn help | grep -- --ignore
    --ignore-engines                    ignore engines check
    --ignore-optional                   ignore optional dependencies
    --ignore-platform                   ignore platform checks
    --ignore-scripts                    don't run lifecycle scripts
```

**Comment by 9mm** [comment] 2022-05-01 16:54
How do I even create a project with vue-cli? It seems to run yarn automatically

**Comment by wxh06** [comment] 2022-05-02 00:10
> How do I even create a project with vue-cli? It seems to run yarn automatically

```sh
yarn config set ignore-engines true
```

**Comment by 9mm** [comment] 2022-05-03 16:30
Ok thanks! Do you know if there a permanent solution in the works? Considering this breaks new installs it seems weird it isnt a higher priority. Also I don't like setting to ignore other things as there may be other conflicts etc.

**Comment by FlorianLoch** [comment] 2022-05-03 20:42
I admit, I am wondering too that this topic does not get much more attention. But perhaps Node.js 18 does not have too much adoption yet? But I hardly believe that...

**Comment by jsonkody** [comment] 2022-05-09 13:08
Please update the dependency to @achrinza/node-ipc@9.2.4
I need vue@cli in my work and I must use only Npm (not Yarn) AND I can't downgrade to node 16 easily :/

**Comment by LinusBorg** [comment] 2022-05-09 14:20
~~The current version range is already `@9` so a fresh install will give you `9.2.4`. You need to remove the lockfile though.~~

I'm wrong.

The reason the version is pinned should be obvious after the fiasco that made a switch to a fork necessary.

We'll see to it that this is upgraded.

Npm also supports overrides for some time now:

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by haoqunjiang** [comment] 2022-06-21 09:28
Fixed in 5.0.6

**Closed as completed by haoqunjiang** 2022-06-21 09:28 UTC

**Comment by kabkee** [comment] 2022-07-24 08:07
> got the same issue when trying to install:
> 
> ```shell
> yarn global add @vue/cli@next
> ```

saved my life.

**Comment by DevCleverton** [comment] 2023-04-04 19:51
test('top level test', async (t) => {
  await t.test('subtest 1', (t) => {
    assert.strictEqual(1, 1);
  });

  await t.test('subtest 2', (t) => {
    assert.strictEqual(2, 2);
  });
});

**Comment by MikeMitterer** [comment] 2023-08-22 12:41
Now it's the same with node 20 - please support this version

**Comment by albertomenen** [comment] 2024-08-22 08:16
Yes same problem right now, even with ignore-engines is giving us problems. Is this problem solve already for you team?

**Comment by CodeXiD** [comment] 2024-08-27 13:21
Unfortunately, the problem is relevant for me.

I get this error when installing dependencies at the moment
```
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.19.0"
error Found incompatible module.
```

Any updates on this issue?

**Comment by christeena-mary** [comment] 2024-09-09 03:08
Still facing the same problem , anybody have any update
`error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.19.0"
error Found incompatible module.`

**Comment by albertomenen** [comment] 2024-09-09 05:09
Yeah actually the only problem I could solve with this is changing the version an check dependencies to create a stable version. What works for me its either change the node version:

`nvm i 17`

Or install with this command after.

`"what you want to install" --ignore-engines`

Hope that helps!

**Comment by ptramontina** [comment] 2025-01-09 16:13
Just to add some extra help. I was trying to use `--ignore-engines`, but it was not working. It looked like the flag was being ignored by `yarn`.
What worked for me was to add the ignore globally, by using `yarn config set ignore-engines true`.
