### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by qilvnuanqingyou** [vuejs/vue-cli#1744] opened 2018-07-04 03:20 UTC
### Version
3.0.0-rc.3

### Reproduction link
[https://codesandbox.io/s/ppzz4pnj3x](https://codesandbox.io/s/ppzz4pnj3x)

### Steps to reproduce
vue.config.js 
proxy: {
            '/': {
                target: 'http://192.168.4.69:8080',
                ws: true,
                changeOrigin: true
            }

### What is expected?
no error, I also try this with  vue-cli 2.9.6, It doesn't have this problem

### What is actually happening?
I succeeded in getting the data, but the prompt was wrong:
Proxy error: Could not proxy request /sockjs-node/802/ehlkoad1/websocket from localhost:4200 to http://192.168.4.69:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

---
Can't I set the '/' ?

**Comment by sijakret** [comment] 2018-07-05 17:55
I am struggling with this as well.

For me the `devServer` section seems to be completely ignored:

with the config below i can print it with `vue inspect devServer`, so it ends up in the webpack config correctly, but the proxying is not working.
Seems to me like the devServer settings are taken from elsewhere, maybe via cli argument to webpack-dev-server.

Is the following supposed to work?

```js
module.exports = {
  configureWebpack: {
    devServer: {
      proxy: {
        "/route": {
          target: "http://localhost:3002",
        }
      }
    }
  }
}
```

**Comment by LinusBorg** [comment] 2018-07-05 18:17
Please have another look at the config documentation - there's an extra option for `devServer`, which you should use instead of configWebpack

**Comment by qilvnuanqingyou** [comment] 2018-07-06 02:08
@sijakret if your vue-cli is 3.0 version, you should set the proxy in vue.config.js like this:
module.exports = {
    devServer: {
      proxy: {
        "/route": {
          target: "http://localhost:3002",
        }
      }
    }
  }

**Comment by LinusBorg** [comment] 2018-07-13 14:12
I'm closing this since OPs problem seems to be resolved.

**Closed by LinusBorg** 2018-07-13 14:12 UTC
Labels: feat: cli-service serve, question

**Comment by scccboom** [comment] 2019-01-26 02:35
@qilvnuanqingyou  I also met the same problem, how to solve it?

**Comment by nickdex** [comment] 2019-02-02 05:42
I was facing similar problem. My api server was hosted on `http://localhost:3000/` and Vue app on `http://localhost:8080`, and my Config `devServer: { proxy: 'http://localhost:3000' }`. When I tried to resolve api call eg `GET http://localhost:8080/clients` I would get ECONNRESET error.

My solution (found it accidentally) was to add catch all in my vue router mappings, I hope this helps someone else too.

```Javascript
mode: 'history',
  base: process.env.BASE_URL,
  routes: [
    {
      path: '/',
      name: 'login',
      component: Login
    },
    {
      path: '/home',
      name: 'home',
      component: Home
    },
// Adding this solved my problem
    {
      path: '*',
      component: Login
    }
  ]
```

**Comment by getElementBy1d** [comment] 2019-07-05 09:38
I also encountered this problem. Has it been solved?

**Comment by samuraichickenfish** [comment] 2019-07-25 14:03
I don't see how this has been solved, I have this issue as well after upgrading from the old templates. It used to be that the HMR ws conn would not be proxied, the only thing I can think to do as a hacky fix would be to prepend some string to the front of all of my api routes and that is not an acceptable solution. Please give more feedback.

**Comment by and54** [comment] 2019-08-13 20:32
it is not solved

**Comment by chiyanhui** [comment] 2019-09-18 12:45
Maybe this works:

```javascript
module.exports = {
  devServer: {
    hot: true, // https://webpack.js.org/configuration/dev-server/#devserverhot
    proxy: {
      '/': {
        target: 'http://127.0.0.1:3000/',
        ws: true,
        changeOrigin: true,
      },
    },
  },
}
```

**Comment by rotelando** [comment] 2019-10-16 20:41
I have encountered this issue also. Been trying to find a solution for some days now. Got it to work but after a day or two, it stopped working. Any one with a solution should please help.

**Comment by focussing** [comment] 2019-10-31 10:48
https://techformist.com/vuejs-proxy-error-for-backend-connection/

also tried this one; sometimes it works, sometimes it doesn't...
Sorry I found nothing that reproduces, but maybe a bell might ring somewhere?

**Comment by ajslater** [comment] 2020-05-06 17:08
127.0.0.1 works for me with a devProxy whereas 'localhost' does not. Could be a resolving issue native to macOS, haven't tested on other platforms.

**Comment by zhangxiaoshang** [comment] 2020-05-27 03:28
同样碰到过几次类似问题
可以从以下几个方面尝试解决
- 检查proxy配置的是否正确
- dns是否能正常解析，有可能因网络问题不能正常解析，可以手动配置hosts
- 有可能是proxy设置的不够严谨

举个例子

```js
'/data/':
   { target: 'https://data.domain.com',
     changeOrigin: true,
     pathRewrite: { '/data/': '/' } },
/live/':
   { target: 'https://domain.live',
     changeOrigin: true,
     pathRewrite: { '/live/': '/' } } }
```

当发起一个Get    http://localhost:8080/live/1/data/rate.json
期望代理到   https://domain.live/1/data/rate.json

实际上 这个请求路径中还有一个 `/data/` 会被第一个配置匹配到 所以就会出现问题
解决方案是将配置写的尽量严谨，比如改为：
```js
'^/data/':
   { target: 'https://data.domain.com',
     changeOrigin: true,
     pathRewrite: { '^/data/': '/' } },
^/live/':
   { target: 'https://domain.live',
     changeOrigin: true,
     pathRewrite: { '^/live/': '/' } } }
```

**Comment by maleta** [comment] 2020-07-05 07:54
I run into this problem. I am using WSL and everything worked nicely for more than a year, but now I get this error whenever I do update on backend(proxy) and do not restart client app as well.
