### ISSUE TITLE
Component library with component that is composed of another does not render the base component

### ISSUE THREAD

**Issue by lukef** [vuejs/vue-cli#5851] opened 2020-09-05 15:42 UTC
### Version
3.0.0-rc.10

### Reproduction link
[https://github.com/lukef/vue-component-repro](https://github.com/lukef/vue-component-repro)

[https://stackoverflow.com/questions/63758716/vue-3-component-library-with-component-that-is-composed-of-another-does-not-ren](https://stackoverflow.com/questions/63758716/vue-3-component-library-with-component-that-is-composed-of-another-does-not-ren)

### Steps to reproduce
I have included a project that will demonstrate the issue. Instructions in README.

### What is expected?
`<cool-component>` is derived from `<base-component>`. My expectation is that when `<cool-component>` is rendered that it should also render the base component as well. That isn't happening.  

### What is actually happening?
What happens is that `<cool-component>` is rendered but `<base-component>` (in this case `<BaseComponent>`) is not being rendered and is being translated to the literal tag `<basecomponent>` (no hyphen). 

---
The console contains the following warning: `[Vue warn]: resolveComponent can only be used in render() or setup().`

Not really sure what I've done wrong with setup or whether this is a bug.

**Comment by posva** [comment] 2020-09-07 07:36
@lukef transferred to vue-cli as it seems related to how the build service is used

**Comment by posva** [comment] 2020-09-07 08:27
I think the issue actually comes from vue-next. Someone also opened https://github.com/vuejs/vue-next/issues/2064. Closing in favor of that one because the reproduction is much simpler

**Closed by posva** 2020-09-07 08:27 UTC

**Comment by posva** [comment] 2020-09-07 13:06
See https://github.com/vuejs/vue-next/issues/2064#issuecomment-688296352. You also need to make sure your lib and app are using the same vue instance because right now they are both importing Vue from different files

**Comment by lukef** [comment] 2020-09-07 15:27
I still don't see a solution to the issue in that other issue that resolves this one so I'm not really sure it is closed. I tried modifying the webpack config in my `vue.config.js` file to include:

```vue$: path.resolve("./node_modules/vue/dist/vue.runtime.esm.js")```

But this create a myriad of other issues if you're using vuex, vue-router, etc in the consuming project.

It shouldn't be this hard to make a component library for vue.

**Comment by lukef** [comment] 2020-09-07 16:16
I also tried converting my plugin to use rollup via https://github.com/team-innovation/vue-sfc-rollup (4.0-beta) and I get the exact same issue.

**Comment by alvarosaburido** [comment] 2020-09-17 06:04
I'm having the same issue that  @lukef in my library https://github.com/alvarosaburido/vue-dynamic-forms. If I use it on a typescript vue3 app like the. one in `dev/typescript` it works, but in a javascript one `dev/vue`, it doesn't 

The console also output the following  warnings:
