### ISSUE TITLE
Command vue-cli-service test:unit failing when file import vue-resource

### ISSUE THREAD

**Issue by pawelbujna** [vuejs/vue-cli#4594] opened 2019-09-19 12:49 UTC
### Version
3.11.0

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/2871](https://github.com/vuejs/vue-cli/issues/2871)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.1004.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.11.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.11.0
    @vue/cli-plugin-babel: ^3.11.0 => 3.11.0
    @vue/cli-plugin-eslint: ^3.11.0 => 3.11.0
    @vue/cli-plugin-unit-mocha: ^3.11.0 => 3.11.0
    @vue/cli-service: ^3.11.0 => 3.11.0
    @vue/cli-shared-utils:  3.11.0
    @vue/component-compiler-utils:  3.0.0
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)
    sweet-modal-vue: ^2.0.0 => 2.0.0
    vue: ^2.6.10 => 2.6.10
    vue-class-component:  7.1.0
    vue-cookies: ^1.5.13 => 1.5.13
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.3
    vue-i18n: ^8.14.0 => 8.14.0
    vue-jwt-decode: ^0.1.0 => 0.1.0
    vue-loader:  15.7.1
    vue-moment: ^3.2.0 => 3.2.0
    vue-property-decorator:  8.2.2
    vue-recaptcha: ^1.2.0 => 1.2.0
    vue-resize:  0.4.5
    vue-resource: ^1.5.1 => 1.5.1
    vue-simple-suggest: ^1.9.5 => 1.9.5
    vue-slider-component: ^3.0.40 => 3.0.40
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuejs-datepicker: ^1.6.2 => 1.6.2
    vuejs-paginate: ^2.1.0 => 2.1.0
    vuelidate: ^0.7.4 => 0.7.4
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
https://github.com/vuejs/vue-cli/issues/2871

### What is expected?
Works.

### What is actually happening?
Crushes.

---
So i found that link: https://github.com/vuejs/vue-cli/issues/2871. I'm having very same problem. Any chances for fixing it?

**Comment by LinusBorg** [comment] 2019-09-19 12:59
Hi  

Thanks for filing this issue! Could you please provide a small reproduction on jsfiddle.net or as a Github repository so we can debug this without trying to replicate this ourselves?

That would be very helpful, thanks!

**Comment by LinusBorg** [comment] 2019-09-19 13:01
As a sidenode this seems to be an issue with `vue-resource` rather than Vue CLI

**Comment by pawelbujna** [comment] 2019-09-19 14:14
npm i; npm run test:utils
https://github.com/pawelbujna/vue-resource-problem

I have same vue-resource version (and vue ^2.5.16) in another vue project where we're using karma and everything works fine there.

**Comment by LinusBorg** [comment] 2019-09-19 14:44
I assume the following:

1., vue-resource uses got, which - optionally - works in electron.
2. we run unit tests tests in node with a simulated browser API (jsdom), not in a real browser (like with karma). Nothing out of the ordinary nowadays, though.
3. presumably, `got` or one of its dependencies thinks its runnning in an electron environment for whatever reason, and therefore, tries to import `electron`
4. but of course there's no electron package

Hence, the error:  `Module not found: 'electron' in '/disk2/projetos/hello-world2/node_modules/got'`

I even took a quick look at got's source but could not figure out where and when this electron stuff exactly comes into play, but generally, it seems to me that got mistakenly detects electron so its their issue. 

If they can identify why that happens and can demonstrate/explain how that's related to something specific to our environment specifically (and not jsdom+mocha/jest in general), we can think about how we might be able to help.

So far I see the ball in got's field.

**Comment by LinusBorg** [comment] 2019-09-19 14:59
Did a quick google for you:

https://github.com/vankasteelj/trakt.tv/issues/34

should have been fixed in got, but seems it can still happen. 

Not really related to us. I recommend trying the fixes proposed in that issue.

**Closed by LinusBorg** 2019-09-19 14:59 UTC
Labels: need feedback
