### ISSUE TITLE
vue ui can't create a project

### ISSUE THREAD

**Issue by YangGoldDragon** [vuejs/vue-cli#3940] opened 2019-05-05 05:58 UTC
### Version
3.7.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (2) x64 Intel(R) Pentium(R) CPU G3258 @ 3.20GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\c\Users\金龙\.npm-packages\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    vue-hot-reload-api: ^1.3.3 => 1.3.3
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
1. enter "vue ui" in gitbash
2. enter http://localhost:8000,  step by step, the end,  create project but it's failed
3. gitbash error message: 
 { Error: Command failed: vue create vuevue --skipGetStarted --packageManager yarn --inlinePreset {"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"standard","lintOn":["save"]}},"cssPreprocessor":"stylus"}

    at makeError (C:\Users\金龙\AppData\Local\Yarn\Data\global\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\金龙\AppData\Local\Yarn\Data\global\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: '',
  stderr: null,
  failed: true,
  signal: null,
  cmd:
   'vue create vuevue --skipGetStarted --packageManager yarn --inlinePreset {"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"standard","lintOn":["save"]}},"cssPreprocessor":"stylus"}',
  timedOut: false,
  killed: false }

### What is expected?
resolve create project in vue ui

### What is actually happening?
I can't create project in vue ui

**Comment by WL-Amigo** [comment] 2019-05-06 08:26
I had same probrem.

* OS: Ubuntu 16.04 LTS (64bit)
* CPU: Intel Core i7-7700HQ CPU
* Mem: 15.5GiB
* Node: 11.6.0
* yarn: 1.15.2
* Language: Japanese

I saw error message `Unknown option --skipGetStarted.` when I tried to create project from `vue ui`.
I also run `vue create --help`, and I found `--skipGetStarted` option in help message.

I run command below (it appeared in error message, and I added some quote), and it completed without any problem.

```
vue create projectname --skipGetStarted --packageManager yarn --git 'Initialize project' --inlinePreset {"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-typescript":{"classComponent":true,"useTsWithBabel":true},"@vue/cli-plugin-pwa":{}},"router":true,"routerHistoryMode":false,"cssPreprocessor":"node-sass"}
```

**Comment by Akryum** [comment] 2019-05-06 09:55
@WL-Amigo which quotes did you add?

**Comment by WL-Amigo** [comment] 2019-05-06 10:09
@Akryum `--git` and `--inlinePreset`.

(And I'm aware just now I wrote wrong info in comment above... I updated with correct one. Sorry for my mistake.)

**Comment by Akryum** [comment] 2019-05-06 11:35
What was the original command that failed?

**Comment by WL-Amigo** [comment] 2019-05-06 11:53
```
'vue create projectname --skipGetStarted --packageManager yarn --git Initialize project --inlinePreset {"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-typescript":{"classComponent":true,"useTsWithBabel":true},"@vue/cli-plugin-pwa":{}},"router":true,"routerHistoryMode":false,"cssPreprocessor":"node-sass"}'
```

But this is not valid as shell command, so I added quotes to `--git` and `--inlinePreset` arguments.

It seems to failed when the command spawn from Node.js.

Below is full log when failed to create project from `vue ui`. (I now reproduce issue, so it's bit different from command in my first coment)

```
{ Error: Command failed: vue create testproject --skipGetStarted --packageManager yarn --inlinePreset {"router":false,"vuex":false,"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"base","lintOn":["save"]}}}
Usage: create [options] <app-name>

create a new project powered by vue-cli-service

Options:
  -p, --preset <presetName>       Skip prompts and use saved or remote preset
  -d, --default                   Skip prompts and use default preset
  -i, --inlinePreset <json>       Skip prompts and use inline JSON string as preset
  -m, --packageManager <command>  Use specified npm client when installing dependencies
  -r, --registry <url>            Use specified npm registry when installing dependencies (only for npm)
  -g, --git [message]             Force / skip git intialization, optionally specify initial commit message
  -f, --force                     Overwrite target directory if it exists
  -c, --clone                     Use git clone when fetching remote preset
  -x, --proxy                     Use specified proxy when creating project
  -h, --help                      output usage information

  Unknown option --skipGetStarted.


    at makeError (/home/wlamigo/.config/yarn/global/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/wlamigo/.config/yarn/global/node_modules/execa/index.js:278:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  code: 1,
  stdout:
   'Usage: create [options] <app-name>\n\ncreate a new project powered by vue-cli-service\n\nOptions:\n  -p, --preset <presetName>       Skip prompts and use saved or remote preset\n  -d, --default                   Skip prompts and use default preset\n  -i, --inlinePreset <json>       Skip prompts and use inline JSON string as preset\n  -m, --packageManager <command>  Use specified npm client when installing dependencies\n  -r, --registry <url>            Use specified npm registry when installing dependencies (only for npm)\n  -g, --git [message]             Force / skip git intialization, optionally specify initial commit message\n  -f, --force                     Overwrite target directory if it exists\n  -c, --clone                     Use git clone when fetching remote preset\n  -x, --proxy                     Use specified proxy when creating project\n  -h, --help                      output usage information\n\n  Unknown option --skipGetStarted.\n\n',
  stderr: null,
  failed: true,
  signal: null,
  cmd:
   'vue create testproject --skipGetStarted --packageManager yarn --inlinePreset {"router":false,"vuex":false,"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"base","lintOn":["save"]}}}',
  timedOut: false,
  killed: false }
```

**Comment by YangGoldDragon** [comment] 2019-05-06 12:07
> ue create testproject --skipGetStarted --packageManager yarn --inlinePreset {"router":false,"vuex":false,"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"base","lintOn":["save"]}}}
> Usage: create [options] <app-name>

Hei,friend, do you already resolve the problem?

**Comment by WL-Amigo** [comment] 2019-05-06 12:18
@YangGoldDragon Quick workaround for this probrem is:
1. copy `cmd` in error message
2. quote `--git`, `--inlinePreset` (if these option exist)
3. run in bash

For example, your command after this procedure is below.
```
vue create vuevue --skipGetStarted --packageManager yarn --inlinePreset '{"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"standard","lintOn":["save"]}},"cssPreprocessor":"stylus"}'
```

(If it still fails, removing `--skipGetStarted` may resolve.)

**Comment by Akryum** [comment] 2019-05-06 12:45
I can't reproduce on linux with `@vue/cli` at `3.7.0`.

**Comment by Akryum** [comment] 2019-05-06 12:47
Maybe the error message wasn't representative of the quotes actually used to run the child process. All arguments are already automatically quoted when using `execa`, we don't do any special there.

Maybe vue cli is installed multiple times on the computer, maybe on time using npm and another using yarn?

**Comment by WL-Amigo** [comment] 2019-05-06 12:58
I confirmed `npm ls -g`, then I found there is old version of `@vue/cli`...

After removing vue-cli installed by npm (`npm remove -g @vue/cli`), `vue ui` works again.

Thank you for your generous support!

**Comment by YangGoldDragon** [comment] 2019-05-06 14:09
> I confirmed `npm ls -g`, then I found there is old version of `@vue/cli`...
> 
> After removing vue-cli installed by npm (`npm remove -g @vue/cli`), `vue ui` works again.
> 
> Thank you for your generous support!

![image](https://user-images.githubusercontent.com/22095365/57230724-979cbb00-704b-11e9-99c7-5d15744be180.png)

there is not one old version of @vue/cli, 
I still  uninstall @vue/cli and vue-cli by  (npm remove -g @vue/cli, npm uninstall -g vue-cli , npm uninstall vue-cli,  npm uninstall -g @vue/cli, npm uninstall @vue/cli, yarn global remove vue-cli, yarn global remove @vue/cli, yarn remove vue-cli, yarn global remove @vue/cli) ,
After remove this, I reinstall @vue/cli by yarn global add @vue/cli, but It still can't create a project.

**Comment by YangGoldDragon** [comment] 2019-05-06 14:48
> Maybe the error message wasn't representative of the quotes actually used to run the child process. All arguments are already automatically quoted when using `execa`, we don't do anything special there.
> 
> Maybe vue cli is installed multiple times on the computer, maybe one time using npm and another using yarn?

I uninstall @vue/cli and vue-cli by (npm remove -g @vue/cli, npm uninstall -g vue-cli , npm uninstall vue-cli, npm uninstall -g @vue/cli, npm uninstall @vue/cli, yarn global remove vue-cli, yarn global remove @vue/cli, yarn remove vue-cli, yarn global remove @vue/cli) 

But it still can't create a project .

**Comment by YangGoldDragon** [comment] 2019-05-06 14:53
> I can't reproduce on linux with `@vue/cli` at `3.7.0`.

So I can do what  for you ?

**Comment by YangGoldDragon** [comment] 2019-05-07 00:45
> @YangGoldDragon Quick workaround for this probrem is:
> 
> 1. copy `cmd` in error message
> 2. quote `--git`, `--inlinePreset` (if these option exist)
> 3. run in bash
> 
> For example, your command after this procedure is below.
> 
> ```
> vue create vuevue --skipGetStarted --packageManager yarn --inlinePreset '{"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"standard","lintOn":["save"]}},"cssPreprocessor":"stylus"}'
> ```
> 
> (If it still fails, removing `--skipGetStarted` may resolve.)

Thanks, I have already resolve this problem by your provide commands, But what is problems with "vue  ui", Why it can't be use to correct create a project,  I have some Obsessive compulsive disorders, it make me uncomfortable

**Comment by richardeschloss** [comment] 2019-06-20 05:17
I was able to repro this issue on Debian Linux 9.6, using vue cli version 3.8.4. When attempting to create the project, vue ui fails to make the project directory correctly (it doesn't exist initially), and thus, when I get to the final create step, it encounters the ENOENT errors.

I run the vue ui in debug mode (`vue ui --debug`) and see the following errors when typing in the project name:
```
ENOENT: no such file or directory, stat '$/Software/VueJS/v'
ENOENT: no such file or directory, stat '$/Software/VueJS/vu'
ENOENT: no such file or directory, stat '$/Software/VueJS/vue'
ENOENT: no such file or directory, stat '$/Software/VueJS/vue2'
```
It fails trying to spawn the following command:
> vue create vue2 --skipGetStarted --packageManager npm --inlinePreset '{"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"prettier","lintOn":["save"]},"@vue/cli-plugin-unit-jest":{}},"router":true,"routerHistoryMode":false,"vuex":true}'

However, I can run this same command in the bash shell and vue-cli creates the project ok. 

Does this help?

**Comment by richardeschloss** [comment] 2019-06-20 05:19
Here's the stack trace: 
```
UI 22:02.10 create vue2 [ '--skipGetStarted',
  '--packageManager',
  'npm',
  '--inlinePreset',
  '{"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"prettier","lintOn":["save"]},"@vue/cli-plugin-unit-jest":{}},"router":true,"routerHistoryMode":false,"vuex":true}' ]
{ Error: spawn vue ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn vue',
  path: 'vue',
  spawnargs:
   [ 'create',
     'vue2',
     '--skipGetStarted',
     '--packageManager',
     'npm',
     '--inlinePreset',
     '{"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"prettier","lintOn":["save"]},"@vue/cli-plugin-unit-jest":{}},"router":true,"routerHistoryMode":false,"vuex":true}' ],
  stdout: '',
  stderr: null,
  failed: true,
  signal: null,
  cmd:
   'vue create vue2 --skipGetStarted --packageManager npm --inlinePreset {"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"prettier","lintOn":["save"]},"@vue/cli-plugin-unit-jest":{}},"router":true,"routerHistoryMode":false,"vuex":true}',
  timedOut: false,
  killed: false }
```

**Comment by richardeschloss** [comment] 2019-06-20 06:13
OK... I solved this problem. Figured out what it was (FYI @YangGoldDragon). It's not an issue with vue cli..it has to do with how the vue binary gets resolved. It's located in ~/.npm-global/bin. Either PATH or NODE_PATH have to be set properly, or, what I found to be easier for me was to just create a symbolic link in /usr/bin:

> sudo ln -s ~/.npm-global/bin/vue /usr/bin/vue

Re-run `vue ui` and it should now work (when the ui tries to `spawn` the child process it should no longer encounter ENOENT).

I think this can be closed as non-issue.

**Closed** 2019-06-20 06:16 UTC
Labels: cannot reproduce

**Comment by ImAli7** [comment] 2020-12-09 19:07
Hi everyone,
I got this issue while creating a project by `vue ui`, but I see the following error:
`
vue create <project_name> --skipGetStarted --packageManager npm --no-git --inlinePreset 
{"router":false,"vuex":false,"useConfigFiles":false,"plugins": {"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint": {"config":"base","lintOn":["save"]}}}
`
But the error is:
`Unknown option --skipGetStarted`

However I tried to run that command again without option `--skipGetStarted`, it shows a new error:
`vue create <project_name> --packageManager npm --no-git --inlinePreset 
{"router":false,"vuex":false,"useConfigFiles":false,"plugins": {"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint": {"config":"base","lintOn":["save"]}}}`
`CLI inline preset is not valid JSON: {router:false,vuex:false,useConfigFiles:false,plugins:`

After all, I ran the command below and it finally worked:
`vue create <project_name> --packageManager npm --no-git --default`

But I still don't know default Presets like Babel & ESlint are added or not. I want to use it by default vue 3.

**Comment by bretonio** [comment] 2021-01-25 16:26
I found that adding `--package-manager npm` did the trick. 

Made sense: my error messages all pointed to `yarn` as the culprit.
