### ISSUE TITLE
Invalid options: child "files" fails because [child "json" fails because ["json" must be an object]]

### ISSUE THREAD

**Issue by SevenOutman** [vuejs/vue-cli#1921] opened 2018-07-23 14:49 UTC
### Version
3.0.0-rc.5

### Reproduction link
[http://localhost:8001](http://localhost:8001)

### Steps to reproduce
- Install latest vue-cli via `npm install -g @vue/cli`
- Check version `vue --version`, outputs 3.0.0-rc.5
- Run `vue ui`

### What is expected?
Normal outputs

### What is actually happening?
```bash
$ vue ui
🚀  Starting GUI...
🌠  Ready on http://localhost:8001
Error: Invalid options: child "files" fails because [child "json" fails because ["json" must be an object]]
    at PluginApi.describeConfig (/usr/local/lib/node_modules/@vue/cli/node_modules/@vue/cli-ui/apollo-server/api/PluginApi.js:156:21)
    at module.exports.api (/Users/Doma/Developer/WebstormProjects/vue-locale/node_modules/@vue/cli-plugin-eslint/ui.js:3:7)
    at runPluginApi (/usr/local/lib/node_modules/@vue/cli/node_modules/@vue/cli-ui/apollo-server/connectors/plugins.js:227:7)
    at plugins.forEach.plugin (/usr/local/lib/node_modules/@vue/cli/node_modules/@vue/cli-ui/apollo-server/connectors/plugins.js:167:33)
    at Array.forEach (<anonymous>)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/@vue/cli/node_modules/@vue/cli-ui/apollo-server/connectors/plugins.js:167:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```
and the same stacktrace message repeats

---
Looks like something wrong with the plugins system, but Refresh Plugins API doesn't help

**Comment by SevenOutman** [comment] 2018-07-24 14:05
@yyx990803 It's `Node v8.11.3` with `npm v5.6.0` on a `macOS 10.13.6` machine.

**Comment by yyx990803** [comment] 2018-07-24 14:13
I just did a fresh install with the exact same environment and it's working as expected. Closing as we cannot reproduce the behavior unless more information can be provided.

**Closed by yyx990803** 2018-07-24 14:13 UTC
Labels: cannot reproduce, feat: ui

**Comment by terean-dspd** [comment] 2018-08-01 14:01
And...
step 1: npm update
step 2: npm uninstall -g @vue/cli
sted 3: npm install -g @vue/cli

Finaly helped me
