### ISSUE TITLE
Add baseUrl option in vue-cli-service build command

### ISSUE THREAD

**Issue by ThibaudCrespin** [vuejs/vue-cli#1623] opened 2018-06-19 15:13 UTC
### What problem does this feature solve?
When you deploy on gh-pages, the base url is not the good one, it takes the root, not the repository. So I suggest to add on option to the cli command that will simply change relative urls in the vue application.

### What does the proposed API look like?
vue-cli-service build --baseUrl <MY-BASE-URL>

**Comment by zentby** [comment] 2018-06-19 23:54
Agree. Or just use a relative path for the src URL so that it can also support preview the HTML in anyone's local browser:

When run
```bash
vue build
```
get
```html
    <script src=js/app.e46b869a.js></script>
```
instead of 
```html
    <script src=/js/app.e46b869a.js></script>
```

**Comment by zentby** [comment] 2018-06-19 23:57
My bad. It can be resolved with `vue.config.js` within the same folder:
```js
module.exports = {
    baseUrl: './'
}
```
@ThibaudCrespin I guess you can solve your issue with this one as well.

**Closed** 2018-06-20 00:09 UTC

**Comment by uxweb** [comment] 2018-07-04 21:19
@zentby @yyx990803 

Hi,

I am using `baseUrl` with `.` value because the app can be deployed under any subdirectory of a webserver.

This is making webpack put all dependencies (js/css/sourceMaps) at the root of the dist directory.

Is this the intended behavior?

I was expecting having my js assets inside a js directory as well as my css assets.

![image](https://user-images.githubusercontent.com/5134732/42294325-ace73d88-7fa5-11e8-97f3-f8f1a4a440db.png)

This is the content of my index.html after building for production:

![vue-cli-relative-path-index](https://user-images.githubusercontent.com/5134732/42294374-e92aa0d2-7fa5-11e8-933e-84a9ae7ef18f.png)

am I missing something here?

Thanks!

**Comment by zentby** [comment] 2018-07-06 04:55
@uxweb 

I'm not sure if it's [a bug or intended](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/util/getAssetPath.js). The path prefix will be eliminated if `baseUrl` is set:

```js
if (
    placeAtRootIfRelative &&
    !(/^https?:/.test(options.baseUrl)) &&
    options.baseUrl.charAt(0) !== '/'
  ) {
    return filePath.replace(/^\w+\//, '')
  }
  return options.assetsDir
    ? path.posix.join(options.assetsDir, filePath)
    : filePath
```

The **return filePath.replace(/^\w+\//, '')** will remove the leading 'js' or 'css'

**Comment by ebastuart** [comment] 2018-09-20 10:03
I am using the latest version and it still doesn't work. When I set the baseUrl to './' it will be ignored. 
Please help!

**Comment by hhochart29** [comment] 2018-09-20 10:10
Can you try with this in `vue.config.js` :

module.exports = {
  baseUrl: process.env.NODE_ENV === 'production'
    ? './' // prod
    : '/', // dev
}``

**Comment by y-nk** [comment] 2018-10-03 07:10
is there any lead to solve this bug ?

**Comment by shannonsands** [comment] 2018-10-19 05:36
Same issue. Having to manually run a find & replace.

**Comment by parth55** [comment] 2018-12-18 11:15
I am still facing the issue. I have used below code to remove '/' and made my application work.
`module.exports = {
    baseUrl:''
  }`

With the above code, My application is running but some of css and js files are not getting the correct relative path for production build.

**Comment by parth55** [comment] 2018-12-18 11:22
> @uxweb
> 
> I'm not sure if it's [a bug or intended](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/util/getAssetPath.js). The path prefix will be eliminated if `baseUrl` is set:
> 
> ```js
> if (
>     placeAtRootIfRelative &&
>     !(/^https?:/.test(options.baseUrl)) &&
>     options.baseUrl.charAt(0) !== '/'
>   ) {
>     return filePath.replace(/^\w+\//, '')
>   }
>   return options.assetsDir
>     ? path.posix.join(options.assetsDir, filePath)
>     : filePath
> ```
> 
> The **return filePath.replace(/^\w+//, '')** will remove the leading 'js' or 'css'

May I know where to use this configuration? can you please give in detail code for the same (I mean, dir-->filename --> objName. etc )

**Comment by cawoodm** [comment] 2019-02-18 13:53
IMHO it's just wrong and unnecessary that vue build defaults to `/`. Using `./` would make the built application work just as well hosted in root as from any other subdirectory. It would also fix issues with other platforms (e.g. NWJS) which are not served via HTTP.

**Comment by rpbarbati** [comment] 2019-04-25 01:09
Not sure if this is applicable to what is being discussed, but a valid URL would not be able to start with a dot.

A dot would be valid for a file system, but a web server does not have a file system - it has URL's.  / merely points to whatever is defined on the server as the root context - it most certainly does not point to a root directory of a drive.  . (dot) does not point to anything on a web server (for all the web servers I have ever worked with anyway, and that is pretty much most of them) and is probably just being ignored or causing errors that result in what you think you want.

**Comment by parzibyte** [comment] 2019-06-06 16:31
It's still not working even configuring publicPath to ./ so we need to replace the content manually, but if you have Python installed i made a small script to replace. Just put it next to package.json, or modify the path

```
import re
RUTA_INDEX = "./dist/index.html"
with open(RUTA_INDEX, "r") as archivo :
  contenido = archivo.read()
contenido = re.sub(r"href=([a-zA-Z\.]+)", r"href=./\1", contenido)
contenido = re.sub(r"src=([a-zA-Z\.]+)", r"src=./\1", contenido)
with open(RUTA_INDEX, "w") as archivo:
  archivo.write(contenido)
```

**Comment by ilyaDegtyarenko** [comment] 2019-06-25 13:22
**vue.config.js**

`module.exports = {
    publicPath: 'https://...'
}`

**Comment by NarasimhaA-Hexaware** [comment] 2019-09-04 21:16
I am still facing same issue, any solution?

**Comment by parzibyte** [comment] 2019-09-05 18:13
I had the same issue, so i made a Python Script that calls:
`npm run build`
And after that, it just replaces index.html contents using regular expression:

```python
INDEX_PATH = DIST_PATH + "/index.html"
with open(INDEX_PATH, "r") as file:
    content = file.read()
content = re.sub(r"href=([a-zA-Z\.]+)", r"href=./\1", content)
content = re.sub(r"src=([a-zA-Z\.]+)", r"src=./\1", content)
with open(INDEX_PATH, "w") as file:
    file.write(content)
```
(it just adds `./` to the start)
I know it is not the best solution, but it works!
If you don't know Python, just make the same operations in your favorite language

**Comment by cpury** [comment] 2019-10-30 17:08
Under the newest version, configuring the `basePath` and then running build gives me this:

```
 ERROR  Invalid options in vue.config.js: "baseUrl" is not allowed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mtj-apply-frontend@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
```

**Comment by cornelius-agrippa** [comment] 2019-11-13 11:15
@cpury I ran into the same problem and found your post

After searching a bit more I found out that `baseUrl` is deprecated in the newest versions and to use `publicPath` instead. Here's the reference documentation: https://cli.vuejs.org/config/#baseurl

**Comment by domcorvasce** [comment] 2020-01-23 10:07
`publicPath` doesn't work for me

```js
module.exports = {
  publicPath: './',
};
```

```html
<!DOCTYPE html>
<html lang=en>

<head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="width=device-width,initial-scale=1">
    <link rel=icon href=icon.png>
    <title>X</title>
    <link href=js/about.c8f61e7c.js rel=prefetch>
    <link href=css/app.a2b64800.css rel=preload as=style>
    <link href=js/app.fe175e7f.js rel=preload as=script>
    <link href=js/chunk-vendors.99d4a91b.js rel=preload as=script>
    <link href=css/app.a2b64800.css rel=stylesheet>
</head>

<body>
    <noscript><strong>We're sorry but X doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript>
    <div id=app></div>
    <script src=js/chunk-vendors.99d4a91b.js></script>
    <script src=js/app.fe175e7f.js></script>
</body>

</html>
```

**Comment by cristianvasquez** [comment] 2020-10-10 17:24
for me, baseUrl is not allowed and publicPath is not respected,

**Comment by thefyrewire** [comment] 2020-11-17 17:36
For anyone coming across this in the future, I was able to use `././` to force a `./` path (so I can open the site locally without a server).

```js
module.exports = {
  publicPath: '././'
};
```
```html
<script src="./js/chunk-vendors.82980510.js">
```

**Comment by kusleikar** [comment] 2021-05-01 13:09
@thefyrewire Thanks man, that solved my problem with electron.

**Comment by mgolshan** [comment] 2023-12-17 17:19
In case anyone uses `defineConfig` in the `vue.config.js` file, you may use the `publicPath` argument.
```
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true,
  publicPath: './'
})
```
