### ISSUE TITLE
This is bug?

### ISSUE THREAD

**Issue by TDcloud** [vuejs/vue-cli#4764] opened 2019-10-28 08:29 UTC
### Version
4.0.5

### Reproduction link
[https://ws1.sinaimg.cn/large/d74f4e33gy1g8dzh9lfd2j20it0camy6.jpg](https://ws1.sinaimg.cn/large/d74f4e33gy1g8dzh9lfd2j20it0camy6.jpg)

### Environment info
```
win7,64，vue-cli4.0.5
```

### Steps to reproduce
 System:
   OS: Windows 7
   CPU: (4) x64 Intel(R) Core(TM) i5-2450M CPU
 Binaries:
   Node: 10.16.3 - D:\nodejs\node.EXE
   Yarn: Not Found
   npm: 6.12.0 - D:\nodejs\npm.CMD
 npmPackages:
   @vue/babel-helper-vue-jsx-merge-props:  1.0
   @vue/babel-plugin-transform-vue-jsx:  1.0.0
   @vue/babel-preset-app:  4.0.5
   @vue/babel-preset-jsx:  1.1.1
   @vue/babel-sugar-functional-vue:  1.0.0
   @vue/babel-sugar-inject-h:  1.0.0
   @vue/babel-sugar-v-model:  1.1.1
   @vue/babel-sugar-v-on:  1.1.0
   @vue/cli-overlay:  4.0.5
   @vue/cli-plugin-babel: ^4.0.0 => 4.0.5
   @vue/cli-plugin-router: ^4.0.0 => 4.0.5
   @vue/cli-plugin-vuex:  4.0.5
   @vue/cli-service: ^4.0.0 => 4.0.5
   @vue/cli-shared-utils:  4.0.5
   @vue/component-compiler-utils:  3.0.0
   @vue/preload-webpack-plugin:  1.1.1
   @vue/web-component-wrapper:  1.2.0
   vue: ^2.6.10 => 2.6.10
   vue-hot-reload-api:  2.3.4
   vue-loader:  15.7.1
   vue-router: ^3.1.3 => 3.1.3
   vue-style-loader:  4.1.2
   vue-template-compiler: ^2.6.10 => 2.6.10
   vue-template-es2015-compiler:  1.9.1
 npmGlobalPackages:
   @vue/cli: Not Found

### What is expected?
No real-time trace trigger required check box

### What is actually happening?
Click the check box once to trigger the selection information dynamically, and it will be displayed in the echo. Is there any defect?

**Comment by LinusBorg** [comment] 2019-10-28 08:46
duplicate of #4763

**Closed** 2019-10-28 08:46 UTC
