### ISSUE TITLE
Vue Cli build error

### ISSUE THREAD

**Issue by cherot1k** [vuejs/vue-cli#6329] opened 2021-03-03 09:55 UTC
### Version
4.5.11

### Reproduction link
[https://github.com/cherot1k/shop](https://github.com/cherot1k/shop)

### Environment info
```

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.11
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.10
    @vue/cli-plugin-babel: ^4.5.11 => 4.5.11
    @vue/cli-plugin-pwa: ~4.5.0 => 4.5.10
    @vue/cli-plugin-router: ~4.5.0 => 4.5.10
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.10
    @vue/cli-service: ~4.5.0 => 4.5.10
    @vue/cli-shared-utils:  4.5.10 (4.5.11)
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    vue: ^2.6.11 => 2.6.12
    vue-cli-plugin-vuetify: ~2.0.9 => 2.0.9
    vue-hot-reload-api:  2.3.4
    vue-loader: ^15.9.6 => 15.9.6 (16.1.2)
    vue-router: ^3.2.0 => 3.4.9
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.12 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
    vuetify: ^2.2.11 => 2.4.2
    vuetify-loader: ^1.7.2 => 1.7.2
    vuex: ^3.4.0 => 3.6.0
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
Fixing errors with vue-cli-service build(or command npm run build in project)

### What is expected?
The builded project in the dist folder

### What is actually happening?
Template execution failed: ReferenceError: features is not defined

  ReferenceError: features is not defined

  - index.html:96
    C:/my_projects/shop-e1ef20a42d035b5a08fa043add606f6036d1b736/public/index.html:96:10

  - index.html:99 0971.module.exports
    C:/my_projects/shop-e1ef20a42d035b5a08fa043add606f6036d1b736/public/index.html:99:3

  - index.js:284
    [shop-e1ef20a42d035b5a08fa043add606f6036d1b736]/[html-webpack-plugin]/index.js:284:18

  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5

---
A three days ago i ve builded this project with no errors etc, i didn't changes any webpack config, etc, so i has errors while building

**Comment by sodatea** [comment] 2021-03-03 10:14
Can't reproduce.
Does this StackOverflow question help? https://stackoverflow.com/q/54743760/2302258

**Comment by cherot1k** [comment] 2021-03-03 10:24
No, i ve already deployed it like a 30 times to firebase with no problems

ср, 3 мар. 2021 г., 12:14 Haoqun Jiang <notifications@github.com>:

**Comment by cherot1k** [comment] 2021-03-03 10:30
It is problem not with deploy,but with build the project

ср, 3 мар. 2021 г., 12:24 Kostya Osypenko <lulok2t@gmail.com>:

**Comment by sodatea** [comment] 2021-03-03 11:27
But I can't reproduce the issue locally. Here's my screencast: https://asciinema.org/a/4gkAa4LhZ1CWSJ6r42hd4Qlgf

**Comment by cherot1k** [comment] 2021-03-03 13:39
you should use npm install over npm ci
but i cloned my project from github and it magically works, idk how, so
sorry for wasting your time

ср, 3 мар. 2021 г. в 13:27, Haoqun Jiang <notifications@github.com>:

**Comment by sodatea** [comment] 2021-03-04 10:17
I used `npm ci` to ensure I have the exact same dependencies installed as your environment.

Now that it works again, I'm closing this issue.

**Closed by sodatea** 2021-03-04 10:17 UTC
