### ISSUE TITLE
Doesn't work with survey-vue https://www.npmjs.com/package/survey-vue

### ISSUE THREAD

**Issue by dmitrykurmanov** [vuejs/vue-cli#1889] opened 2018-07-18 09:10 UTC
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/surveyjs/vue_cli-_3_boilerplate](https://github.com/surveyjs/vue_cli-_3_boilerplate)

### Steps to reproduce
just run `npm run serve` and open the console

### What is expected?
console without error

### What is actually happening?
In fact the problem with our main file name survey.vue.js (https://unpkg.com/survey-vue@1.0.33/survey.vue.js)

For example if we rename survey.vue.js to survey-vue.js it will be ok.

---
I am one of SurveyJS contributors. Please look at the original issue reference https://github.com/surveyjs/surveyjs/issues/1223

**Comment by LinusBorg** [comment] 2018-07-18 11:32
Sounds a bit like the webpack alias that we use for `'vue$'` could be the culprit, but on the other hand, I maintain a package called `portal-vue` which doesn't have this problem...

**Comment by dmitrykurmanov** [comment] 2018-07-18 12:36
@LinusBorg yes, I think that the problem only in the dot (".vue")

**Comment by tsv2013** [comment] 2018-07-18 12:45
@LinusBorg the file name `survey-vue.js` is working also, but the problem is with the `survey.vue.js`

**Comment by LinusBorg** [comment] 2018-07-18 20:50
This is a really weird one. I did some debugging as far as I could.

* It's not the alias, I manually added another alias for `survey-vue` before the original `vue$` one but that didn't solve anything
* I also had a suspicion that vue-loader's dynamically added rules were responsible, which rely on `resourceQuery` filtering where it adds a "fake file"  (see [here](https://github.com/vuejs/vue-loader/blob/master/lib/plugin.js#L137)), but then I removed the App.vue entirely and imported SurveyVue into main.js, so those rules won't apply - no more "can't find import Survey..." errors, but  an error about Vue not being found.

Now I'm a bit out of my whits ... /ping @yyx990803

**Comment by yyx990803** [comment] 2018-07-18 21:20
`*.vue.js` is the special file extension used by `vue-loader` to match against `<script>` blocks in `*.vue` files... for now you should just rename it. We can probably work around this in `vue-loader`.

**Comment by kamidev** [comment] 2018-08-08 08:04
Survey-vue has now renamed the main file to 'survey-vue.js', which fixes the reported problem.

However, if "*.vue.js" really is a special file exension (and "off-limits" for non-Vue use), perhaps the documentation should be more clear about this?

**Comment by LinusBorg** [comment] 2018-12-10 13:35
I'm, closing this here as it has to be solved in vue-loader, if anywhere.

**Closed by LinusBorg** 2018-12-10 13:35 UTC
Labels: bug
