### ISSUE TITLE
Task Error [serve, build, lint] Ended with error code 1

### ISSUE THREAD

**Issue by javidrashid** [vuejs/vue-cli#1726] opened 2018-07-01 18:26 UTC
### Version
3.0.0-rc.3

### Reproduction link
[http://no-url](http://no-url)

### Steps to reproduce
Install a node module say node-sass, sass-loader, Everything goes for a toss after that. and any command you run, build, serve or lint, The task fails with the message Task Error [serve, build, lint] Ended with error code 1

### What is expected?
It should work.

### What is actually happening?
The whole setup crashes  and you can't even run the app if you start over.

---
I did some additional debugging and you see it reports missing of the core modules when it happens like;

$ vue-cli-service inspect --mode production
module.js:549
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /path/to/project/node_modules/request-promise-native/lib/rp.js:8:12
    at module.exports (/path/to/project/node_modules/stealthy-require/lib/index.js:62:23)
    at Object.<anonymous> (/path/to/project/node_modules/request-promise-native/lib/rp.js:7:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by LinusBorg** [comment] 2018-07-02 07:18
hI:

Can you provide any more details? "Crate a project and install a npm package" is not enough. At least, I cannot reproduce this behaviour with those instructions.

**Comment by javidrashid** [comment] 2018-07-02 07:44
Did you try installing node-sass and sass-loader. I will see if I can create a sandbox environment to reproduce the issue. In the meantime I have added a couple of screenshots if that helps. I didn't had this issue if I install any other plugin/npm package, only with node-sass and sass-loader.

Screen Shot 1:
<img width="1236" alt="sc_1" src="https://user-images.githubusercontent.com/3892722/42151107-7be98126-7df9-11e8-8411-f9a034856b26.png">


Screen 2:

<img width="342" alt="sc_2" src="https://user-images.githubusercontent.com/3892722/42151132-92f71e78-7df9-11e8-993d-17b115fa15ce.png">

**Comment by LinusBorg** [comment] 2018-07-02 07:49
Oh, so this **is** about the UI? you didn't mention that at all ....

**Comment by javidrashid** [comment] 2018-07-02 07:52
Yes but it would even break the command line setup too. I just added UI screenshots for more clarity.

**Comment by LinusBorg** [comment] 2018-07-02 11:09
In that case, a sandbox would be apprechiated because I can't reproduce this so far.

**Comment by SerbanC** [comment] 2018-07-02 14:24
Having trouble since today with this also. In my case, after wiping node_modules and running `npm i`, I get `Error: Cannot find module 'request'` on both `npm run serve` and `npm run build`.

If needed, I can try to reproduce in a repo.

**Comment by rayfoss** [comment] 2018-07-03 13:48
For those who run into this issue while vue cli crashes on start, while you're following `https://cli.vuejs.org/guide/creating-a-project.html#installation` ... the instructions will currently install 2.9.6, but they are for 3+ `vue create hello-world` isn't a thing in v2.

The giveaway was "echo $?" returning 0

**Comment by Akryum** [comment] 2018-07-03 13:51
> the instructions will currently install 2.9.6

No.

```
npm install -g @vue/cli
# OR
yarn global add @vue/cli
```

This installs `@vue/cli` which is 3.x.
2.x is `vue-cli`.

**Comment by rayfoss** [comment] 2018-07-03 13:58
I just realized that and came to update... vue-cli installs the old... subtle difference I overlooked while not copy pasting... lesson learned :+1:

**Comment by SerbanC** [comment] 2018-07-03 15:21
I created a fresh project using the CLI tool + the same saved Vue app config file and the app ran fine. Turned out it was my `package-lock.json` which was broken somehow, I can't figure out how. After replacing my `package-lock.json` with the one from the fresh project (then re-added all other deps and installed them too), everything seems to work fine again.

node version: 8.11.2
npm version: 6.1.0

contents of my `package.json`:
```
{
  "name": "[redacted]",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test:unit": "vue-cli-service test:unit",
    "docs": "jsdoc -c ./jsdoc.config.json"
  },
  "dependencies": {
    "es6-promise": "^4.2.4",
    "vue": "^2.5.16",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.15",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.15",
    "@vue/cli-plugin-unit-jest": "^3.0.0-beta.15",
    "@vue/cli-service": "^3.0.0-beta.15",
    "@vue/eslint-config-standard": "^3.0.0-rc.3",
    "@vue/test-utils": "^1.0.0-beta.16",
    "axios": "^0.18.0",
    "axios-mock-adapter": "^1.15.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.0.1",
    "jsdoc": "^3.5.5",
    "jsdoc-vuejs": "^2.0.1",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.20",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1",
    "vue-cli-plugin-webpack-bundle-analyzer": "^1.1.1",
    "vue-template-compiler": "^2.5.16"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie < 8"
  ]
}
```

**Comment by revelt** [comment] 2018-07-05 06:08
@javidrashid please update, did you had any luck solving this yet considering the given advice above to wipe `package-lock` and reinstall.
@javidrashid I can't stop wondering, what is the reason to install `node-sass` and `sass-loader` at the first place? CLI offers SASS boilerplate automatically:

![sass](https://user-images.githubusercontent.com/8344688/42305282-222c26fe-8022-11e8-9b6f-bb3a0e3e7142.gif)

**Comment by Akryum** [comment] 2018-07-05 06:20
So it seems it was an issue with your local dev environment. Closing until a reliable way to reproduce is found.

**Closed by Akryum** 2018-07-05 06:20 UTC
Labels: need repro

**Comment by javidrashid** [comment] 2018-07-05 10:44
@revelt : Apologies for the delay, I had already wiped out my client_side code before I could try the instructions of updating package-lock so can't confirm if that solves the issue.
That said, I tried reproducing it again and no luck so @Akryum it is good to close for now.

**Comment by revelt** [comment] 2018-07-05 10:48
good stuff!

**Comment by coolemur** [comment] 2018-07-06 13:37
I have the same issue on my projects with vue ui.

1. Create project.
2. npm install sass-loader --save-dev
3. npm install --save-dev node-sass
4. vue ui task - serve

Result:

Task ... :serve ended with error code 1

**Comment by revelt** [comment] 2018-07-06 13:39
@coolemur are you aware Vue CLI comes with SASS already pre-wired? https://github.com/vuejs/vue-cli/issues/1726#issuecomment-402615919 — I wonder why do you install `sass-loader` and `node-sass`?

**Comment by coolemur** [comment] 2018-07-06 13:41
@revelt 

When I try to use

```
<style lang="scss" scoped>

</style>
```

in my vue ui projects, error is shown that sass-loader is missing. So I assume Vue ui doesn't come with sass pre-wired.

**Comment by revelt** [comment] 2018-07-06 13:43
@coolemur OK, strange. Did you select "Manually select features" > "CSS Preprocessors" in the wizard during init stage?

I set up a blank project yesterday and hacked all evening and today morning in SASS, no problems.

**Comment by coolemur** [comment] 2018-07-06 13:48
@revelt Sorry. I missed a point that I need to Manually select it. Now it works just fine. Thank you.

**Comment by revelt** [comment] 2018-07-06 13:50
@coolemur no probs happy to help
