### ISSUE TITLE
vui ui command results in "Error: EISDIR: illegal operation on a directory, read"

### ISSUE THREAD

**Issue by aryehof** [vuejs/vue-cli#1963] opened 2018-07-27 15:38 UTC
### Version
3.0.0-rc.7

### Node and OS info
Node v10.6.0, NPM v6.1.0, Windows 10

### Steps to reproduce
Upgrade to Vue cli 3.0.0-rc.7 from rc.3.  Run the command > vue ui

### What is expected?
No error - ui displayed

### What is actually happening?
An error is shown in the console, e.g.

λ vue ui
🚀  Starting GUI...
 ERROR  Error: EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:337:20)
    at Object.readFileSync (fs.js:374:19)

...

---
Tried to upgrade to latest RC

**Comment by Akryum** [comment] 2018-07-27 15:40
Please check existing issues first, this one is at the top of the closed issues...
Duplicate of #1961

**Closed by Akryum** 2018-07-27 15:40 UTC
