### ISSUE TITLE
Component importing modernizr breaks mocha unit tests

### ISSUE THREAD

**Issue by nataliaBernarte** [vuejs/vue-cli#1158] opened 2018-04-20 13:52 UTC
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/nataliaBernarte/vue-cli-3-bug](https://github.com/nataliaBernarte/vue-cli-3-bug)

### Steps to reproduce
Run `yarn test`

### What is expected?
Tests are run

### What is actually happening?
Error in ./.modernizrrc.js
  TypeError: requirejs.define is not a function

---
Thought might related to the combination modernizr   jsdom   mocha test
[webpack-modernizr-loader](https://www.npmjs.com/package/webpack-modernizr-loader) package documentation

**Comment by LinusBorg** [comment] 2018-04-24 13:09
Closing since no further feedback was given and the issue is caused by a 3rd party dependency that's not supported by webpack

**Closed by LinusBorg** 2018-04-24 13:09 UTC
