### ISSUE TITLE
GUI: Option to disable "Auto Translate"

### ISSUE THREAD

**Issue by katerlouis** [vuejs/vue-cli#2350] opened 2018-08-24 10:04 UTC
### What problem does this feature solve?
When asking for support it would be great to know what the label originally is saying; development is happening all in English, so why should this tool be in German? I'd really like to choose the language myself or atleast force it to English.

### What does the proposed API look like?
<img width="327" alt="image" src="https://user-images.githubusercontent.com/1983382/44579156-d593d080-a795-11e8-9e95-f361ba2cfe67.png">

Maybe put another button at the bottom right of the screen to toggle autotranslation? Right next to "Übersetzung verbessern" (which means: improve translation) 

Or go a step further and make an option / settings screen for the GUI in general– while looking for a way to disable I really missed a cog icon :D

**Comment by sodatea** [comment] 2018-08-25 12:02
Duplicate of #2151

**Closed by sodatea** 2018-08-25 12:02 UTC
