### ISSUE TITLE
cli-plugin-unit-mocha test coverage support

### ISSUE THREAD

**Issue by jorge-fernandes** [vuejs/vue-cli#3084] opened 2018-12-05 13:08 UTC
### What problem does this feature solve?
Currently is next to impossible to use/configure vue-cli's cli-plugin-unit-mocha with nyc and get some reliable test coverage going. This feature would allow all devs to get out-of-the-box test coverage up and running.

As it stands now, it seems configuring webpack from scratch if easier than use vue-clie 3 out-of-the-box solutions, since everything is way easier and faster beside test coverage, which reverted me back to a pure webpack build.

If it's actually easy to accomplish this, perhaps just a up-to-date doc on how to actually achieve this can be a solution, but for now i can't get nyc to work in combination with vue-cli-service test:unit

### What does the proposed API look like?
Perhaps cli-plugin-unit-mocha should also inject a new command for coverage:

`vue-cli-service test:unit:coverage`

**Comment by sodatea** [comment] 2018-12-06 03:57
Duplicate of https://github.com/vuejs/vue-cli/issues/1363

**Closed by sodatea** 2018-12-06 03:57 UTC
