### ISSUE TITLE
Use tslint-config-prettier for typescript

### ISSUE THREAD

**Issue by alexjoverm** [vuejs/vue-cli#761] opened 2018-02-01 15:52 UTC
### What problem does this feature solve?
Similar to how the new vue-cli 3 has [eslint-config-prettier](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/eslint-config-prettier) in order to use both without conflicts, I think it can be useful to add [tslint-config-prettier](https://github.com/alexjoverm/tslint-config-prettier) to achieve the same thing when using typescript.

### What does the proposed API look like?
It should be transparent to the user as long as it selects typescript and a formatter on the cli questions

**Comment by yyx990803** [comment] 2018-02-01 15:55
Does `tsling-config-prettier` support `--fix` via TSLint? Or does it require the user to setup prettier themselves?

**Comment by alexjoverm** [comment] 2018-02-01 16:13
Right now it disables conflicting rules, so yeah it assumes prettier is already configured. In that way, it works just as [eslint-config-prettier](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/eslint-config-prettier).

**Comment by eladcandroid** [comment] 2018-04-25 19:00
That would be great (TSLint + Prettier option in the CLI)

**Comment by backbone87** [comment] 2018-08-04 07:56
you can simply `npm i -D prettier tslint-plugin-prettier tslint-config-prettier` and setup your tslint.json:
```json
{
  "extends": [
    "tslint-config-prettier"
  ],
  "rulesDirectory": ["tslint-plugin-prettier"],
  "rules": {
    "prettier": true
  }
}
```

the only problem i had with this is that when running `npm run lint` the prettier rule reports alot of consecutive newline errors. (and doesnt seem to be able to autofix...).

the problem is here:
https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-typescript/lib/tslint.js#L46

this pads the extracted script with newlines (see https://www.npmjs.com/package/vue-template-compiler#pad )
while the tslint rule for consecutive newlines is disabled by `npm run lint`, prettier has its own rules.

**Comment by wminshew** [comment] 2018-10-31 18:12
Is there a temporary workaround for this or are you just ignoring those error messages?

**Comment by backbone87** [comment] 2019-01-07 09:39
There is no workaround. There needs to be an option in vue-template-compilers parseComponent to comment out newlines (like vue-parser does) when `lang="ts"` is specified. After that, the option can be used downstream (if not enabled by default).

**Comment by backbone87** [comment] 2019-03-03 19:16
i have opened a PR which fixes script content padding inside the vue-cli tslint command

**Comment by sodatea** [comment] 2020-10-09 08:41
Now that TSLint [is officially deprecated](https://github.com/palantir/tslint/pull/4906/files), TSLint support will be [fully dropped in the next major version](https://github.com/vuejs/vue-cli/pull/5065); as for the current major version, no more bug fixes or features will be implemented except for security reasons. So I'm closing this issue now.

**Closed by sodatea** 2020-10-09 08:41 UTC
Labels: feature request, scope: typescript
