### ISSUE TITLE
CSS extract option is not evaluated in dev mode

### ISSUE THREAD

**Issue by mcacek** [vuejs/vue-cli#1807] opened 2018-07-10 17:11 UTC
### Version
3.0.0-rc.3

### Reproduction link
[https://codesandbox.io/s/18mx8k04xq](https://codesandbox.io/s/18mx8k04xq)

### Steps to reproduce
Create new application: `vue create hello-world` using the default CLI options. Create a vue.config.js in the project root and enable CSS extraction per docs, https://cli.vuejs.org/config/#css-extract. Execute a dev build via `npx vue-cli-service build --mode dev`. Examine the resulting files in the `dist/`.

### What is expected?
CSS should be extracted from JS and placed in *.css files. 

### What is actually happening?
The configuration value `css.extract` is ignored and CSS is not extracted from JS assets.

---
It looks like there is a hard-coded environment check that makes it impossible to use the extract option for CSS. I'm not sure if this is intentional or not. 

https://github.com/vuejs/vue-cli/blob/f5c0f5867378c975b06499ab9582497019f05900/packages/%40vue/cli-service/lib/config/css.js#L24

**Comment by LinusBorg** [comment] 2018-07-10 18:33
Duplicate of #1801

**Closed by LinusBorg** 2018-07-10 18:33 UTC
