### ISSUE TITLE
can  not install vue-cli

### ISSUE THREAD

**Issue by lihua123569** [vuejs/vue-cli#660] opened 2017-11-30 11:26 UTC
Coffeescript has been installed, but there are other problems, as follows
https://user-images.githubusercontent.com/8295524/33428497-0a5b2656-d604-11e7-8845-2c11129fa4d2.png

**Comment by marekchen** [comment] 2017-11-30 11:54
same,want for help @yyx990803

**Comment by ksbaozi** [comment] 2017-11-30 12:31
me too...

**Comment by heiliuer** [comment] 2017-11-30 12:37
me too...

**Comment by SmileStrength** [comment] 2017-11-30 12:37
me too..

**Comment by posva** [comment] 2017-11-30 12:43
Duplicate of #655 
@lihua123569 Please, stop already opening new issues

**Closed by posva** 2017-11-30 12:43 UTC
