### ISSUE TITLE
Standard setup is broken

### ISSUE THREAD

**Issue by wsmarsh** [vuejs/vue-cli#4918] opened 2019-12-02 18:25 UTC
### Version
4.1.1

### Reproduction link
[https://github.com/wsmarsh/test-error](https://github.com/wsmarsh/test-error)

### Environment info
```
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.771.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.1.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.1
    @vue/cli-plugin-babel: ^4.1.0 => 4.1.1
    @vue/cli-plugin-e2e-nightwatch: ^4.1.0 => 4.1.1
    @vue/cli-plugin-router: ^4.1.0 => 4.1.1
    @vue/cli-plugin-typescript: ^4.1.0 => 4.1.1
    @vue/cli-plugin-unit-mocha: ^4.1.0 => 4.1.1
    @vue/cli-plugin-vuex: ^4.1.0 => 4.1.1
    @vue/cli-service: ^4.1.0 => 4.1.1
    @vue/cli-shared-utils:  4.1.1
    @vue/component-compiler-utils:  3.0.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    typescript: ~3.5.3 => 3.5.3
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.0.2 => 7.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.2
    vue-property-decorator: ^8.3.0 => 8.3.0
    vue-router: ^3.1.3 => 3.1.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.2 => 3.1.2
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
This is the standard setup, which is broken from the get-go

Created a project from the Vue UI

npm run serve - broken
npm run test:unit - broken

### What is expected?
Vue CLI sereve and tests should work

### What is actually happening?
running both serve and test:unit via npm causes an error

**Comment by daverodal** [comment] 2019-12-02 18:34
I get this error 

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/xxxx/mobx/vue-ddd/src/main.js: Cannot find module './src/data' (While processing: "/Usersxxxx/mobx/vue-ddd/node_modules/@vue/cli-plugin-babel/preset.js")

what is ./src/data and why does babel want it all the sudden?

**Comment by wsmarsh** [comment] 2019-12-02 18:38
@vue/cli-plugin-babel/preset.js points to module.exports = require('@vue/babel-preset-app')
(https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/index.js)

But I can't see any reference to src/data in there

**Comment by daverodal** [comment] 2019-12-02 18:59
mine may be different
i just do vue create project and take minimum defaults and then run npm run serve

**Comment by daverodal** [comment] 2019-12-02 19:01
sorry i did not run your setup I just did a vue create and got my error

**Comment by f-elix** [comment] 2019-12-02 19:03
Running into this exact same issue with version 4.1.1

**Comment by aljaff94** [comment] 2019-12-02 19:05
when updating packages to last version using ncu -g the problem also happened

**Comment by grahamnordstrom** [comment] 2019-12-02 19:05
Just ran into this as well. The issue is in core-js-compat/helpers.js
Line 3 `const data = require('./src/data');`

The workaround
Should read `const data = require('./data');`

**Comment by aljaff94** [comment] 2019-12-02 19:23
fixed by install this package  
`npm i core-js-compat@3.4.7`

**Closed** 2019-12-03 01:27 UTC
