### ISSUE TITLE
Export with cli-plugin-typescript does not work

### ISSUE THREAD

**Issue by Patcher56** [vuejs/vue-cli#1452] opened 2018-06-03 19:15 UTC
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/Patcher56/vue-flowy/blob/rework/src/main.ts](https://github.com/Patcher56/vue-flowy/blob/rework/src/main.ts)

### Steps to reproduce
1. yarn build: it will build all ts files to js files (everything okay after that)
2. add the plugin into a vue-cli-project (currently done with yarn link)
3. try to import ```import {FlowChart} from 'vue-flowy'```
4. console.log(FlowChart) -> undefined

### What is expected?
FlowChart should be an object

### What is actually happening?
FlowChart is undefined

---
Using latest version of vue-cli.
Working with export default for auto installing on main.js on the App and working with export {FlowChart}  for exporting my components and classes.

**Comment by Patcher56** [comment] 2018-06-03 19:30
Fixed by using the following code:
vue```
import VueFlowy from './VueFlowy.vue'
import { VueConstructor } from 'vue';
import FlowChart from './FlowChart'

const Plugin = {
  VueFlowy,
  FlowChart,
  install (Vue: VueConstructor) {
    Vue.component(VueFlowy.name, VueFlowy)
  }
}

export default Plugin

export { VueFlowy, FlowChart }
```
So I added the component and the class to the Plugin Object. For an unknown reason, the ```export``` without the ```default``` keyword has no effect.

Can be closed if this is the way to go.

**Comment by lossendae** [comment] 2018-06-03 19:56
The export without default are not exported, this is similar to my issue #1436

**Comment by Patcher56** [comment] 2018-06-03 20:07
Oh nice to see that I am not the only one with this problem. I googled an hour long but found not solution except the one above.

Also the watcher for typescript files does not work with vue-cli

**Comment by yyx990803** [comment] 2018-06-03 20:08
I'll close this as a duplicate of #1436

**Closed by yyx990803** 2018-06-03 20:08 UTC
