### ISSUE TITLE
Error: Cannot find module './src/init'

### ISSUE THREAD

**Issue by devnill** [vuejs/vue-cli#199] opened 2016-10-13 22:09 UTC
When trying to run the `vue init` command i'm getting an error referring to a nonexistent node module.

I've pasted the command as run and the output of a couple other relevant commands. I'm running osx 10.12. 

```
$ vue init webpack vue-test
module.js:471
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/vue-cli/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

$ vue list
  Available official templates:

  ★  browserify - A full-featured Browserify + vueify setup with hot-reload, linting & unit testing.
  ★  browserify-simple - A simple Browserify + vueify setup for quick prototyping.
  ★  simple - The simplest possible Vue setup in a single HTML file
  ★  webpack - A full-featured Webpack + vue-loader setup with hot reload, linting, testing & css extraction.
  ★  webpack-simple - A simple Webpack + vue-loader setup for quick prototyping.

$ node --version
v6.8.0

$ npm -v
3.10.8

$ npm ls -g --depth=0
/usr/local/lib
├── http-server@0.9.0
├── npm@3.10.8
├── sqlite@2.2.0
├── vue-cli@2.4.0
└── webpack@2.1.0-beta.25

$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:./node_modules/.bin
```

**Comment by davidenq** [comment] 2016-10-13 22:55
Please see #198

**Comment by posva** [comment] 2016-10-14 07:51
as @davidenq said, duplicate of #198

**Closed by posva** 2016-10-14 07:51 UTC
