### ISSUE TITLE
cli-plugin-pwa uses pwa.name from manifest.json but pwa.themeColor not.

### ISSUE THREAD

**Issue by frederikhors** [vuejs/vue-cli#2629] opened 2018-09-27 09:32 UTC
### Version
3.0.4

### What is expected?
`cli-plugin-pwa` uses in `vue.config.js`:

- `pwa.name` from `/public/manifest.json`;
- `pwa.themeColor` from `/public/manifest.json`.

### What is actually happening?
`cli-plugin-pwa` uses in `vue.config.js`:

- `pwa.name` from `/public/manifest.json` but
- `pwa.themeColor` **not**.

**Why?**

**Comment by LinusBorg** [comment] 2018-09-27 12:43
Welcome back.

Now you opened a bug report, like I asked you to. But you still didn't provide a reproduction, like I asked you to.

Please provide one - it allows us to re-cereate your problem and analyze it.

**Comment by LinusBorg** [comment] 2018-09-27 12:46
Please include a reproduction, I'm still not sure what you mean.

According to the pwa plugin's README, the `pwa.name` is *not* taken from `/publix/manifest.json`, it's taken from package.json unless specified otherwise.

**Comment by Devoter** [comment] 2018-09-28 19:46
I confirm. Plugin doesn't create or update manifest.json anyway.

**Comment by LinusBorg** [comment] 2018-09-28 20:44
Yeah. And it's not claiming to do, so I don't see any problem?

**Comment by Devoter** [comment] 2018-09-28 21:52
Maybe, I have to create a new issue. I'm setting properties like `pwa.name` or `pwa.themeColor` into `vue.config.js`, but after build there is no changes into `dist/manifest.json`: `name` and `themeColor` are not applied.

**Comment by LinusBorg** [comment] 2018-09-28 22:00
Yes, you have to do that yourself.

**Comment by LinusBorg** [comment] 2018-09-29 10:00
Closing since I don't see anything we could fix, and OP doesn't respond.

**Closed by LinusBorg** 2018-09-29 10:00 UTC
Labels: needs reproduction

**Comment by frederikhors** [comment] 2018-09-29 10:09
@LinusBorg I think I not explained myself very well. My concern was about the fact we can retrieve also `pwa.themeColor` from a file. And we should. Avoid repeat multiple times a value.

Nothing is broken. This is a feature request.
