### ISSUE TITLE
Documentation request: how to configure vue-cli to build non `src/App.vue` files so they can be mounted directly in `main.js`

### ISSUE THREAD

**Issue by SumNeuron** [vuejs/vue-cli#4935] opened 2019-12-06 13:38 UTC
### Version
4.1.1

### Reproduction link
[https://gitlab.com/SumNeuron/vuetify-rollup-alcarte](https://gitlab.com/SumNeuron/vuetify-rollup-alcarte)

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.16 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (40) x64 Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz
  Binaries:
    Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
    Yarn: Not Found
    npm: 6.7.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 70.0.1
  npmGlobalPackages:
    @vue/cli: 4.1.1

```

### Steps to reproduce
1. Created empty project repo: `mkdir test && cd test`
2. Created fresh project via `vue-cli`: `vue create dev`
3. Added Vuetify to project: `cd dev && vue add veutify`
4. Pulled config files from `test/dev` up to `test`
5. Updated `vue.config.js` to point to new location:

```js
//vue.config.js
{
//...
pages: {
    index: {
      entry: 'dev/src/main.js',
      template: 'dev/public/index.html',
      filename: 'index.html',
    }
  },
}
```
6. Made a very simple component `CountButton.vue` which is just a wrapper of the Vuetify component `<v-btn>` imported a la carte (see `test/dev/components/CountButton.vue`)
7. tried mounting multiple instances of the component `CountButton` in `dev/src/main.js` e.g. 

```js
// dev/src/main.js
// ...
import CountButton from './components/CountButton.vue'
new Vue({
  store,
  vuetify,
  render: h => h(CountButton)
}).$mount('#app')

new Vue({
  store,
  vuetify,
  render: h => h(CountButton)
}).$mount('#app2') // <--- copy pasted <div id="app"> and gave it new id "app2" in `public/index.html`

```
8. Noticed that direct mounting this way does not work as expected (`CountButton.vue` was mounted and data was reactive in Vue inspector, but not the template)
9. Updated `dev/src/App.vue` to contain just `CountButton.vue` 
10. Tried the multi-mount, and that works.
11. Copy pasted the file `dev/src/App.vue` to `dev/src/App0.vue` and tried mounting the `App0` component. This failed in the same manner as (8) as the `vue-cli` targets `dev/src/App.vue` as the entry point. 
12. Tried to then convert component to a WebComponent by adding the following `package.json`

```json
"build:wc": "npx vue-cli-service build --target wc --name pub 'dev/src/components/*.vue'",
```

13. inspected the resulting `dist/pub.min.js` and `dist/demo.html` files and noticed the component regained its dynamic template - error from (8) - but lost all styling

14. Thought that this may be due to Vuetify styles not being bundled with the the Vuetify component
15. Setup rollup to try and force the CSS to be bundled with the component (see `rollup.config.js`, `dev/src/rollup.entry.js` and `package.json`)
16. then I rolled up `npm run build:r`
17. then I tried to use the component: (`dist/demo.html`)
18. Am back to where I was at step (13); namely, I have WebComponents, but despite bundling `vuetify.min.css` with the `CountButton.vue` component, but no styling.

This belabored process raises two questions:

1. [How to mount multiple components (not App.vue) in main.js from vue-cli3](https://stackoverflow.com/questions/59193172/vue-cli3-mount-multiple-components-in-main-js-that-are-not-app-vue)
2. [How to rollup Vue Components that are built on top of Vuetify.js to keep their styling and functionality outside of <v-app>](https://stackoverflow.com/questions/59158339/vuetify-a-la-carte-rollup-component-complains-when-used-in-static-html-file)

The former is related to `vue-cli`.

ideally I would be able to, in `src/main.js` import my components / subapps and mount them to any divs I point them to in `public/index.html`

### What is expected?
I can mount any component (from `src/components) imported in `main.js` and they will work correctly

### What is actually happening?
Some functionality of the components are lost

---
See repo and long commnets above

**Comment by LinusBorg** [comment] 2019-12-06 14:33
There's nothing special to consider, you *can* mount any component.

I would rather suspect thatyour issue is completely related to Vuetify, but can't take a look at the code right now.

Did you try to mount a non-vuetify component ?

**Comment by sodatea** [comment] 2019-12-08 10:36
Can't reproduce the first issue.
Don't have the time to reproduce the second one.

Please boil down the reproduction to a **minimal** one.

**Comment by SumNeuron** [comment] 2019-12-08 17:56
@sodatea @LinusBorg Yes. To simply things, I created a second, smaller MWE repo as I tried to overcome many problems in the first.

Here is the smaller repo specifically for the first problem: https://gitlab.com/SumNeuron/vue-cli-multi-mount


What did I do?

1. `mkdir vue-cli-multi-mount`
2. `cd vue-cli-multi-mount`
3. `vue create dev`
4. `cd dev`
5. `vue add vuetify`
6. move all config files from `vue-cli-multi-mount/dev` to `vue-cli-multi-mount`
7. updated `vue.config.js` to point to the new location of all components.
8. created 5 test components:
  - `VuetifyBtn`: vbtn used wrapped in div
  - `VuetifyBtnVApp`: `v-btn` used wrapped in `v-app`
  - `VuetifyBtnALaCarte`: `v-btn` imported a la carte, wrapped in div
  - `VuetifyBtnALaCarteVApp`: `v-btn` imported a la carte, wrapped in `v-app`
  - `WrapBtn`: a div over an html button
9. updated public html to have the mount points:
 ```html
<ul>
      <li>
        Vuetify Btn <div id="btn1"></div>
      </li>
      <li>
        Vuetify Btn in VApp <div id="btn2"></div>
      </li>
      <li>
        Vuetify Btn A La Carte <div id="btn3"></div>
      </li>
      <li>
        Vuetify Btn A La Carte in VApp <div id="btn4"></div>
      </li>
      <li>
        Wrapper over normal button <div id="btn5"></div>
      </li>
    </ul>
```
10. updated `main.js` to load components and mount them:

```js
import Vue from 'vue'
// import App from './App.vue'
import VuetifyBtn from './components/VuetifyBtn.vue'
import VuetifyBtnVApp from './components/VuetifyBtnVApp.vue'
import VuetifyBtnALaCarte from './components/VuetifyBtnALaCarte.vue'
import VuetifyBtnALaCarteVApp from './components/VuetifyBtnALaCarteVApp.vue'
import WrapBtn from './components/WrapBtn.vue'
import store from './store'
import vuetify from './plugins/vuetify';

Vue.config.productionTip = false

new Vue({
  store,
  vuetify,
  render: h => h(VuetifyBtn)
}).$mount('#btn1')
new Vue({
  store,
  vuetify,
  render: h => h(VuetifyBtnVApp)
}).$mount('#btn2')
new Vue({
  store,
  vuetify,
  render: h => h(VuetifyBtnALaCarte)
}).$mount('#btn3')
new Vue({
  store,
  vuetify,
  render: h => h(VuetifyBtnALaCarteVApp)
}).$mount('#btn4')
new Vue({
  store,
  vuetify,
  render: h => h(WrapBtn)
}).$mount('#btn5')
```

11. ran `npm run serve` to ensure everything works in dev. All good here
12. ran `npm run build` 
13. opened `dist/index.html` to see 100% disappointment with nothing there.

**Comment by SumNeuron** [comment] 2019-12-08 18:16
To clarify, the issue is for production in that `npm run build` only mounts what is specifically targeted in `App.vue`

@LinusBorg

**Comment by LinusBorg** [comment] 2019-12-09 13:22
> opened dist/index.html to see 100% disappointment with nothing there.

...but that file contains all the mount points and includes the correct javascript file that will mount to those mount points.

So what specifically is your disappointment about?

**Comment by LinusBorg** [comment] 2019-12-09 13:25
Oh, did you doubleclick the `dist/index.html`file and expect that to work? It won't, as we build ith absolute paths by default, which means opening the file via file:// will not work as that requirews relative paths.

so now imports for e.g. the `vendors-hash.js` chunk fail.

**Comment by SumNeuron** [comment] 2019-12-09 14:23
@LinusBorg correct I double clicked what I was hoping to be a static SPA `dist/index.html`. How can I: 

- have it build without absolute paths
- serve `index.html` for production?
- build a static site with the mount points?

**Comment by SumNeuron** [comment] 2019-12-09 14:28
I also just pushed a branch `retool`, which includes a rolluped version, where even the plan `WrapBtn` component is unfunctional complaining of 

```
[Vue warn]: Error in nextTick: "TypeError: this.$root.$options.customElement is undefined"
```

**Comment by LinusBorg** [comment] 2019-12-09 15:15
> which includes a rolluped version,

We will not debug rollup configs here. Vue CLI doesn't use rollup, so this it out of scope for a bug report unless you can show how this is because of something Vue CLI does.

Feel free to ask the community on discord or forum.vuejs.org for help regarding that.



> * have it build without absolute paths

https://cli.vuejs.org/config/#publicpath

> * serve index.html for production?

Explaining how to serve an index.html with a webserver is out of scope for a bug report. There's pleanty of tutorials available online, and our documentation offers deployment guides for various plattforms.

> * build a static site with the mount points?

I don't understand what you mean by that.

**Comment by SumNeuron** [comment] 2019-12-09 17:53
> re rollup
Fair enough. Rollup was included as the webcomponents generated by
```
npx vue-cli-service build --target wc --name pub 'dev/src/components/*.vue'
```
also did not work

> re `publicPath`
That allows local inspection of `index.html` which works as expected. 

> Re serve `index.html`
I understand that explaining how to serve `index.html` with a webserver is out of scope for a bug report but this is a documentation request. Similarly to the vue-cli, nuxt has `npm run dev` (`npm run serve` for vue-cli) and `npm run build` to build the production site. The difference is that nuxt also has `npm run start` to serve the built site, which vue cli does not have by [default](https://cli.vuejs.org/guide/deployment.html#previewing-locally). Perhaps including it in `package.json` would be worth while?

**Comment by LinusBorg** [comment] 2019-12-09 18:39
There's no start command because vue-cli projects are not server-rendered, they are entirely client-side.

**Comment by LinusBorg** [comment] 2019-12-13 12:01
So I'll close this issue as the original problem was ansered with a relative public path.

You also mentioned something about web components but I don't see how that directly relates. So if this is a separate problem you are encountering, please open a new issue for that problem alone.

**Closed by LinusBorg** 2019-12-13 12:01 UTC
Labels: needs reproduction

**Comment by frog-o** [comment] 2022-03-29 09:51
@LinusBorg ,
you said
>So I'll close this issue as the original problem was ansered with a relative public path.

 I am confused this thread ask for documentation can you explain why a relative path fixes that problem? 

I am have the same problem trying to figure out how the build system works, I been trying to ssr with 
[vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) which I think , breaks  "vue cli". 

you said 
> Vue CLI doesn't use rollup, 

It look to me that "vue cli" expect to use webpack but vite want to use roll-up.**I often wounder why "vue cli" doesn't use vite.**

I been asking for documention on the build and using of "vue cli"  on  vite  and vite-plugin-ssr,  so far with out much help.  I been trying to figure out how all the pieces go together.  I like read documentations that you have but sadly I have not been able to figure it out. **I been fight this for weeks now.**

I coming to the conclusion  that even though Vite and vue( I thought where made by the same person)  They where not meant to work together with the "vue cli".  There no documentation that I could find for that.   All vue documentation seem to use "vue cli" tool making the "vuejs" documentations almost worthless without **info for the build and use of  ssr**.

**Comment by LinusBorg** [comment] 2022-03-29 11:15
It fixes the original issue ok insof as r as it uses Vitey which uses roll-up.

You seem to want to propose a whole architecture for spring multiple build systems, which sounds cool but likely will not make it into create-vue due to the insane complexity
