### ISSUE TITLE
page tasks empty in French language 

### ISSUE THREAD

**Issue by HarolDeuh** [vuejs/vue-cli#3701] opened 2019-03-25 00:10 UTC
### Version
3.5.1

### Environment info
```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: Not Found
    Safari: 12.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.5.1 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.5.1 
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.1 
    @vue/cli-plugin-eslint: ^3.5.0 => 3.5.1 
    @vue/cli-service: ^3.5.0 => 3.5.1 
    @vue/cli-shared-utils:  3.5.1 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue:  4.7.1 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-style-loader:  4.1.2 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
I've create a project with vue CLI 3 and the task page in dashboard is empty 

### What is expected?
Launch multiple tasks 

### What is actually happening?
Nothing

**Comment by bulletmark** [comment] 2019-03-29 01:55
Nothing to with your language. This is generic issue #3664. Create a project using `vue ui` and you get that issue and a blank tasks page. Create a project manually using `vue create` then view it in UI and you will see the tasks page populated correctly.

**Comment by bulletmark** [comment] 2019-05-02 04:28
As I said above, this is just a duplicate of issue #3664 which was fixed and closed about a month ago so this bug should be closed as well.

**Closed** 2019-05-02 10:02 UTC
Labels: feat: ui
