### ISSUE TITLE
npm run serve error: You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2

### ISSUE THREAD

**Issue by scliuyang** [vuejs/vue-cli#1162] opened 2018-04-23 03:12 UTC
### Version
3.0.0-beta.6

### Reproduction link
[https://codepen.io/](https://codepen.io/)

### Steps to reproduce
- Vue CLI v3.0.0-beta.6
- ? Please pick a preset: Manually select features
- ? Check the features needed for your project: TS, Router, Vuex, CSS Pre-processors, Linter
- ? Use class-style component syntax? Yes
- ? Use Babel alongside TypeScript for auto-detected polyfills? Yes
- ? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): LESS
- ? Pick a linter / formatter config: Airbnb
- ? Pick additional lint features:
- ? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
- ? Save this as a preset for future projects? No

vue-cli will install @babel/preset-stage-2@7.0.0-beta.45 and npm run serve will throw error:

`The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2`

see:  https://github.com/babel/babel/blob/master/packages/babel-preset-stage-2/src/index.js#L29

forgive my poor English

### What is expected?
server success

### What is actually happening?
The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2

**Comment by dzza** [comment] 2018-04-23 04:05
Same. On a fresh install:

```
>yarn serve
yarn run v1.5.1
$ vue-cli-service serve --open
 INFO  Starting development server...
 94% asset optimization

 ERROR  Failed to compile with 1 errors                                                                                                         23:59:26

 error  in ./src/main.js

Module build failed: Error: [BABEL] /Users/dzza/multiselect/src/main.js: The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2 (While processing: "/Users/dzza/multiselect/node_modules/@vue/babel-preset-app/index.js$1")
    at /Users/dzza/multiselect/node_modules/@babel/preset-stage-2/lib/index.js:107:11
    at /Users/dzza/multiselect/node_modules/@babel/helper-plugin-utils/lib/index.js:18:12
    at /Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:172:14
    at cachedFunction (/Users/dzza/multiselect/node_modules/@babel/core/lib/config/caching.js:42:17)
    at loadPresetDescriptor (/Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:243:63)
    at /Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:68:19
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:66:36)
    at recurseDescriptors (/Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:97:26)
    at loadFullConfig (/Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:112:6)

 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js
```

package.json

```
{
  "name": "servicevue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve --open",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "d3-hierarchy": "^1.1.5",
    "es6-tween": "^5.1.0",
    "faker": "^4.1.0",
    "panzoom": "^4.4.0",
    "svg-pan-zoom": "^3.5.3",
    "validator": "^9.4.1",
    "vue": "^2.5.13",
    "vue-resource": "^1.3.6",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.6",
    "@vue/cli-service": "^3.0.0-beta.6",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "sass-resources-loader": "^1.3.3",
    "vue-template-compiler": "^2.5.13"
  },
  "babel": {
    "presets": [
      "@vue/app"
    ]
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

```

**Comment by dzza** [comment] 2018-04-23 04:06
Same. On a fresh install:

```
>yarn serve
yarn run v1.5.1
$ vue-cli-service serve --open
 INFO  Starting development server...
 94% asset optimization

 ERROR  Failed to compile with 1 errors                                                                                                         23:59:26

 error  in ./src/main.js

Module build failed: Error: [BABEL] /Users/dzza/multiselect/src/main.js: The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2 (While processing: "/Users/dzza/multiselect/node_modules/@vue/babel-preset-app/index.js$1")
    at /Users/dzza/multiselect/node_modules/@babel/preset-stage-2/lib/index.js:107:11
    at /Users/dzza/multiselect/node_modules/@babel/helper-plugin-utils/lib/index.js:18:12
    at /Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:172:14
    at cachedFunction (/Users/dzza/multiselect/node_modules/@babel/core/lib/config/caching.js:42:17)
    at loadPresetDescriptor (/Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:243:63)
    at /Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:68:19
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:66:36)
    at recurseDescriptors (/Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:97:26)
    at loadFullConfig (/Users/dzza/multiselect/node_modules/@babel/core/lib/config/full.js:112:6)

 @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js
```

package.json

```
{
  "name": "multiselect",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve --open",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "vue": "^2.5.13"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.6",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.6",
    "@vue/cli-service": "^3.0.0-beta.6",
    "@vue/eslint-config-prettier": "^3.0.0-beta.6",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "vue-template-compiler": "^2.5.13"
  },
  "babel": {
    "presets": [
      "@vue/app"
    ]
  },
  "eslintConfig": {
    "root": true,
    "extends": [
      "plugin:vue/essential",
      "@vue/prettier"
    ]
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

**Comment by chenKuer** [comment] 2018-04-23 05:38
I get the same error, is there any solution?

**Comment by nusr** [comment] 2018-04-23 05:42
me to

**Comment by soft903** [comment] 2018-04-23 05:45
As babel added "decoratorsLegacy" to presets few days ago
https://github.com/babel/babel/commit/2679d6775cc957e6cc77f23da0e31cd24bbfd18f

I changed vue/babel-preset-app/index.js
`  const envOptions = {
    modules: options.modules || false,
    targets: options.targets,
    useBuiltIns: typeof options.useBuiltIns === 'undefined' ? 'usage' : options.useBuiltIns,
  }`
added decoratorsLegacy
`  const envOptions = {
    modules: options.modules || false,
    targets: options.targets,
    useBuiltIns: typeof options.useBuiltIns === 'undefined' ? 'usage' : options.useBuiltIns,
    decoratorsLegacy: options.decoratorsLegacy || false
  }`
It works, not sure whether it is best way though

**Comment by soft903** [comment] 2018-04-23 06:10
missed another part need to change
line number : 40 
set decoratorsLegacy to true
```
 presets.push([require('@babel/preset-stage-2'), {
    useBuiltIns: true,
    decoratorsLegacy: true
  }])
```

**Comment by chenKuer** [comment] 2018-04-23 06:17
I used the vue-cli, and I don't have the file locally, the sample code of in the package-lock.json is as following:
`"dependencies": {
    "@babel/code-frame": {
      "version": "7.0.0-beta.42",
      "resolved": "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.0.0-beta.42.tgz",
      "integrity": "sha512-L8i94FLSyaLQpRfDo/qqSm8Ndb44zMtXParXo0MebJICG1zoCCL4+GkzUOlB4BNTRSXXQdb3feam/qw7bKPipQ==",
      "dev": true,
      "requires": {
        "@babel/highlight": "7.0.0-beta.42"
      }
    },
    "@babel/core": {
      "version": "7.0.0-beta.42",
      "resolved": "https://registry.npmjs.org/@babel/core/-/core-7.0.0-beta.42.tgz",
      "integrity": "sha512-jcjZRewF/xqROfbk8EGyWlykaIR3IwrcefjWHu8xh4QnULSv3nfkjPM35v1itDgAT4/Jj5b4mPf4eZSC2HoRQA==",
      "dev": true,
      "requires": {
        "@babel/code-frame": "7.0.0-beta.42",
        "@babel/generator": "7.0.0-beta.42",
        "@babel/helpers": "7.0.0-beta.42",
        "@babel/template": "7.0.0-beta.42",
        "@babel/traverse": "7.0.0-beta.42",
        "@babel/types": "7.0.0-beta.42",
        "babylon": "7.0.0-beta.42",
        "convert-source-map": "1.5.1",
        "debug": "3.1.0",
        "json5": "0.5.1",
        "lodash": "4.17.5",
        "micromatch": "2.3.11",
        "resolve": "1.5.0",
        "semver": "5.5.0",
        "source-map": "0.5.7"
      }
    },
    "@babel/generator": {
      "version": "7.0.0-beta.42",
      "resolved": "https://registry.npmjs.org/@babel/generator/-/generator-7.0.0-beta.42.tgz",
      "integrity": "sha512-9x3zS4nG/6GAvJWB8fAK+5g/Di36xdubB43dMNSucNJTwPvmyfCippir/0I8zyG+ID66hLCLi8V9bomlWRYaHA==",
      "dev": true,
      "requires": {
        "@babel/types": "7.0.0-beta.42",
        "jsesc": "2.5.1",
        "lodash": "4.17.5",
        "source-map": "0.5.7",
        "trim-right": "1.0.1"
      }
    },
    "@babel/helper-annotate-as-pure": {
      "version": "7.0.0-beta.42",
      "resolved": "https://registry.npmjs.org/@babel/helper-annotate-as-pure/-/helper-annotate-as-pure-7.0.0-beta.42.tgz",
      "integrity": "sha512-2lmcB7mHRSXZjDV9fdnWGRco+5fbI0PdUtsL7mNA2GtJs0GPoKdV3sCx0N4cpzG2YRR4dNCiB2riYIrzWjmQ1Q==",
      "dev": true,
      "requires": {
        "@babel/types": "7.0.0-beta.42"
      }
    },`

Could you tell me what is the reason that I can run the command yarn build  --mode production on some computer, but at the serve it show 
`Module build failed: Error:[BABEL] : The new decorators proposal is not supported yet. You must pass the "decoratorsLegacy": true option to`

**Comment by koen-chen** [comment] 2018-04-23 07:30
got the same error！

**Comment by soft903** [comment] 2018-04-23 07:42
My working file of node_moudles/@vue/babel-peset-app/index.js

```const path = require('path')

module.exports = (context, options = {}) => {
  const presets = []
  const plugins = []

  // JSX
  if (options.jsx !== false) {
    plugins.push(
      require('@babel/plugin-syntax-jsx'),
      require('babel-plugin-transform-vue-jsx')
      // require('babel-plugin-jsx-event-modifiers'),
      // require('babel-plugin-jsx-v-model')
    )
  }

  const envOptions = {
    modules: options.modules || false,
    targets: options.targets,
    useBuiltIns: typeof options.useBuiltIns === 'undefined' ? 'usage' : options.useBuiltIns,
    decoratorsLegacy: options.decoratorsLegacy || false
  }
  delete envOptions.jsx
  // target running node version (this is set by unit testing plugins)
  if (process.env.VUE_CLI_BABEL_TARGET_NODE) {
    envOptions.targets = { node: 'current' }
  }
  // cli-plugin-jest sets this to true because Jest runs without bundling
  if (process.env.VUE_CLI_BABEL_TRANSPILE_MODULES) {
    envOptions.modules = 'commonjs'
    // necessary for dynamic import to work in tests
    plugins.push(require('babel-plugin-dynamic-import-node'))
  }

  // pass options along to babel-preset-env
  presets.push([require('@babel/preset-env'), envOptions])

  // stage 2. This includes some important transforms, e.g. dynamic import
  // and rest object spread.
  presets.push([require('@babel/preset-stage-2'), {
    useBuiltIns: true,
    decoratorsLegacy: true
  }])

  // transform runtime, but only for helpers
  plugins.push([require('@babel/plugin-transform-runtime'), {
    polyfill: false,
    regenerator: false,
    moduleName: path.dirname(require.resolve('@babel/runtime/package.json'))
  }])

  return {
    presets,
    plugins
  }
}
```

added line 21: 
decoratorsLegacy: options.decoratorsLegacy || false
and line 42 : 
decoratorsLegacy: true

**Comment by zhuweiyou** [comment] 2018-04-23 08:30
same error

**Comment by PedroGao** [comment] 2018-04-23 08:32
me too

**Comment by designbuedchen** [comment] 2018-04-23 08:52
Me too. Needs urgent fix!

**Comment by zhangwei900808** [comment] 2018-04-23 08:53
坐等修复

**Comment by yozman** [comment] 2018-04-23 10:52
the same problem

**Comment by light24bulbs** [comment] 2018-04-23 20:17
While those PR changes are discussed `vue create` is broken for the entire community, and I'd expect some existing projects are broken if they lose their lockfile as well. 

Maybe there should a hard lock onto the previous beta version of babel rather than a `^` to prevent this from happening again

**Comment by light24bulbs** [comment] 2018-04-23 20:36
Confirmed, just talked to the babel maintainers who say that you should absolutely version lock your babel betas.  
https://github.com/babel/babel/commit/2679d6775cc957e6cc77f23da0e31cd24bbfd18f

> 
@light24bulbs Since Babel 7 is still a prerelease beta, we're free to make breaking changes between versions. If you're using 7.x, you should be using one specific version of it.

**Comment by hzoo** [comment] 2018-04-23 20:46
Really sorry this happened!

We aren't in RC yet and there has been a few things we wanted to change before doing so. Unfortunately, this means that a project that is using `^` would pick up the latest beta. And this isn't specific to this release or even this project since at some point you might hit an intentional breaking change. The internal packages are also exact versions as well; this can be an issue in a monorepo.

Not really sure a better way to be able to talk/enforce this on our side. I think we've said this per release, but it hasn't broken in such an obvious way for people before?

Here's Babel's own deps for Babel https://github.com/babel/babel/blob/3a2aa9b86284957533d01105754044fb6b235d41/package.json#L13-L15.

**Comment by yozman** [comment] 2018-04-24 03:59
wish u guys fix it

**Comment by nitta-honoka** [comment] 2018-04-24 04:00
I had solved the problem by using a custom config by `@babel/preset-env` in file .babelrc. Working well, like this:

``` json
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": [
          "> 5%",
          "last 2 versions",
          "not ie <= 8"
        ]
      },
      "modules": false,
      "exclude": [
        "transform-regenerator"
      ]
    }],
    ["@babel/preset-stage-2", {
      "useBuiltIns": true,
      "decoratorsLegacy": true
    }]
  ],
  "plugins": [
  ]
}
```

**Comment by ftgibran** [comment] 2018-04-24 04:07
Guys while this issue is not fixed, simply use this temporary solution: 
Specify the old version of `@babel/preset-stage-2` in `devDependencies`
```
"devDependencies": {
  "@babel/preset-stage-2": "7.0.0-beta.44",
  ...
}
```

**Comment by Chatles** [comment] 2018-04-24 06:09
Waiting!

**Comment by Pymous** [comment] 2018-04-24 08:01
Waiting for what ? It's a beta of vue-cli, and multiple way to fix the issue has been given, just use them ?

**Comment by Hugale12** [comment] 2018-04-24 08:03
No one works for me @Pymous .

**Comment by Hugale12** [comment] 2018-04-24 08:13
`  "devDependencies": {  
    "@babel/preset-stage-2": "7.0.0-beta.44",
    "@vue/cli-plugin-babel": "^3.0.0-beta.6",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.6",
    "@vue/cli-plugin-pwa": "^3.0.0-beta.6",
    "@vue/cli-plugin-unit-jest": "^3.0.0-beta.6",
    "@vue/cli-service": "latest",
    "@vue/eslint-config-airbnb": "^3.0.0-beta.6",
    "@vue/test-utils": "^1.0.0-beta.14",
    "autoprefixer": "^8.3.0",
    "babel-core": "^7.0.0-0",
    "babel-eslint": "^8.2.3",
    "babel-jest": "^22.0.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "eslint": "^4.19.1",
    "less": "^2.7.3",
    "less-loader": "^4.0.5",
    "lint-staged": "^6.0.0",
    "postcss-import": "^11.1.0",
    "postcss-preset-env": "^3.2.2",
    "vue-svgicon": "^2.1.3",
    "vue-template-compiler": "^2.5.13"`  I have that for the moment maybe change another thing ?

**Comment by Pymous** [comment] 2018-04-24 08:29
I don't have any error with your dependancies on a clean folder. Try clearing your `node_modules` folder ? You might have installed a package which is conflicting with the script and not saved it to your `package.json`

**Comment by Hoofoo-WHU** [comment] 2018-04-24 13:45
You can slove this problem by configuring `.babelrc` like this.
PS: `@babel/preset-stage-2` must be configured before `@vue/app`
```json
{
  "presets": [
    [
      "@babel/preset-stage-2", 
      {
        "decoratorsLegacy": true
      }
    ],
    "@vue/app"
  ]
}
```

**Comment by axtho** [comment] 2018-04-24 13:58
adding to `.babelrc` is not helping. The same is for just using the fixed version of `preset-stage-2`, and both in combination. Hopefully the next beta will be out soon and this issue addressed as well. Hacking the code in `node_modules/` is no solution.

Waiting for https://github.com/vuejs/vue-cli/pull/1163 to merged.

**Comment by Hugale12** [comment] 2018-04-24 14:52
One of my colleague have this error ... Mine is resolve

`error  in ./src/App.vue
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null`

**Comment by droidenator** [comment] 2018-04-25 01:25
https://github.com/vuejs/vue-cli/issues/1162#issuecomment-383797149 worked for me. 

Just to clarify, you'll want to add this the `@babel/preset-stage-2` line in your `package.json` sitting in the root of your project. There is **not** currently an entry for that package in there and that threw me off. Don't forget to run `npm install` after you update `package.json`

**Comment by kimse310** [comment] 2018-04-25 05:25
I solved this problem. 
npm install --save-dev babel-preset-stage-2

**Comment by tony19** [comment] 2018-04-25 07:11
Installing `babel-preset-stage-2@7.0.0-beta.44` per https://github.com/vuejs/vue-cli/issues/1162#issuecomment-383797149 did **not** resolve the error for me. The suggestion in https://github.com/vuejs/vue-cli/issues/1162#issuecomment-383796325 actually worked, but I discovered a different solution that modifies the `@vue/app` preset to include the required `decoratorsLegacy` setting:

 1. Delete `.babelrc` (which only contains a config to use the `@vue/app` preset).
 2. Create `.babelrc.js` with the following code:

```javascript
const vueBabelPreset = require('@vue/babel-preset-app');

module.exports = (context, options = {}) => {
  // Cache the returned value forever and don't call this function again.
  context.cache(true);

  const {presets, plugins} = vueBabelPreset(context, options);

  // Find @babel/preset-stage-2, and update its config to enable `decoratorsLegacy`.
  const presetStage2 = require('@babel/preset-stage-2');
  const preset = presets.find(p => p[0] === presetStage2);
  if (preset) {
    preset[1].decoratorsLegacy = true;
  }

  return {
    presets,
    plugins
  };
}
```

**Comment by bdiz** [comment] 2018-04-25 12:05
I think I tried most if not all of the suggestions thus far. Only thing that worked for me was this [comment](https://github.com/vuejs/vue-cli/issues/1162#issuecomment-383796325). Thanks @nitta-honoka

**Closed** 2018-04-25 14:19 UTC

**Comment by stephanepericat** [comment] 2018-04-25 14:51
i just found out that removing the babel entry in package.json also solves the issue.

**Comment by QuantumInformation** [comment] 2018-04-26 06:25
"@babel/preset-stage-2": "7.0.0-beta.44"

 didn't work for me

**Comment by axtho** [comment] 2018-04-26 06:26
there is a new cli version published (beta7) that fixes this issue. This issue can be closed now.

**Comment by QuantumInformation** [comment] 2018-04-26 06:46
I'm using beta7 and still had the issue, until I reinstalled node mods
