### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by pingmouren** [vuejs/vue-cli#3618] opened 2019-03-12 04:54 UTC
### Version
3.5.0

### Reproduction link
[https://cli.vuejs.org/zh/guide/cli-service.html](https://cli.vuejs.org/zh/guide/cli-service.html)

### Environment info
```
win 7
```

### Steps to reproduce
The newly created project is incompatible with IE11 and reports an error in the referenced package

'SCRIPT1002: 语法错误'

### What is expected?
Run successfully

### What is actually happening?
Run failure

**Comment by LinusBorg** [comment] 2019-03-12 07:47
Seems like a duplicate of #3616

**Closed** 2019-03-12 07:50 UTC

**Comment by sodatea** [comment] 2019-03-12 08:07
3.5.1 released, please check if it has fixed this issue
