### ISSUE TITLE
 node 8.1.0 upgrade issue

### ISSUE THREAD

**Issue by RezaHaidari** [vuejs/vue-cli#482] opened 2017-06-08 15:12 UTC
I've upgrade node version, from 8.0.0 to 8.1.0, when i want run vue cli (many projects), command line freeze on "Project description" step ,  but when downgraded node to 8.0.0 it's works!

windows 10
node 8.1.0
vue-cli 2.8.2

![123456](https://user-images.githubusercontent.com/12013210/26935870-5bc49844-4c82-11e7-91b8-d672b5a43335.PNG)

**Comment by piyushchauhan2011** [comment] 2017-06-09 03:40
Yeah true happening after upgrade

**Comment by piyushchauhan2011** [comment] 2017-06-09 04:12
Good idea to upgrade again, as something changed and it's working now @RezaHaidari

**Comment by dzift** [comment] 2017-06-09 08:52
Experiencing the same issue with Node 8.1.0 on Linux Mint 18.2 (kernel 4.8)

**Comment by piyushchauhan2011** [comment] 2017-06-09 09:48
Hmm @dzift , on osx `brew` version `8.1.0_1` is pushed that somehow fixed  the problem, don't know what's changed ~!

**Comment by LucaDev** [comment] 2017-06-10 11:30
Still experiencing the problem on Arch. Any ideas for a workaround?

**Comment by arifunlu** [comment] 2017-06-11 02:31
It's still going on.

**Comment by dzift** [comment] 2017-06-11 07:02
For now we can just clone the template repo, edit package.json and `npm install`.

**Comment by elgrafico** [comment] 2017-06-12 11:08
Node regression, see https://github.com/nodejs/node/pull/13560
Ought to be fixed with node 8.1.1, scheduled for June 13th 2017 https://github.com/nodejs/node/issues/13557#issuecomment-307565799

**Comment by posva** [comment] 2017-06-12 12:26
Thanks a lot for letting us know @elgrafico 
Closing since it's a node bug. Hold on to node 8 until tomorrow 😄

**Closed by posva** 2017-06-12 12:26 UTC
