### ISSUE TITLE
npm install of @vue/cli-ui@^3.1.1 fails with Couldn't find package \"@akryum/winattr@^3.0.0\"

### ISSUE THREAD

**Issue by damoeb** [vuejs/vue-cli#2915] opened 2018-11-07 21:13 UTC
### Version
3.1.1

### Node and OS info
node v10.12.0 / npm 6.4.1 / yarn 1.5.1

### Steps to reproduce
Run npm install -g @vue/cli and see it failing with the error 
> 404 Not Found: @akryum/winattr@^3.0.0

Same for yarn.
> Couldn't find package \"@akryum/winattr@^3.0.0\" required by \"@vue/cli-ui@^3.1.1\"

### What is expected?
cli gets installed

### What is actually happening?
installation fails with the

**Comment by CaiPeng1989** [comment] 2018-11-08 01:10
I think there is a problem with your npm package installation source, you can try to switch sources by `nrm` or `yrm`.

**Comment by JaZo** [comment] 2018-11-08 14:18
Duplicate of #2220

**Comment by segersrobbert** [comment] 2018-11-09 23:00
running `npm install -g @vue/cli` 
& running `npm install --registry=https://registry.npmjs.com/ -g @vue/cli` both result in:

> Couldn't find package "@akryum/winattr@^3.0.0"

Running `npm config get registry` returns `https://registry.npmjs.com/`
Got a local `.npmrc` file which contains `registry=https://registry.npmjs.com/`
Running `yarn config` returns config objects for yarn & npm, both set to their default registries (https://registry.yarnpkg.com & https://registry.npmjs.com/)

**Comment by sodatea** [comment] 2018-12-14 16:59
Closing as there's no actionable item here.

**Closed by sodatea** 2018-12-14 16:59 UTC

**Comment by MannyDiera** [comment] 2019-04-03 05:16
@sodatea why is this closed? I have the same issue and after uninstalling and reinstalling node it still does not work. Love Vue but can't find an answer anywhere on why this is happening.

**Comment by sodatea** [comment] 2019-04-03 05:54
@MannyDiera A possible workaround is to remove `~/.npmrc` and try again. Though, it is not a Vue CLI issue - it's more of an npm issue. There's nothing we can do here.

**Comment by MannyDiera** [comment] 2019-04-03 21:26
@sodatea Thanks for the tip! This was driving me nuts, I had uninstalled node and the Vue CLI twice and still couldn't get it to work. 
For anyone encountering this issue, the key was to delete the ~/.npmrc file and then you should be able to install npm packages again.
