### ISSUE TITLE
 Node15 Stay on DONE  Build complete. The dist directory is ready to be deployed.

### ISSUE THREAD

**Issue by DreamPWJ** [vuejs/vue-cli#6326] opened 2021-03-02 02:38 UTC
### Version
4.2.1

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  Binaries:
    Node: 15.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @ant-design/icons-vue:  2.0.0
    @tinymce/tinymce-vue: 3.0.1 => 2.1.0
    @vue/babel-preset-app:  3.2.0
    @vue/cli-overlay:  3.2.0
    @vue/cli-plugin-babel: 3.2.0 => 3.2.0
    @vue/cli-plugin-eslint: 3.2.0 => 3.2.1
    @vue/cli-service: 3.2.0 => 3.2.0
    @vue/cli-shared-utils:  3.2.0
    @vue/component-compiler-utils:  2.3.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    ant-design-vue: 1.5.0 => 1.6.1
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: 6.2.2 => 5.0.0 (4.7.1)
    viser-vue: 2.4.2 => 2.4.2
    vue: 2.5.17 => 2.5.19 (2.6.11)
    vue-cropper: 0.4.4 => 0.4.6
    vue-eslint-parser:  2.0.3 (4.0.3)
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.4.2
    vue-ls: 3.2.0 => 3.2.0
    vue-print-nb: 1.5.0 => 1.5.0
    vue-qr: 2.2.1 => 2.2.1
    vue-ref:  2.0.0
    vue-router: 3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: 2.5.17 => 2.5.19
    vue-template-es2015-compiler:  1.6.0
    vuex: 3.0.1 => 3.0.1
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
1.  npm run build

### What is expected?
Continue executing the CI code

### What is actually happening?
Staying still on this line does not report an error

**Comment by DreamPWJ** [comment] 2021-03-02 02:44
![image](https://user-images.githubusercontent.com/16730031/109588779-45902800-7b44-11eb-9e9d-216aaef2937b.png)

**Comment by sodatea** [comment] 2021-03-02 05:27
1. Please provide a runnable reproduction
2. Your dependencies are too outdated. These may be bugs that were already fixed in previous releases. Please upgrade to at least `@vue/cli-*` v3.12. v4 would be better if you can.

**Comment by sodatea** [comment] 2021-05-08 11:09
Closing due to inactivity. Please open a new issue with a reference to this one if you can follow up with more information.

**Closed by sodatea** 2021-05-08 11:09 UTC
Labels: needs reproduction

**Comment by rizypb** [comment] 2022-01-18 16:57
Check your npm packages first. In my case it was `vue-cli-plugin-webpack-bundle-analyzer` which was causing issue when I was running the development build command:
`vue-cli-service build --mode development`
I uninstalled this specific npm package and the above command worked fine.

**Comment by dev069** [comment] 2022-02-11 13:02
> Check your npm packages first. In my case it was `vue-cli-plugin-webpack-bundle-analyzer` which was causing issue when I was running the development build command: `vue-cli-service build --mode development` I uninstalled this specific npm package and the above command worked fine.

Thanx, this helped me
