### ISSUE TITLE
Component is missing template or render function while install by npm (not pnpm)

### ISSUE THREAD

**Issue by zhaozhongyu** [vuejs/vue-cli#6754] opened 2021-10-14 12:31 UTC
### Version
5.0.0-beta.6

### Environment info
```
node v14
```

### Steps to reproduce
1. vue create demo 
2. select `recommand ([Vue 3] dart-sass, babel, typescript, router, vuex, eslint, unit-jest) `
3. delete node_modules 
4. npm i
5. npm run serve

### What is expected?
demo work

### What is actually happening?
Component is missing template or render function

**Comment by sodatea** [comment] 2021-10-14 13:19
Can't reproduce. Please provide a reproduction.

**Comment by zhaozhongyu** [comment] 2021-10-14 13:39
https://github.com/iBelieveLove/micropage
```
{
  "name": "demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^3.0.0",
    "vue-class-component": "^8.0.0-0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@types/jest": "^24.0.19",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vue/test-utils": "^2.0.0-0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.0.0",
    "prettier": "^2.2.1",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "typescript": "~4.1.5",
    "vue-jest": "^5.0.0-0"
  }
}
```

**Comment by sodatea** [comment] 2021-10-30 06:14
Closing due to lack of reproduction.

**Closed by sodatea** 2021-10-30 06:14 UTC
Labels: needs reproduction

**Comment by byq1213** [comment] 2021-11-02 10:53
update vue version to ^3.2.21
