### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by focussing** [vuejs/vue-cli#2101] opened 2018-08-07 15:54 UTC
### Version
3.0.0-rc.10

### Node and OS info
npm 8.9.1 / macOS High Sierra

### Steps to reproduce
On the commandline: vue create projectname

### What is expected?
Creation of new project without errors

### What is actually happening?
The following error occurs;

Vue CLI v3.0.0-rc.10
✨  Creating project in /Users/raymond/stack/sites/xml.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/cli-service@^3.0.0-rc.11
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'xml'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raymond/.npm/_logs/2018-08-07T15_37_42_868Z-debug.log
 ERROR  command failed: npm install --loglevel error

---
First I wanted to create a new project using Vue CLI3 UI but that did not work as well...

**Comment by Akryum** [comment] 2018-08-07 15:58
Duplicate of #2100

**Closed by Akryum** 2018-08-07 15:58 UTC

**Comment by focussing** [comment] 2018-08-07 16:00
Beaten by 10 minutes... :)

**Comment by focussing** [comment] 2018-08-07 17:28
It works again, good job!!
