### ISSUE TITLE
Lint errors are not showing when serving

### ISSUE THREAD

**Issue by Rolanddoda** [vuejs/vue-cli#4916] opened 2019-12-02 15:24 UTC
### Version
4.1.1

### Reproduction link
[https://github.com/Rolanddoda/vue-cli-issue](https://github.com/Rolanddoda/vue-cli-issue)

### Environment info

<details>
<summary>Details</summary>
<pre>
  System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 12.13.0 
    Yarn: 1.19.1 
    npm: 6.13.1

  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.1.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.1
    @vue/cli-plugin-babel: ^4.1.0 => 4.1.1
    @vue/cli-plugin-eslint: ^4.1.0 => 4.1.1
    @vue/cli-plugin-router:  4.1.1
    @vue/cli-plugin-vuex:  4.1.1
    @vue/cli-service: ^4.1.0 => 4.1.1
    @vue/cli-shared-utils:  4.1.1
    @vue/component-compiler-utils:  3.0.2
    @vue/eslint-config-prettier: ^5.0.0 => 5.1.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found

</pre>
</details>

### Steps to reproduce
- Clone the repo
- npm install
- npm run serve (See the lint errors there)
- stop the serve
- npm run serve 

> ### **After npm install, when you run `npm run serve`, lint errors are shown.**
>
> ### **But that happens only the first time.**

### What is expected?
`npm run serve` should always show lint errors.

### What is actually happening?
Every time after, `npm run serve` will not show lint errors.

---
It seems that the `npm run serve` shows lint errors from files that are actually in git changes and not all the files that are presented in the app.

So if you manually create a lint error, it will show in the terminal. But if you commit the lint error, stop the server and re-run the server then the lint error will not show.

Of course, `npm run serve` should show all errors disregarding if they are already committed or not.

**Comment by sodatea** [comment] 2019-12-06 08:03
Duplicate of #3065 and contributions are welcome.

**Closed by sodatea** 2019-12-06 08:03 UTC
