### ISSUE TITLE
vue create issue: Cannot find module 'debug'

### ISSUE THREAD

**Issue by ayush987goyal** [vuejs/vue-cli#833] opened 2018-02-13 06:31 UTC
### Version
3.0.0-alpha.12

### Steps to reproduce
run the following
`vue create my-app`

### What is expected?
It should scaffold the app.

### What is actually happening?
```
module.js:557
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Goyal\AppData\Roaming\npm\node_modules\@vue\cli\lib\Creator.js:2:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by nikakoy131** [comment] 2018-02-13 07:33
Same issue
node -v v8.9.4
npm -v 5.6.0
Returning to v3.0.0-alpha.11 fix issue

**Comment by Samjin** [comment] 2018-02-13 07:59
Sam here. And there are other bugs too. I am reverting back to v2

**Comment by Sun1ive** [comment] 2018-02-13 09:47
same here
node 9.5.0
npm 5.6.0
linux ubuntu x64

**Comment by 4eek** [comment] 2018-02-13 11:15
See #831

**Comment by posva** [comment] 2018-02-13 11:22
Duplicate of #831

**Closed by posva** 2018-02-13 11:22 UTC

**Comment by ayush987goyal** [comment] 2018-02-13 11:26
what's the solution? Might it have already been included in the alpha12 release right?

**Comment by singhkong** [comment] 2018-02-13 16:36
When can we expect this fix to be published to yarn?

**Comment by NathanMacedo** [comment] 2018-07-08 20:18
I solved the same problem with upgrading npm's version:
Node Version: 8.11.3
NPM Version: 6.1.0
Vue version: 3.0.0-rc.3
