### ISSUE TITLE
vue-cli 3.9.0新建项目运行时报错Module build failed (from ./node_modules/eslint-loader/index.js): Error: Cannot find module 'E:\workSpace\test\node_modules\eslint\lib\api.js/package.json'     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)     at Function.Module._load (internal/modules/cjs/loader.js:562:25)     at Module.require (internal/modules/cjs/loader.js:690:17)     at require (internal/modules/cjs/helpers.js:25:18)     at Object.module.exports (E:\workSpace\test\node_modules\eslint-loader\index.js:170:23)  You may use special comments to disable some warnings. Use // eslint-disable-next-line to ignore the next line. Use /* eslint-disable */ to ignore all warnings in a file.

### ISSUE THREAD

**Issue by jinxinkai** [vuejs/vue-cli#4234] opened 2019-07-03 20:02 UTC
### Version
3.9.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 10.16.0 - D:\soft\node\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - D:\soft\node\npm.CMD
  Browsers:
    Edge: 40.15063.674.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue create test  
-Babel  
-Router  
-vuex  
-CSS Pre-processors  
-Linter / Formatter  

cd test
npm run serve

E:\workSpace\test>npm run serve

> test@0.1.0 serve E:\workSpace\test
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                       3:47:58 AM

Module build failed (from ./node_modules/eslint-loader/index.js):  
Error: Cannot find module 'E:\workSpace\test\node_modules\eslint\lib\api.js/package.json'  
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)  
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)  
    at Module.require (internal/modules/cjs/loader.js:690:17)  
    at require (internal/modules/cjs/helpers.js:25:18)  
    at Object.module.exports (E:\workSpace\test\node_modules\eslint-loader\index.js:170:23)  

You may use special comments to disable some warnings.  
Use // eslint-disable-next-line to ignore the next line.  
Use /* eslint-disable */ to ignore all warnings in a file.  

### What is expected?
可以运行

### What is actually happening?
E:\workSpace\test>npm run serve

> test@0.1.0 serve E:\workSpace\test
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                       3:47:58 AM

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'E:\workSpace\test\node_modules\eslint\lib\api.js/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.module.exports (E:\workSpace\test\node_modules\eslint-loader\index.js:170:23)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

**Comment by richardtallent** [comment] 2019-07-03 20:09
Duplicate of #4231

**Closed** 2019-07-03 20:09 UTC

**Comment by jinxinkai** [comment] 2019-07-03 20:24
it's going well after I tried to install eslint-loader@2.1.2
