### ISSUE TITLE
Can't launch the dev server on port 80 on Windows

### ISSUE THREAD

**Issue by Julien-R44** [vuejs/vue-cli#4206] opened 2019-06-28 17:42 UTC
### Version
3.8.4

### Reproduction link
[https://github.com/Julien-R44/vue-cli-bug-reproduction](https://github.com/Julien-R44/vue-cli-bug-reproduction)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: ^3.8.0 => 3.8.0
    @vue/cli-plugin-eslint: ^3.8.0 => 3.8.0
    @vue/cli-service: ^3.8.0 => 3.8.4
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Just run `npm run serve` in the repository I've created to illustrate the bug ( ? ). 

### What is expected?
Launch the web server on port 80.

### What is actually happening?
The web server is listening to port 81 instead of 80.

---
I tried to launch run the `npm run serve` as an administrator but that don't change anything. 

I've make a simple test with webpack and webpack dev server to see if the issue was related to vue-cli : i'm launching the web server with this config : 
```
...
devServer: {
    host: '127.0.0.2',
    port: 80
}
...
```
And it works, I can access to my project by typing 127.0.0.2 in my browser

That also proves nothing is already listening on port 80.

Thanks !

**Comment by sodatea** [comment] 2019-07-01 06:39
I'm sorry but this project works totally fine on my Windows 10 virtual machine… Maybe it's not a bug of Vue CLI, but caused by something else?

**Comment by Julien-R44** [comment] 2019-07-01 08:58
The dev server is listening on port 80 and not 81 ? Damn, I don't understand.
I will dockerize my application as a workaround but I will try to investigate further. Thanks for your time

**Comment by RemiKalbe** [comment] 2019-07-11 19:01
Same issue here but instead 81 it listen on port 1024 for some reason 🤯

**Comment by sodatea** [comment] 2019-11-06 14:25
Closing this issue as we couldn't reproduce it and there haven't been any similar issues reported for the last 4 months.

**Closed by sodatea** 2019-11-06 14:25 UTC
Labels: cannot reproduce

**Comment by christhofer** [comment] 2020-08-06 05:06
This is also happened to me. I'm was trying to serve my vue as http://app.test, and have my php projects to serve as api in http://api.app.test.
Even though I set the port to 80, `npm run serve` will listen on port 81 instead.

But if I disable my apache, and rerun `npm run serve`, it will listen to port 80, so I think it can't share the port with apache.

**Comment by Nebosmile** [comment] 2021-05-26 10:59
i got the same problem.
after 10 min of work, vue cli start reload on port 81. but my second app listen port 80
