### ISSUE TITLE
node-ipc 用了最新版本含有peacenotwar 模块

### ISSUE THREAD

**Issue by dean5277** [vuejs/vue-cli#7056] opened 2022-03-16 09:41 UTC
### Version
5.0.3

### Environment info
```
"node_modules/@vue/cli-shared-utils": {
      "version": "3.12.1",
      "resolved": "https://registry.npmmirror.com/@vue/cli-shared-utils/-/cli-shared-utils-3.12.1.tgz",
      "integrity": "sha512-jFblzRFjutGwu5utOKdVlPlsbA1lBUNNQlAThzNqej+JtTKJjnvjlhjKX0Gq0oOny5FjKWhoyfQ74p9h1qE6JQ==",
      "dev": true,
      "dependencies": {
        "@hapi/joi": "^15.0.1",
        "chalk": "^2.4.1",
        "execa": "^1.0.0",
        "launch-editor": "^2.2.1",
        "lru-cache": "^5.1.1",
        "node-ipc": "^9.1.1",
        "open": "^6.3.0",
        "ora": "^3.4.0",
        "request": "^2.87.0",
        "request-promise-native": "^1.0.7",
        "semver": "^6.0.0",
        "string.prototype.padstart": "^3.0.0"
      }
    }
```

### Steps to reproduce
npm i
npm run build

### What is expected?
希望固定版本或者不要使用node-ipc

### What is actually happening?
npm ERR! code E451
npm ERR! 451 Unavailable For Legal Reasons - GET https://registry.npmmirror.com/peacenotwar - [UNAVAILABLE_FOR_LEGAL_REASONS] peacenotwar was blocked, reason: security (operator: cnpmcore_admin/61f154594ce7cf8f5827edf8)

**Comment by mjanthony** [comment] 2022-03-16 11:17
It appears that the [node-ipc](https://github.com/RIAEvangelist/node-ipc) package now includes [peacenotwar](https://github.com/RIAEvangelist/peacenotwar) as a dependency.

There are a lot of complaints under the node-ipc issue page:
https://github.com/RIAEvangelist/node-ipc/issues

I discovered this by finding "WITH-LOVE-FROM-AMERICA.txt" on my desktop.

**Comment by shugen002** [comment] 2022-03-16 15:55
https://github.com/vuejs/vue-cli/issues/7054#issuecomment-1068677029 
已经锁了版本。

**Comment by shugen002** [comment] 2022-03-16 16:07
https://github.com/vuejs/vue-cli/issues/7054#issuecomment-1068677029
我check了一下，似乎5.0.3已经锁了9.2.1了，9.2.1应该是一个干净的版本。。。。

**Comment by MidSpike** [comment] 2022-03-16 16:18
> [#7054 (comment)](https://github.com/vuejs/vue-cli/issues/7054#issuecomment-1068677029) 我check了一下，似乎5.0.3已经锁了9.2.1了，9.2.1应该是一个干净的版本。。。。

For English speakers here:
> [#7054 (comment)](https://github.com/vuejs/vue-cli/issues/7054#issuecomment-1068677029) I checked, it seems that 5.0.3 has locked 9.2.1, 9.2.1 should be a clean version. . . .

**Comment by no-identd** [comment] 2022-03-16 21:17
Wew lads. Since #7054 just got locked, this issue is basically a dupe, and nobody there had offered this consideration yet:

Wow this's some Kindergarten shit. Lying about API key validity acting like it was never valid, deleting comments, this sure smells like a shitty false flag attempt and like @RIAEvangelist actually represents a Russian state actor engaging in Inverse agiprop to rile up Russian internal support for the "special operating"

#NotNearlyParanoidEnough

And now I'm out & turning off notifications for this #smh

**Comment by Akryum** [comment] 2022-03-16 21:23
Duplicate of #7051 and #7054

**Closed as completed by Akryum** 2022-03-16 21:23 UTC
