### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Marka83** [vuejs/vue-cli#656] opened 2017-11-30 08:27 UTC
I can't install vue-cli. 
I reinstalled node.js but it didn't help.
Complete log is in attachment.
[2017-11-30T08_16_34_678Z-debug.log](https://github.com/vuejs/vue-cli/files/1516997/2017-11-30T08_16_34_678Z-debug.log)

**Comment by a062670** [comment] 2017-11-30 08:32
CoffeeScript has moved!

https://www.npmjs.com/package/coffee-script

**Comment by Jackliu007888** [comment] 2017-11-30 08:39
now how can i use vue-cli ? i installed coffeescript -g ,but it didn't work.

**Comment by a062670** [comment] 2017-11-30 08:46
I have the same trouble.

Waiting for vue-cli to update...

**Comment by serdem** [comment] 2017-11-30 09:17
Same problem, I can't use vue-cli any more

**Comment by agogex** [comment] 2017-11-30 09:36
+1 The same problem. How to fix it?

**Comment by pkoecker** [comment] 2017-11-30 10:21
+1 Same Issue

**Comment by lihua123569** [comment] 2017-11-30 11:01
Same problem

**Comment by posva** [comment] 2017-11-30 11:08
Duplicate of #655

**Closed by posva** 2017-11-30 11:08 UTC

**Comment by avatarvb** [comment] 2018-06-01 22:35
hello i juste remove the folder @vue from my desktop C:\Users\Labo\AppData\Roaming\npm
