### ISSUE TITLE
error Command failed with exit code 132.

### ISSUE THREAD

**Issue by dmitriyl99** [vuejs/vue-cli#3920] opened 2019-04-30 10:57 UTC
### Version
3.6.3

### Environment info
```
System:
    OS: Linux 4.15 elementary OS 5.0 Juno
    CPU: (2) x64 Intel(R) Celeron(R) CPU  N3050  @ 1.60GHz
  Binaries:
    Node: 12.0.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.108
    Firefox: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.7.0 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.7.0 
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0 
    @vue/cli-service: ^3.7.0 => 3.7.0 
    @vue/cli-shared-utils:  3.7.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    vue: ^2.6.10 => 2.6.10 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-router: ^3.0.3 => 3.0.6 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.6.3

```

### Steps to reproduce
vue create project_name
any configuration
yarn serve / npm run serve or just yarn build / npm run build
recieve error

### What is expected?
I expected a working start template for my project

### What is actually happening?
I recieve error, when i'm trying to build new project 

This is output in my terminal:
``` 
$ vue-cli-service serve
INFO  Starting development server...
98% after emitting CopyPlugin  
Fatal error in , line 0
Check failed: U_SUCCESS(status).
FailureMessage Object: 0x7ffe77a8ef50Illegal instruction
error Command failed with exit code 132.
```

**Comment by sodatea** [comment] 2019-04-30 11:27
Duplicate of https://github.com/vuejs/vue-cli/issues/3883 and please upgrade to Node.js v12.1.0

**Closed by sodatea** 2019-04-30 11:27 UTC
