### ISSUE TITLE
'Add vue-router' fails on Windows 10 powershell

### ISSUE THREAD

**Issue by lauri108** [vuejs/vue-cli#2036] opened 2018-08-02 07:19 UTC
### Version
3.0.0-rc.10

### Node and OS info
Node 9.11.1 / npm 6.2.0 / Windows 10

### Steps to reproduce
1. start vue UI in powershell
2. Enter an existing project
3. choose 'Add vue-router'

### What is expected?
Adds dependency vue-router (and makes the required changes into Vue.app?)

### What is actually happening?
TypeError: Cannot read property 'routerHistoryMode' of undefined
    at module.exports (C:\dev\cfdt-plc-ui\node_modules\@vue\cli-service\generator\router\index.js:10:26)
    at Generator.plugins.forEach (C:\Users\Lauri\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:96:7)
    at Array.forEach (<anonymous>)
    at new Generator (C:\Users\Lauri\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:94:13)
    at Function.runGenerator (C:\Users\Lauri\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:111:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

---
I've installed 3.0.0-rc.10, which eliminated previous error https://github.com/vuejs/vue-cli/issues/1876 but this is a new error beyond that.

**Comment by yyx990803** [comment] 2018-08-03 18:49
Duplicate of #2034

**Closed by yyx990803** 2018-08-03 18:49 UTC
Labels: awaiting reproduction, feat: ui
