### ISSUE TITLE
Cannot build app (3.0.0-beta.1)

### ISSUE THREAD

**Issue by soanvig** [vuejs/vue-cli#904] opened 2018-02-28 19:54 UTC
### Version
3.0.0-alpha.13

### Reproduction link
[https://github.com/soanvig/vue-cli-issue](https://github.com/soanvig/vue-cli-issue)

### Steps to reproduce
1. Create application using `vue create test-vue` (**version 3.0.0-beta.1**, which is not included in issue creator)
2. Enter application directory `cd test-vue`
3. Run `yarn build`

### What is expected?
The build finishes.

### What is actually happening?
```
Building for production...buffer.js:202
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at new Buffer (buffer.js:158:17)
    at writeOut (/mnt/pliki/Repos/test-vue/node_modules/webpack/lib/Compiler.js:334:17)
    at require.forEach (/mnt/pliki/Repos/test-vue/node_modules/webpack/lib/Compiler.js:345:12)
    at /mnt/pliki/Repos/test-vue/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/mnt/pliki/Repos/test-vue/node_modules/async/dist/async.js:1055:9)
    at eachOf (/mnt/pliki/Repos/test-vue/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/mnt/pliki/Repos/test-vue/node_modules/async/dist/async.js:3158:5)
    at emitFiles (/mnt/pliki/Repos/test-vue/node_modules/webpack/lib/Compiler.js:315:21)
    at /mnt/pliki/Repos/test-vue/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
error An unexpected error occurred: "Command failed.\nExit code: 1\nCommand: sh\nArguments: -c vue-cli-service build\nDirectory: /mnt/pliki/Repos/test-vue\nOutput:\n".
info If you think this is a bug, please open a bug report with the information provided in "/mnt/pliki/Repos/test-vue/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

---
From yarn-error.log:
```
Yarn version: 
  1.4.0
Node version: 
  8.9.4
Platform: 
  linux x64
```

Exactly the same error on Windows 7 x64 after `yarn install` and `yarn build`

**Comment by yyx990803** [comment] 2018-02-28 23:37
This seems to be duplicate of #893 and fixed by #897.

**Closed by yyx990803** 2018-02-28 23:37 UTC
