### ISSUE TITLE
The latest version is not compatible with ie 9?

### ISSUE THREAD

**Issue by An0nymous0** [vuejs/vue-cli#1139] opened 2018-04-17 14:00 UTC
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/vuejs/vue-cli/releases/tag/v3.0.0-beta.6](https://github.com/vuejs/vue-cli/releases/tag/v3.0.0-beta.6)

### Steps to reproduce
1.vue.config.js 

module.exports = {
    configureWebpack: {
        entry: [
            'babel-polyfill',
            './src/main.js'
        ]
    }
}

2.main.js

import 'babel-polyfill'

3.npm run serve

SCRIPT1002:语法错误

### What is expected?
IE9-IE11正常访问

### What is actually happening?
IE9 无法正常访问

**Comment by posva** [comment] 2018-04-17 14:46
Duplicate of #858

**Closed by posva** 2018-04-17 14:46 UTC
