### ISSUE TITLE
Issue with using vue-cli with private bitbucket repo

### ISSUE THREAD

**Issue by rwb7041** [vuejs/vue-cli#403] opened 2017-03-16 19:22 UTC
I've got a customized version of the webpack template that I'm using on my projects. Hosting it on a public github account works fine, but my organization has decided to go with private bitbucket repositories. I copied my github repository to bitbucket and went to test creating a new vue app with the cli and my bitbucket template with the following command:

`vue init -c bitbucket:rwb7041/vuetemplate myproject`

I get the following error:
`vue-cli · Failed to download repo vuejs-templates/myproject: 'git clone' failed with status 128`

So next I tried creating the myproject directory and running the following inside that directory:
`vue init -c bitbucket:rwb7041/vuetemplate`

And I got the following error (after responding 'Y' to the question of generating project in the current directory:
`vue-cli · Local template "bitbucket:rwb7041/vuetemplate" not found.`

I am using version 2.8.1 of the vue-cli. What am I doing incorrectly?

**Comment by znck** [comment] 2017-03-17 07:38
Unencrypted SSH key should be configured for git.

This is probably caused by missing ssh key or encrypted key asking for password or host mismatch.

**Comment by rwb7041** [comment] 2017-03-17 12:20
That's not it because my keys are correctly set up as I can clone/push/pull/etc from the repo just fine

**Comment by rwb7041** [comment] 2017-03-17 12:45
I believe part of my issue is that the version of vue-cli installed via npm does not have the changes referenced to in issue #355. I went ahead and cloned master and ran it again, and now I'm getting 
`vue-cli · Failed to download repo bitbucket:beltrw/vuetemplate: 'git clone' failed with status 128`

**Comment by rwb7041** [comment] 2017-03-17 14:54
After digging around more into what's going on, beyond the issue of the changes mentioned in #355 not being in the version npm installs, I've found the cause of my problem with `'git clone' failed with status 128`. I'm on windows using Git Bash as my terminal, and the path being generated for where to clone the template is `C:\Users\username\.vue-templates\bitbucket:rwb7041-vuetemplate`. This path is an invalid path in Git Bash, and should be more like `/c/Users/username/.vue-templates/...`.

**Comment by rwb7041** [comment] 2017-03-21 23:02
Is there any chance or timeline of when the version of the vue-cli installed by npm will be updated to include some of these changes (specifically the ones mentioned in #355 and fixed by  #341)?

**Comment by zigomir** [comment] 2017-03-22 02:24
try `npm install -g vuejs/vue-cli`

**Comment by rwb7041** [comment] 2017-03-22 12:42
That seems to have done the trick. Thanks @zigomir. Still not sure why executing `vue init -c bitbucket:rwb7041/vuetemplate myproject` fails, but creating a `myproject` directory and running `vue init -c bitbucket:rwb7041/vuetemplate` from within the `myproject` directory works. I'm guessing a small problem with the command line arguments being picked up incorrectly maybe?

**Comment by rwb7041** [comment] 2017-03-22 13:07
Actually, looks like I spoke too soon. `npm install -g vuejs/vue-cli` worked on my MacBook, but on my Windows machine, I'm getting the following error whether I try to use my template on bitbucket or one of the official templates: `C:\Users\rwb7041\AppData\Roaming\npm\node_modules\vue-cli\node_modules\rx-lite\rx.lite.js:75
    throw e;
    ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at MuteStream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at MuteStream.emit (events.js:188:7)
    at MuteStream.write (C:\Users\rwb7041\AppData\Roaming\npm\node_modules\vue-cli\node_modules\mute-stream\mute.js:116:8)
    at Object.exports.clearLine (C:\Users\rwb7041\AppData\Roaming\npm\node_modules\vue-cli\node_modules\inquirer\lib\utils\readline.js:50:13)
    at module.exports.ScreenManager.clean (C:\Users\rwb7041\AppData\Roaming\npm\node_modules\vue-cli\node_modules\inquirer\lib\utils\screen-manager.js:92:8)
    at module.exports.ScreenManager.render (C:\Users\rwb7041\AppData\Roaming\npm\node_modules\vue-cli\node_modules\inquirer\lib\utils\screen-manager.js:26:8)
    at Prompt.render (C:\Users\rwb7041\AppData\Roaming\npm\node_modules\vue-cli\node_modules\inquirer\lib\prompts\confirm.js:85:15)
    at Prompt._run (C:\Users\rwb7041\AppData\Roaming\npm\node_modules\vue-cli\node_modules\inquirer\lib\prompts\confirm.js:65:8)`

I've tried running `npm uninstall -g vue-cli` and reinstalling the vue-cli, but I get the same error each time.

**Comment by unthunk** [comment] 2017-03-22 22:13
I am seeing this and a few related issues when using a custom template hosted on a non-github domain.  Using macOS and I've switched my vue-cli install to vuejs/vue-cli as per @zigomir 's comment above.

Depending on what combo of flags you use and if vue-cli already has the custom template cached you will get the 'git clone' failed with status 128 message or run into other issues.  The 128 error is occurring when the download-git-repo dep tries to run gitclone (git-clone dep) into the already existing directory in ~/.vue-templates - this is also mentioned in #355 .


**-c and --clone flags**
`vue init -c github:example.com:user/template-repo --clone myproject`
- with template-repo not yet cached in .vue-templates, template clone will work fine
- if template-repo exists in ~/.vue-templates, 'git clone' failed with status 128 error will occur


**-c flag**
`vue init -c github:example.com:user/template-repo myproject`
- when vue-cli runs, "myproject" is assigned to the template variable. program.args looks like:
program.args [ 'myproject',
  'github:example.com:user/template-repo' ]
So when run() gets called, isLocalPath(template) evaluates as false, then in checkVersion if (!hasSlash) evaluates false (because it is checking for the position of a '/' in template, which is set to "myProject") and is then treated as an official template.  Vue-cli will then hang on the "downloading template" spinner.


**--clone flag**
`vue init github:example.com:user/template-repo --clone myproject`
Vue-cli will prompt if you want to "Generate project in current directory?"


**no flags**
`vue init github:example.com:user/template-repo myproject`
- with template-repo not yet cached in .vue-templates:
Vue-cli will assign the correct value to template (github:example.com:user/template-repo), then run() will flow to the else statement in checkVersion() and the correct value will be passed though downloadAndGenerate() to the download-git-repo dep.  Download-git-repo will then pass this to its gitlab() fn, and because there is no clone flag will construct a public URL like: https://github.pie.apple.com/lucas-myers/gobots/archive/master.zip.  Thus, master.zip will be the contents of the template-repo folder in ~/.vue-templates and /lib/generate.js with throw an error "ENOENT: no such file or directory" because none of the expected paths/files exist.
- if template-repo exists in ~/.vue-templates:
Vue-cli will create the project without throwing any errors.  However, it will use the cached version of the template in  ~/.vue-templates, see also #409 .


Based on the above, this makes it challenging to use a custom template not hosted on github/bitbucket (whether https or ssh).  In order to always get a current copy of the custom template (HEAD), you would have to first delete the template from ~/.vue-templates and then use both the -c and --clone flags with vue init.  Using no flags would be feasible if 1.) it didn't default to the cached version if present and 2.) if /lib/generate.js checked to see if master.zip was downloaded to the ~./vue-templates/template-repo folder and if so expanded it.  It would probably be best if all valid options for download-git-repo's shorthand syntax and clone flag were supported from vue init.

Sorry, I am not able to submit a PR on this at this time, but hopefully this is enough to go on to fix. Cheers!

**Comment by rwb7041** [comment] 2017-03-22 23:14
I'm seeing the exact behavior @unthunk describes on my MacBook, but I'd like to add 2 things for Windows.

1. When running the vue cli commands in Git Bash (or mingw), the git clone attempts to store the template in `C:\Users\username\.vue-templates` which cause the clone to fail with a status of 128 because Git Bash will translate that as C:Usersusername.vue-templates`
2. The other problem I'm seeing on Windows is when specifying a repository with the colon to indicate a particular host (i.e., `bitbucket:owner/template`), the directory that the `git clone` command tries to clone into is `~/.vue-templates/bitbucket:owner/repo`. On Windows, file and folder names can't contain colons, so this cause the `git clone` to fail with a status of 128

Hopefully this makes sense and is enough to go on for a fix. Thanks

**Comment by dvic** [comment] 2017-04-04 07:26
I'm having the same problem on my Mac both with Github and Gitlab private repo's. Is there a way to have vue-cli output more debugging info?

**Comment by calvernaz** [comment] 2017-04-16 06:45
I was having the same issue when using the full URL to the template. The short version seems to work just fine. 

`vue init calvernaz/vue-plugin-template tags-plugin`

instead of

`vue init https://github.com/calvernaz/vue-plugin-template tags-plugin`

**Comment by scnich** [comment] 2017-05-04 12:22
Is there any updates regarding this?

Trying to "vue init" using a private bitbucket repo still doesn't work :(

**Comment by unthunk** [comment] 2017-05-04 15:35
You can workaround by checking out your private template and installing from the lcoal copy:

`vue init ~/fs/path/to-custom-template my-project`

You will probably want to git pull on the local copy of the template before you vue init from it.

**Comment by steven-klein** [comment] 2017-05-05 15:43
@unthunk is correct about using the --clone flag.  It's required when you are using private repo's which is noted in the [download-git-repo](https://github.com/flipxfx/download-git-repo/blob/master/index.js) readme.

@rwb7041 @scnich Additionally, take note that the shorthand notation for custom templates will not work in private repos either.  Instead of ``bitbucket:username/repo`` use ``bitbucket.org:username/repo``

Lastly, as @unthunk suggested, the first init using the --clone flag will work just fine.  But subsequent usages will through an error.  This is because the directory already exists and this appears to be coming from git-clone.  So, you can either nuke the template cache: 

```rm -rf ~/.vue-templates``` 

before each usage, which guarantees you get the latest version of your private repo, or you can clone it locally and install from the local path, or use the --offline flag to get the last cached template.  In both cases you run the risk of using an out of date template.

```vue init --offline bitbucket.org:username/repo --clone my-project```

Documentation just need to reflect the requirement of the --clone flag for private repo's.  The error where the cached template causes errors on subsequent uses might best be solved by fixing the caching issues in #409, by removing the cached template first, that error should be avoided.

**Comment by steven-klein** [comment] 2017-05-05 16:47
Pull request #450 addresses removing existing template directories which resolves the issue where the subsequent clones of private repo's fail.

**Closed** 2017-05-07 13:26 UTC
