### ISSUE TITLE
Chrome corrupts downloads over https in Google cloud when service worker is used

### ISSUE THREAD

**Issue by QuantumInformation** [vuejs/vue-cli#3392] opened 2019-01-30 11:00 UTC
### Version
3.3.0

### Reproduction link
[https://github.com/QuantumInformation/quantumjs](https://github.com/QuantumInformation/quantumjs)

### Environment info
```
Doesn't give any output
```

### Steps to reproduce

Can anyone see a reason why the Vue Service working breaking downloads over https in Google cloud?

The links are http://quantumjs.com/brochures/JavaScript-Bootcamp.pdf (works)

https://quantumjs.com/brochures/JavaScript-Bootcamp.pdf

I was able to reproduce this issue only by accessing my website’s home page first, this added a Service worker cookie to my browser which seems to be the root cause of this behaviour as when removed the page https://quantumjs.com/brochures/JavaScript-Bootcamp.pdf loads correctly.

### What is expected?
Pdf downloads when clicking on the link on the website

### What is actually happening?
corrupt pdf is shown

**Comment by LinusBorg** [comment] 2019-01-30 14:13
Please provide a step-by-step guide to reproduce the problem.

**Comment by QuantumInformation** [comment] 2019-01-30 14:18
Did you visit quantumjs index page over https first?

We think this issue only occurs over the UK, but it is definitely related to the service worker.

**Comment by LinusBorg** [comment] 2019-01-30 14:20
> Did you visit quantumjs index page over https first?

Yep. PDF displays fine.

Sidenote: I noticed you don't enforce HTTPS on your website. An easy improvement for the security of your visitors.

**Comment by QuantumInformation** [comment] 2019-01-30 14:21
Perhaps someone in the UK could try the same?

**Comment by QuantumInformation** [comment] 2019-01-30 14:23
This is what I see 
<img width="1284" alt="screen shot 2019-01-30 at 14 22 12" src="https://user-images.githubusercontent.com/216566/51987485-87989c80-249a-11e9-8d4c-bfebd392b3cc.png">

**Comment by LinusBorg** [comment] 2019-01-30 14:24
If this is even location-specific, you're probably looking at a bug in Chrome and/or a problem with your SSL certificate?

I'm not sure how Vue can do anything about this, most of all because the serviceworker is generated by a google plugin for their workbox lib.

**Comment by QuantumInformation** [comment] 2019-01-30 14:34
I've been talking to Google and they think its a client-side issue. Could it have something to do with styles loader?

**Comment by QuantumInformation** [comment] 2019-01-30 14:36
FF renders fine over https

**Comment by LinusBorg** [comment] 2019-01-30 14:41
> I've been talking to Google and they think its a client-side issue. 

vs.:

> FF renders fine over https

If it only happens in Chrome, I'd say at least aprt of the reason is on their side.

> Could it have something to do with styles loader? 

The error message makes it seem that style-loader is involved. Hard to debug without a way to reproduce it.

My first idea would be that a bug in chrome make the page try and execute the javascript as if it's displaying an HTML page rather than a PDF preview, and consequently failing to find an element to inject styles into?

**Comment by QuantumInformation** [comment] 2019-01-30 14:45
I'm stuck for ideas atm. I pinged Google:

https://issuetracker.google.com/issues/123249408#comment10

**Comment by sodatea** [comment] 2019-04-22 11:27
Closing as there's nothing we can do here.

**Closed by sodatea** 2019-04-22 11:27 UTC
Labels: feat: pwa, upstream
