### ISSUE TITLE
option to not have service worker

### ISSUE THREAD

**Issue by etktnse** [vuejs/vue-cli#4154] opened 2019-06-16 14:35 UTC
### What problem does this feature solve?
Some people just do not want a service worker. It should be optional and should be in config file somewhere. And it seems like people are lookign for ways. For example I have 2 builds that are a website and 2 builds for Iphone and Android webview. I do not want service worker for my webview exports. This is not just me : https://stackoverflow.com/questions/52800904/disable-pwa-plugin-in-vue-cli-3

### What does the proposed API look like?
When pwa serviceWorker:false, is set in config file, It actually does not do anything with service worker even when the service worker files are present. So it can be excluded from certain builds

**Comment by sodatea** [comment] 2019-06-16 14:43
Duplicate of https://github.com/vuejs/vue-cli/issues/3830

**Closed by sodatea** 2019-06-16 14:43 UTC
