### ISSUE TITLE
 Hot-Module-Replacement (HMR) NOT working with vue-cli-service build --watch 

### ISSUE THREAD

**Issue by maxxdev** [vuejs/vue-cli#2992] opened 2018-11-22 10:38 UTC
### Version
3.1.3

### Reproduction link
[https://bitbucket.org/maxx/hrm-vue-cli-watch-bug](https://bitbucket.org/maxx/hrm-vue-cli-watch-bug)

### Node and OS info
Node 8.12.0 / Vagrant / Ubuntu 16.04 / VirtualBox / Windows 10

### Steps to reproduce
* Create project from https://cli.vuejs.org/guide/creating-a-project.html#vue-create
* go to /app/test/hello-world
* npm install
* npm vue-cli-service build --watch --mode development OR sudo npm run watch
* add any string in /src/components/HelloWorld.vue

### What is expected?
rebuild dist folder at once any file in project changing

### What is actually happening?
Dist folder didn't rebuilding when file is changed

---
Tried https://github.com/vuejs/vue-cli/issues/2051 - fail.

But vue-cli-service serve works fine and rebuildat once file changing

**Comment by sodatea** [comment] 2018-11-22 12:05
Does this help: https://github.com/webpack/webpack/issues/6262?

**Comment by maxxdev** [comment] 2018-11-22 13:43
No. it doesn't

**Comment by injitools** [comment] 2018-11-25 16:50
for me HMR for vue files working only for this app mounting method

`window.appVue = new Vue({
  router,
  store,
  render: (h) => h(App),
}).$mount('#app');`

and not working for this

`window.appVue = new Vue({
  el: '#app',
  router,
  store,
  components: {App},
  template: '<App/>'
})
`

**Comment by maxxdev** [comment] 2018-11-26 06:30
Both  doesn't work for me

**Comment by LinusBorg** [comment] 2018-11-30 14:23
Closing since not reproducible.

**Closed by LinusBorg** 2018-11-30 14:23 UTC
Labels: needs reproduction

**Comment by oswaldofreitas** [comment] 2019-02-26 18:21
maybe this can help someone: https://webpack.js.org/configuration/watch/#changes-seen-but-not-processed
