### ISSUE TITLE
HotReload breaks components rendering when 'component' has 'key' property set inside keep-alive

### ISSUE THREAD

**Issue by daniele-orlando** [vuejs/vue-cli#3366] opened 2019-01-24 22:10 UTC
### Version
3.3.0

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.9 Debian GNU/Linux 
9 (stretch) 9 (stretch)
    CPU: (2) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. See the [Demo video](https://www.dropbox.com/s/z7eqzglkurvynqj/Demo.mov)
2. Download the attached archive [Bug.zip](https://github.com/vuejs/vue-cli/files/2793828/Bug.zip) and extract it
3. `npm install`
4. `./node_modules/.bin/vue-cli-service serve`
5. Edit the file `src/ui/project-editor-view.vue` changing the JavaScript portion in any way and see HMR failing

See `src/ui/main-view.vue` which contains additional note.

### What is expected?
Hot Reload should work as expected

or 

the usage of 
```
<keep-alive>
    <component :key="key" :is="component"/>
</keep-alive>
```
should be forbidden at all.

### What is actually happening?
Components get unmounted without any error or reason, resulting in a lot of struggles looking for the reason of the mysterious vanishing.

I don't know if this is an intended behavior, but the result is misleading.

**Comment by LinusBorg** [comment] 2019-01-26 11:03
I would assume that has to be solved in the Vue core repository, probably a bug with `<keep-alive>`. It works fine without that component.

**Comment by daniele-orlando** [comment] 2019-01-26 20:36
@LinusBorg If you can not transfer the ticket, I can recreate it on the Vue core repo. Do I proceed in this way?

**Comment by LinusBorg** [comment] 2019-01-26 20:47
That would be apprechiated. 

Also please provide the reproduction as a github repository if possible. 

And link to this issue here.

**Comment by daniele-orlando** [comment] 2019-01-26 23:55
Similar issue has been posted on vuejs/vue but has been moved on vuejs/vue-loader, where two related issues are still open.

vuejs/vue#8282
vuejs/vue-loader#700
vuejs/vue-loader#1332
vuejs/vue-router#2150

They seam to be all related.

So, I'm wondering if it a problem of the `keep-alive` component or of the vue-loader.

**Comment by franciscolourenco** [comment] 2019-04-26 05:58
Any developments on this? It ruins hmr..

**Comment by LinusBorg** [comment] 2019-04-26 07:08
I'll close this since this is tracked in the mentioned issues. Please look up progress there.

**Closed by LinusBorg** 2019-04-26 07:08 UTC
Labels: bug, upstream
