### ISSUE TITLE
baseUrl ignored when building a library

### ISSUE THREAD

**Issue by katerlouis** [vuejs/vue-cli#2339] opened 2018-08-23 11:09 UTC
### Version
3.0.1

### Node and OS info
node 10.7.0, npm 6.3.0

### Steps to reproduce
– unzip the project (https://dumbo.design/project-source-dump.zip)
   _[please tell me when you have downloaded it, I want to delete the file]_
– npm install the dependencies
  – either use vue-cli UI and build a library in production mode 
  – or do `vue-cli-service build --mode production --dest distLIB --target lib --name telekomConfigurator --dashboard` in terminal (command extracted from vue-cli UI console)
– open dist/demo.html
– observe missing static assets (font should be a sans-serif and there are supposed to be arrows left and right – The illustration is inline SVG)

![image](https://user-images.githubusercontent.com/1983382/44522538-285a8300-a6d7-11e8-8ef9-aeda365ba5ad.png)

![image](https://user-images.githubusercontent.com/1983382/44522555-3b6d5300-a6d7-11e8-9fc0-76b89c027a49.png)

### What is expected?
Static assets displayed

### What is actually happening?
Static assets aren't displayed / found
Look at `dist/telekomConfigurator.css` and search for `font-face`, the specified URL is `../fonts/`
although the fonts-folder and the css file looking for the fonts are on the same level.

---
When I build a webapp, the baseUrl of `./` is respected. No matter if I put the app in the webspace root or in a subfolder, assets are found. I tried playing with different baseUrls, no matter what I do, nothing changes.

For example: look at the `demo.html` at the `<script>` tags, no matter what you put in the baseUrl, the top looks like that:
```html
<script src="./telekomConfigurator.umd.js"></script>
<link rel="stylesheet" href="./telekomConfigurator.css">
```
notice the `./`

I thought it could be my use of the `@` alias (`~@` in css) – tried without it and still get wrong paths.

[EDIT]
It seems this issue is specific to my project? Tested a fresh vue-cli project and changed the `src` of the logo-image to `@/assets/logo.png` and it still works as expected. Haven't tried the fonts, though.

[EDIT2]
In the package.json you will find version 3.0.0-rc.12 declared; that was just my attempt to revert back to a previous version to check if this was a 3.0.1 bug– after editing the versions back to rc12 I ran `npm install` and hoped it would install the oldest version– the UI still showed 3.0.1, so I figure this hasn't worked.

**Comment by sodatea** [comment] 2018-08-23 14:52
Duplicate of https://github.com/vuejs/vue-cli/issues/2260
Please wait for the next release.

**Closed by sodatea** 2018-08-23 14:52 UTC
