### ISSUE TITLE
PWA plugin options not working

### ISSUE THREAD

**Issue by aayush420** [vuejs/vue-cli#1934] opened 2018-07-24 13:15 UTC
### Version
3.0.0-rc.5

### Reproduction link
[http://no.link](http://no.link)

### Steps to reproduce
1. Create a PWA using vue ui (vue cli 3.0.0-rc.5)
2. Add any PWA option like name in configuration in vue ui
3. Go to Tasks.
4. Select Serve and click on Start task.
5. Go to output tab and you can see the error.

### What is expected?
A PWA should be up and running and should be opened in a new tab in the browser.

### What is actually happening?
Nothing shows up until we go to the output tab where a stack trace kind of thing will be shown.
Following is an extract of the error:

```
$ vue-cli-service serve --open --mode development --host 127.0.0.1 --port 8080 --dashboard

 ERROR  Invalid options in vue.config.js: "org" is not allowed

 ERROR  Error: Process exited with code 1
Error: Process exited with code 1
    at exports.exit (C:\Users\aayush\projects\ui\pwa\node_modules\@vue\cli-shared-utils\lib\exit.js:7:11)
    at joi.validate.err (C:\Users\aayush\projects\ui\pwa\node_modules\@vue\cli-shared-utils\lib\validate.js:14:9)
    at internals.Object._validateWithOptions (C:\Users\aayush\projects\ui\pwa\node_modules\joi\lib\types\any\index.js:678:20)
    at module.exports.internals.Any.root.validate (C:\Users\aayush\projects\ui\pwa\node_modules\joi\lib\index.js:138:23)
    at exports.validate (C:\Users\aayush\projects\ui\pwa\node_modules\@vue\cli-shared-utils\lib\validate.js:8:7)
    at exports.validate (C:\Users\aayush\projects\ui\pwa\node_modules\@vue\cli-service\lib\options.js:44:3)
    at Service.loadUserOptions (C:\Users\aayush\projects\ui\pwa\node_modules\@vue\cli-service\lib\Service.js:317:5)
    at Service.init (C:\Users\aayush\projects\ui\pwa\node_modules\@vue\cli-service\lib\Service.js:72:30)
    at Service.run (C:\Users\aayush\projects\ui\pwa\node_modules\@vue\cli-service\lib\Service.js:188:10)
    at Object.<anonymous> (C:\Users\aayush\projects\ui\pwa\node_modules\@vue\cli-service\bin\vue-cli-service.js:22:9)
```

---
my vue.config.js(auto generated by vue ui) : : : : 
```

module.exports = {
  lintOnSave: undefined,

  org: {
    vue: {
      pwa: {
        workboxPluginMode: 'InjectManifest'
      }
    }
  }
};

```
Another configuration with the same issue : : : :
```

module.exports = {
  lintOnSave: undefined,

  org: undefined
};

```

**Comment by sodatea** [comment] 2018-07-24 13:35
Duplicate of #1890

**Closed by sodatea** 2018-07-24 13:35 UTC
