### ISSUE TITLE
The code indent is not satisfied when I using annotation @Component

### ISSUE THREAD

**Issue by jaune162** [vuejs/vue-cli#1887] opened 2018-07-18 06:58 UTC
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/jaune162/vue-typescript-mdeditor](https://github.com/jaune162/vue-typescript-mdeditor)

### Steps to reproduce
```
<script lang="ts">
import {Vue, Component} from 'vue-property-decorator';
import {State, Getter} from 'vuex-class';
import GroupItem from './GroupItem';

@Component({
    components: {
        GroupItem
    }
})
export default class GroupList extends Vue {
    @State('notebook/groups') groups: any;

    created() {
    }
}

</script>
```
**error info**
```
@Component({
    components: {
        GroupItem // ESLint: Expected indentation of 4 spaces but found 8. (indent)
    }
})  // ESLint: Expected indentation of 4 spaces but found 0. (indent)
```

### What is expected?
no indent error

### What is actually happening?
The code in `@Component` parameter must indent of 4 space for every lines.

---
### My .eslintrc.js

```
module.exports = {
    root: true,
    env: {
        node: true
    },
    'extends': [
        'plugin:vue/essential',
        '@vue/standard',
        '@vue/typescript'
    ],
    rules: {
        'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
        'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
    }
};
```

**Comment by Akryum** [comment] 2018-07-18 07:22
Duplicate of #1672

**Closed by Akryum** 2018-07-18 07:22 UTC
Labels: feat: eslint, feat: typescript
