### ISSUE TITLE
Init waiting

### ISSUE THREAD

**Issue by DCKT** [vuejs/vue-cli#6] opened 2015-12-31 14:07 UTC
Hi,

When you don't write the project name and just hit enter, the init is paused.
I work on Windows 10 with node 5.3.0 and the last vue-cli version.

**Comment by nblackburn** [comment] 2016-01-19 12:18
Duplicate, see #13

**Comment by chrisvfritz** [comment] 2016-03-14 04:18
@DCKT Can you confirm whether this is now fixed and close the issue if it is?

**Comment by skyronic** [comment] 2016-03-17 20:46
I'm closing this issue since it looks like a duplicate of another issue. If this issue persists, please reopen the issue.

**Closed by skyronic** 2016-03-17 20:46 UTC
