### ISSUE TITLE
Vue Project Manager not working

### ISSUE THREAD

**Issue by azzumaraydid7** [vuejs/vue-cli#5750] opened 2020-08-05 09:06 UTC
### Version
4.5.0

### Environment info
```
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Not Found
    Firefox: Not Found
    Safari: 13.0.5
  npmPackages:
    @vue/component-compiler-utils:  3.2.0 
    vue: ^2.6.11 => 2.6.11 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.3 
    vue-router: ^3.3.4 => 3.3.4 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuetify: ^2.3.7 => 2.3.7 
  npmGlobalPackages:
    @vue/cli: 4.4.6

```

### Steps to reproduce
Step 1. Open Projects

vue.runtime.esm.js:1888 TypeError: Cannot read property 'favorite' of null
    at filter (ProjectSelectList.vue?fd97:5)
    at Array.filter (<anonymous>)
    at render (ListFilter.vue:6)
    at Jt (vue.runtime.esm.js:3058)
    at rn (vue.runtime.esm.js:3231)
    at fn (vue.runtime.esm.js:3422)
    at hn (vue.runtime.esm.js:3353)
    at e._c (vue.runtime.esm.js:3491)
    at ProjectSelectList.vue?fd97:5
    at s.jt [as _l] (vue.runtime.esm.js:2630)

### What is expected?
List of project file

### What is actually happening?
Not display list of previous project

**Comment by forgivegod** [comment] 2020-08-05 14:51
This is caused by an error in your code.  See ProjectSelectList.vue for bad usage of myVar.favorite

Voting to close this

**Comment by hevans90** [comment] 2021-06-11 14:59
@forgivegod 

Maybe tell us how to fix this? I just imported a fresh CLI project in to the project manager and am experiencing this issue, with no other changes.

**Comment by Rofound** [comment] 2022-02-07 01:55
> ### Version
> 4.5.0
> 
> ### Environment info
> ```
>   System:
>     OS: macOS 10.15.3
>     CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
>   Binaries:
>     Node: 12.18.3 - /usr/local/bin/node
>     Yarn: 1.22.4 - /usr/local/bin/yarn
>     npm: 6.14.6 - /usr/local/bin/npm
>   Browsers:
>     Chrome: 84.0.4147.105
>     Edge: Not Found
>     Firefox: Not Found
>     Safari: 13.0.5
>   npmPackages:
>     @vue/component-compiler-utils:  3.2.0 
>     vue: ^2.6.11 => 2.6.11 
>     vue-hot-reload-api:  2.3.4 
>     vue-loader:  15.9.3 
>     vue-router: ^3.3.4 => 3.3.4 
>     vue-style-loader:  4.1.2 
>     vue-template-compiler: ^2.6.11 => 2.6.11 
>     vue-template-es2015-compiler:  1.9.1 
>     vuetify: ^2.3.7 => 2.3.7 
>   npmGlobalPackages:
>     @vue/cli: 4.4.6
> ```
> 
> ### Steps to reproduce
> Step 1. Open Projects
> 
> vue.runtime.esm.js:1888 TypeError: Cannot read property 'favorite' of null at filter (ProjectSelectList.vue?fd97:5) at Array.filter () at render (ListFilter.vue:6) at Jt (vue.runtime.esm.js:3058) at rn (vue.runtime.esm.js:3231) at fn (vue.runtime.esm.js:3422) at hn (vue.runtime.esm.js:3353) at e._c (vue.runtime.esm.js:3491) at ProjectSelectList.vue?fd97:5 at s.jt [as _l] (vue.runtime.esm.js:2630)
> 
> ### What is expected?
> List of project file
> 
> ### What is actually happening?
> Not display list of previous project

I got, I reproduced the bug.
The reason is because the projects object includes null.

The solution is to add a check：
<img width="911" alt="image" src="https://user-images.githubusercontent.com/26542093/152713051-415733f7-ae3b-4273-998a-90cab5dbb65d.png">

**Comment by Rofound** [comment] 2022-02-07 01:57
@yyx990803

**Closed** 2022-05-22 04:45 UTC
