### ISSUE TITLE
create vue-cli app failed

### ISSUE THREAD

**Issue by Qianshaojun** [vuejs/vue-cli#6568] opened 2021-07-02 08:15 UTC
### Version
4.5.13

### Environment info
```

 ERROR  Failed to compile with 1 error                                                                                                                                                                                下午4:04:40
 error  in ./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js

Module parse failed: Unexpected token (763:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }
| class RefImpl {
>     _rawValue;
|     _shallow;
|     _value;

 @ ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js 1:0-233 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 16:4-17 40:4-17 107:13-18 108:32-37 115:16-21 1958:8-13 1962:13-23 1968:35-45 1970:16-21 1973:21-31 2071:19-25 2094:8-12 2135:8-13 2210:29-34 2557:27-30 2558:26-29 2559:28-31 2905:16-29 2912:16-29 3043:28-36 3362:41-56 3378:28-33 3463:8-15 3500:32-37 3647:27-32 3823:29-34 3951:12-25 3958:12-25 4568:17-22 4592:13-18 5173:26-32 5336:8-21 5340:8-21 5755:16-20 5761:12-16 6296:27-32 6328:12-19 6338:16-23 6356:93-100 6357:15-20 6767:60-75 6768:60-75 6769:60-75 6770:59-74 6847:16-21 6997:16-21 7150:21-28 7160:8-21 7161:134-149 7162:8-21 7210:30-39 7264:8-21 7266:8-21 7314:23-38 7334:46-55 7334:56-63 7389:14-24 7576:21-26 7586:21-31 7593:24-34 7596:21-31 7624:53-58 7630:52-57 7696:48-53
 @ ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js
 @ ./node_modules/vue/dist/vue.runtime.esm-bundler.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.18.171:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

### Steps to reproduce
npm run serve

### What is expected?
npm run serve success

### What is actually happening?
npm run serve failed

**Comment by sodatea** [comment] 2021-07-02 08:26
Duplicate of https://github.com/vuejs/vue-cli/issues/6562#issuecomment-872784086

**Closed by sodatea** 2021-07-02 08:26 UTC

**Comment by tmaclucien** [comment] 2021-07-02 08:49
please, i got this issues today, did u solve it???

**Comment by Qianshaojun** [comment] 2021-07-02 08:51
> please, i got this issues today, did u solve it???

No I think it might be the VUE version of Vuecli integration

**Comment by tmaclucien** [comment] 2021-07-02 09:17
create a vue.config.js and put 
module.exports = {
  transpileDependencies: ['@vue/reactivity']
}

it will solve.
