### ISSUE TITLE
Command line Vue Create does not allow "Manual" selection

### ISSUE THREAD

**Issue by BenHayat** [vuejs/vue-cli#3460] opened 2019-02-15 03:38 UTC
### Version
3.4.0

### Environment info
```

C:\WINDOWS\system32>vue info

Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  Binaries:
    Node: 11.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 4.0.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmGlobalPackages:
    @vue/cli: Not Found


C:\WINDOWS\system32>vue --version
3.4.0

C:\WINDOWS\system32>
```

### Steps to reproduce
@VUE Team;

I'm running the latest Vue on a Windows 10 machine.
When I go to command line and I type vue create hello-world I get prompted for default or manual.
I try to use my down arrow key on the keyboard to highlight/select manual, but as soon as it gets selected, it jumps back to the default and does not allow me to select the manual mode.
I tried it 5 times with no luck.
So I ended up using the GUI version by using Vue ui and I was able to create a new project.
Hope this helps!
..Ben

### What is expected?
Vue Create my_proj to allow me to create a project with manual options

### What is actually happening?
When I use arrow key down to manual, it jumps back up to default

**Comment by sodatea** [comment] 2019-02-15 06:57
Duplicate of #3446 and it is a bug of Node v11.8+

**Closed by sodatea** 2019-02-15 06:57 UTC
