### ISSUE TITLE
3.0.0-rc.11 peer dependency update is a breaking change

### ISSUE THREAD

**Issue by cecotw** [vuejs/vue-cli#2114] opened 2018-08-08 15:32 UTC
### Version
3.0.0-rc.11

### Node and OS info
all

### Steps to reproduce
If your version is set to allow patch updates, for example:  "@vue/cli-service": "^3.0.0-rc.10", then when you install, you get version 3.0.0-rc.11. The move of vue-template-compiler to the peer dependencies makes this a breaking change, not a patch update.

```npm WARN @vue/cli-service@3.0.0-rc.11 requires a peer of vue-template-compiler@^2.0.0 but none is installed. You must install peer dependencies yourself.```

### What is expected?
Patch changes shouldn't break build

### What is actually happening?
Patch change added a peer dependency that is breaking the build.

---
This is fixable by adding this to the deps or pegging the version explicitly, but still breaking changes shouldn't be put on patch versions.

Thanks!

**Comment by Akryum** [comment] 2018-08-08 15:40
Duplicate of #2109

**Closed by Akryum** 2018-08-08 15:40 UTC

**Comment by yyx990803** [comment] 2018-08-08 15:57
RC version bumps are **not** patch changes.

**Comment by cecotw** [comment] 2018-08-08 16:09
Ahh yea you're right, should have said premajor. It started happening in AWS CodeBuild initially, so I tried a rebuild with a previous working build, and this one broke too. I took a look locally and did a clean checkout & npm install and I was able replicate. I believe npm will still install the latest premajor version with the ^. Should we peg this to an explicit version then?

The project was created a few months ago with the vue cli, not sure which exact version (I think beta-5) so the ^ got carried over from that. I updated it for rc-10 and must have missed the npm warning.

**Comment by cecotw** [comment] 2018-08-08 16:27
Word, thanks man! I was trying to align the code to the latest so we are ready for the stable 3.0 without much effort. 

Really appreciate all your work on vue & the cli by the way! We are using it for all our new projects, its just phenomenal all around.
