### ISSUE TITLE
main.ts should not add ".ts" extension when import typescript files

### ISSUE THREAD

**Issue by anymost** [vuejs/vue-cli#887] opened 2018-02-26 05:19 UTC
### Version
3.0.0-alpha.13

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-typescript/lib/convertImports.js](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-typescript/lib/convertImports.js)

### Steps to reproduce
when choose typescript and tslint config in vue-cli-dev, the tslint will check import statements cannot have ".ts" extension.  you should remove ".ts" extension in default main.ts file when users choose vue-router or vuex config and auto generate import statements.

### What is expected?
This bug should be fixed

### What is actually happening?
cannot pass tslint default checking.

---
none

**Comment by LinusBorg** [comment] 2018-02-26 08:25
Duplicate of #871

**Closed by LinusBorg** 2018-02-26 08:25 UTC
