### ISSUE TITLE
DevServer.before option need to access the WebpackDevServer Instance

### ISSUE THREAD

**Issue by mkanako** [vuejs/vue-cli#1886] opened 2018-07-18 06:55 UTC
### What problem does this feature solve?
```
before: (app, instance) =>{ 
    app.get('/show.html', (req, res, next) => {
        global.my.value = 1
        instance.invalidate()
        next()
    }
}
```
this configuration not work

instance is undefined

I've been studying for a long time to find out what the problem is

in cli-service/lib/commands/serve.js line 135

```
before (app) {
        // launch editor support.
        // this works with vue-devtools & @vue/cli-overlay
        app.use('/__open-in-editor', launchEditorMiddleware(() => console.log(
          `To specify an editor, sepcify the EDITOR env variable or `  
          `add "editor" field to your Vue project config.\n`
        )))
        // allow other plugins to register middlewares, e.g. PWA
        api.service.devServerConfigFns.forEach(fn => fn(app))
        // apply in project middlewares
        projectDevServerOptions.before && projectDevServerOptions.before(app)
      }
```
it didn't pass the second argument

webpack-dev-server  pass the Instance in second argument but vue-cli didn't pass it

### What does the proposed API look like?
the correct code
```
before (app,context) {
        // launch editor support.
        // this works with vue-devtools & @vue/cli-overlay
        app.use('/__open-in-editor', launchEditorMiddleware(() => console.log(
          `To specify an editor, sepcify the EDITOR env variable or `  
          `add "editor" field to your Vue project config.\n`
        )))
        // allow other plugins to register middlewares, e.g. PWA
        api.service.devServerConfigFns.forEach(fn => fn(app,context))
        // apply in project middlewares
        projectDevServerOptions.before && projectDevServerOptions.before(app,context)
      }
```

**Comment by Akryum** [comment] 2018-07-18 07:19
Duplicate of #1833

**Closed by Akryum** 2018-07-18 07:19 UTC
