### ISSUE TITLE
Vue CLI 5 warnings

### ISSUE THREAD

**Issue by litan1106** [vuejs/vue-cli#6247] opened 2021-01-27 23:45 UTC
### Version
5.0.0-alpha.3

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.50)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.2
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  5.0.0-alpha.3
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  5.0.0-alpha.3
    @vue/cli-plugin-babel: ~5.0.0-alpha.3 => 5.0.0-alpha.3
    @vue/cli-plugin-eslint: ~5.0.0-alpha.3 => 5.0.0-alpha.3
    @vue/cli-plugin-router: ~5.0.0-alpha.3 => 5.0.0-alpha.3
    @vue/cli-plugin-typescript: ~5.0.0-alpha.3 => 5.0.0-alpha.3
    @vue/cli-plugin-unit-jest: ~5.0.0-alpha.3 => 5.0.0-alpha.3
    @vue/cli-plugin-vuex: ~5.0.0-alpha.3 => 5.0.0-alpha.3
    @vue/cli-service: ~5.0.0-alpha.3 => 5.0.0-alpha.3
    @vue/cli-shared-utils:  5.0.0-alpha.3
    @vue/compiler-core:  3.0.5
    @vue/compiler-dom:  3.0.5
    @vue/compiler-sfc: ^3.0.4 => 3.0.5
    @vue/compiler-ssr:  3.0.5
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^7.0.0 => 7.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/reactivity:  3.0.5
    @vue/runtime-core:  3.0.5
    @vue/runtime-dom:  3.0.5
    @vue/shared:  3.0.5
    @vue/test-utils: ^2.0.0-0 => 2.0.0-rc.0
    @vue/web-component-wrapper:  1.2.0
    @zhuowenli/vue-feather-icons: ^5.0.2 => 5.0.2
    eslint-plugin-vue: ^7.2.0 => 7.5.0
    jest-serializer-vue:  2.0.2
    typescript: ~4.1.2 => 4.1.3
    vue: ^3.0.4 => 3.0.5
    vue-demi:  0.6.0
    vue-eslint-parser:  7.4.1
    vue-hot-reload-api:  2.3.4
    vue-jest: ^5.0.0-0 => 5.0.0-alpha.8 (3.0.7)
    vue-loader:  16.1.2 (15.9.6)
    vue-router: ^4.0.1 => 4.0.3
    vue-style-loader:  4.1.2
    vue-template-es2015-compiler:  1.9.1
    vuex: ^4.0.0-0 => 4.0.0-rc.2
```

### Steps to reproduce
yarn serve

### What is expected?
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
99% done plugins FriendlyErrorsWebpackPlugin

### What is actually happening?
DeprecationWarning

**Comment by fangbinwei** [comment] 2021-01-31 12:04
duplicate of  https://github.com/vuejs/vue-cli/issues/6236

**Closed by fangbinwei** 2021-01-31 12:04 UTC
