### ISSUE TITLE
Remove dependency on deprecated module 'request'

### ISSUE THREAD

**Issue by michaelkozakovsc** [vuejs/vue-cli#5331] opened 2020-03-28 06:30 UTC
### What problem does this feature solve?
@vue/cli-shared-utils currently depends on the module 'request'. This module has been deprecated as of a couple of days ago. 
https://github.com/request/request/issues/3142

Installations of vue apps now show a warning: "request@2.88.2: request has been deprecated,"

Let's figure out a replacement for 'request'

### What does the proposed API look like?
N/A

**Comment by sodatea** [comment] 2020-03-28 11:18
Duplicate of #5220 and contribution's welcome

**Closed by sodatea** 2020-03-28 11:18 UTC
