### ISSUE TITLE
devServer.proxy config only allow simple options for http-proxy-middleware

### ISSUE THREAD

**Issue by showapi** [vuejs/vue-cli#2439] opened 2018-09-05 08:00 UTC
### Version
3.0.1

### Node and OS info
Node 10.7.0 / yarn 1.7.0 / OS High Sierra

### Steps to reproduce
```
devServer: {
    port:3005,
    proxy:[
      {
        context: [
          '**',
          '!/js/appDist/**'
        ],
        target: 'http://'   ip.address()   ':8080',
        secure: false,

      }]
  }

```
### What is expected?
can use complete http-proxy-middleware config

### What is actually happening?
can't use Complicated http-proxy-middleware config

---
From the source it is clear that only simple matcher is supported, And it's not support Array config， For example reproduce
https://github.com/vuejs/vue-cli/blob/3def765ba438638b09c6e76547b85a29ddde3ba6/packages/%40vue/cli-service/lib/util/prepareProxy.js#L66

**Comment by sodatea** [comment] 2018-09-05 13:31
Duplicate of https://github.com/vuejs/vue-cli/issues/2285

**Closed by sodatea** 2018-09-05 13:31 UTC
