### ISSUE TITLE
npm run test:e2e selenium errors

### ISSUE THREAD

**Issue by joeSaad** [vuejs/vue-cli#2273] opened 2018-08-18 22:38 UTC
### Version
3.0.0

### Node and OS info
Node: v8.11.4, npm: 6.4.0, macOSX 10.12.6 and also tried on different machine Node:10.9.0, npm 6.2.0, macOSX 10.13.3

### Steps to reproduce
> vue create myrepo
> npm run test:e2e 

### What is expected?
e2e testing to work without errors

### What is actually happening?
errors

16:46:00.891 ERROR [SeleniumServer.boot] - Port 4444 is busy, please choose a free port and specify it using -port option

 ERROR  Error: Command failed: path2/myrepo/node_modules/nightwatch/bin/nightwatch --config path2/myrepo/node_modules/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js --env chrome
Error: Command failed: path2/myrepo/node_modules/nightwatch/bin/nightwatch --config path2/myrepo/node_modules/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js --env chrome
    at makeError (path2/myrepo/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (path2/myrepo/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

---
I have tried this on two mac machines and both produced the same error mentioned above

**Comment by yyx990803** [comment] 2018-08-19 02:56
As the message suggests, make sure your port 4444 is not being already used...

**Comment by joeSaad** [comment] 2018-08-19 04:30
I cleared that port several times and made sure nothing is using it. Still the error message appeared.

**Comment by yyx990803** [comment] 2018-08-20 00:27
Unfortunately, we can't reproduce this. What you can do is creating a `nightwatch.config.js` in your project (which will be merged into the [default config](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js)) to specify a different port.

**Closed by yyx990803** 2018-08-20 00:27 UTC
Labels: cannot reproduce, feat: e2e-nightwatch

**Comment by fritx** [comment] 2018-09-21 18:30
```plain
[Test] Test Suite
=====================

Running:  default e2e tests

Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ Error: connect ECONNREFUSED 127.0.0.1:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4444 }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! station-web@1.0.0 e2e: `node test/e2e/runner.js`
```
