### ISSUE TITLE
Cannot update vue-cli, not finding global cli-upgrade package. How do I update?

### ISSUE THREAD

**Issue by douglasg14b** [vuejs/vue-cli#3562] opened 2019-03-03 18:48 UTC
### Version
3.2.2

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
  Binaries:
    Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Not Found
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
n/a

### What is expected?
vue cli finds the package and updates

### What is actually happening?
vue cli fails to find the package, and requests that it be globally installed.

---
I cannot update vue cli, when I try I just get the error:

>Command vue upgrade requires a global addon to be installed.
>Please run npm install -g @vue/cli-upgrade and try again.

I have globally installed `@vue/cli-upgrade` already, but the error persists. 

How do I update vue cli in this case? Also, why does `vue info` show that the global `@vue/cli` is not found, when it is installed and I've been using vue-cli successfully?

If I run `npm list -g --depth=0` it shows the appropriate packages :

```
C:\Users\Douglas>npm list -g --depth=0
C:\Users\Douglas\AppData\Roaming\npm
 -- @vue/cli@3.4.1
 -- @vue/cli-upgrade@3.4.1
`-- gulp@4.0.0
```

**Comment by LinusBorg** [comment] 2019-03-03 19:18
Duplicate of #3417 

this feature isn't official yet and doesn't work well. Just update your packages like you normally do until we have finalized the feature.

**Closed by LinusBorg** 2019-03-03 19:18 UTC

**Comment by chrisbloom7** [comment] 2019-04-17 19:23
Then shouldn't the `--help` output be updated to remove the command or mark it experimental?

**Comment by douglasg14b** [comment] 2019-04-17 20:36
@chrisbloom7  That would make sense...
