### ISSUE TITLE
vue list error

### ISSUE THREAD

**Issue by kuma0605** [vuejs/vue-cli#147] opened 2016-08-17 02:58 UTC
xxxs-MacBook-Pro:~ dylan$ vue list

  Available official templates:

/usr/local/lib/node_modules/vue-cli/bin/vue-list:29
  JSON.parse(body).forEach(function (repo) {
                   ^

TypeError: JSON.parse(...).forEach is not a function
    at Request._callback (/usr/local/lib/node_modules/vue-cli/bin/vue-list:29:20)
    at Request.self.callback (/usr/local/lib/node_modules/vue-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/vue-cli/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/vue-cli/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by zigomir** [comment] 2016-08-17 04:17
I can't reproduce it in version 2.2.0. What version do you use?

**Comment by kuma0605** [comment] 2016-08-17 10:36
<img width="412" alt="screen shot 2016-08-17 at 6 35 36 pm" src="https://cloud.githubusercontent.com/assets/2958589/17733483/6c7eaa60-64a9-11e6-92ae-116afecff53b.png">

**Comment by kuma0605** [comment] 2016-08-17 10:37
It maybe a issue caused by network environment.

**Comment by LinusBorg** [comment] 2016-08-18 09:32
Try accessing https://api.github.com/users/vuejs-templates/repos from your browser. You should see a JSON response, an array containing information about all template repos.

I suspect you have a network problem when vue-cli is trying to read from this URL.

It would be an improvement to catch this error,

**Comment by ktsn** [comment] 2016-08-21 07:38
This may be same issue as #130?
PR is already sent (#131) but it is not merged.

**Comment by LinusBorg** [comment] 2016-08-23 08:06
Closing this issue in favor of #130

**Closed by LinusBorg** 2016-08-23 08:06 UTC
