### ISSUE TITLE
cli-plugin-eslint should replace `babel-eslint` to `@babel/eslint-parser`, as it changes name now.

### ISSUE THREAD

**Issue by tweet** [vuejs/vue-cli#5981] opened 2020-10-19 03:47 UTC
### Version
4.5.7

### Steps to reproduce
babel-eslint is now @babel/eslint-parser and has moved into the Babel monorepo.

---
https://github.com/vuejs/vue-cli/blob/5898fcb84827b9d47994247f1ead37b130d4bd4a/packages/%40vue/cli-plugin-eslint/eslintOptions.js#L17

Some background is from here.
https://github.com/babel/babel-eslint

**Comment by DRoet** [comment] 2020-10-19 15:28
duplicate of https://github.com/vuejs/vue-cli/issues/5734

**Closed** 2020-11-20 01:10 UTC
